### ISSUE TITLE
order solutes alphabetically in combo box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#101]
Discussion at 2/6/20 design meeting:

Customer request: Ability to reorder the liquids in the drop-down menu so they’re not listed by decreasing pH.
CM: “Drop-down menu” presumably means “combo box listbox”. This is not currently possible. There is no ability to reorder items for ComboBox (PhET-iO or otherwise). I recently did a lengthy rewrite of ComboBox, and I don’t know how we’d make this possible, or provide a PhET-iO API for it.  I also don’t know why we’d want to allow it. Recommended to push back.
KP: There question is making me wonder why we have it in this order too though? It seems odd not to have it mixed up, for better discovery.
CM: Do we need to find out what their motivation is for reordering the listbox?
KP: They probably just don’t want it ordered by pH.
SR: Add a Studio control for reordering an compacting combo box listbox? CM create issue
AR: What about adding additional items?
Decision: Alphabetize the order by English string

**Comment by pixelzoom** [comment]
Done. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks good @pixelzoom.

**Comment by arouinfar** [comment]
I could not find a reason in the design doc for ordering the the solutes by pH. In design meeting we speculated the reason was likely historical (solutes used to list pH values) rather than pedagogical.

This observation from interviews suggests that ordering by pH could be problematic.
> One student, who did not spend much time comparing solutions, drew conclusions based on the order of items in the dropdown menu

**Comment by pixelzoom** [comment]
Note to whoever regression tests this... The order of the solutes is hard-coded, see code from MacroModel.js below.   We don't attempt to alphabetize programmatically, since the solute names are translated, and we want this order to be fixed regardless of locale.

```js
      // @public solute choices, in order that they'll appear in the combo box
      // The order is alphabetical (English names), see https://github.com/phetsims/ph-scale/issues/101
      this.solutes = [
        Solute.BATTERY_ACID,
        Solute.BLOOD,
        Solute.CHICKEN_SOUP,
        Solute.COFFEE,
        Solute.DRAIN_CLEANER,
        Solute.HAND_SOAP,
        Solute.MILK,
        Solute.ORANGE_JUICE,
        Solute.SODA,
        Solute.SPIT,
        Solute.VOMIT,
        Solute.WATER
      ];
```

**Comment by KatieWoe** [comment]
Looks good in https://github.com/phetsims/QA/issues/514
