### ISSUE TITLE
make it possible to permanently turn off the "Neutral" indicator

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#102]
2/6/20 design meeting discussion:

Client request: Ability to remove the word “neutral” that appears in the beaker when the probe detects a pH of 7. 
CM: This is not entirely straightforward because visibility of “Neutral” is controlled by the sim, depending on pH.  If the client sets its visibleProperty to false, the sim will eventually set it to true. Options:
Wrap this neutralIndicatorNode inside of another Node, and let the client control the wrapper (easy).
Query parameter to disable the feature
PhET-iO specific Property to disable the feature (least desirable)
Decision: Do option (1).

**Comment by pixelzoom** [comment]
Done.  @arouinfar please verify in master.   To test:

1. Run in Studio
2. Navigate to phScale.macroScreen.view.neutralIndicatorNode.visibleProperty
3. Switch between 'Water' and other solutes with visibleProperty true and false

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom
