### ISSUE TITLE
add support for disabling auto-fill feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#104]
2/6/20 design meeting.  From #92:

> - [ ] There's a feature that autofills the beaker at startup and reset, or when a new solute is selected. It's used in ph-scale, but not in ph-scale-basics. Do we need to be able to disable this feature?

Decision: Yes. Add `autoFillEnabledProperty`

**Comment by pixelzoom** [comment]
Added:

```
phScale.macroScreen.model.autoFillEnabledProperty
phScale.microScreen.model.autoFillEnabledProperty
```

To test:

1. Start sim in Studio
2. Select a solute from the combo box, note that the beaker automatically fills to 0.5L
3. Change autoFillEnabledProperty to false
4. Select a solute from the combo box, note that the beaker remains empty
5. Press Reset All button, note that the beaker remains empty
6. Change autoFillEnabledProperty to true
7. Select a solute from the combo box, note that the beaker automatically fills to 0.5L

@arouinfar please verify in master.

**Comment by pixelzoom** [comment]
QA will need to know about this issue, so when it's verified, please change label to "status:fixed-awaiting-deploy".

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.
