### ISSUE TITLE
add ability to change solute name

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#110]
From 2/6/20 design meeting notes:

Client request: Ability to change the text property value of liquids listed in the drop-down menu.
CM: This is a “change string” type request. Did we decide that strings should generally be changed through query parameter? If not... this is problematic. Each solute is static, shared by all screens, and names are not intended to be mutable (name is not a Property).  If we change the solute name, it will affect all screens.  We could change the names that appear in the combo box, but then the model and view will be out of sync (using different names).  Note that the solute names are also in their tandem names (e.g. phScale.global.model.solutes.batteryAcid).
KP: A longterm goal is to switch locale after the sim is running, and have everything in the layout adapt. And it’s easier for an instructional designer to do it in Studio. So we are not going to use query parameters.
CM: I’d prefer to change in the model, rather than just in the view.
KP: OK to prototype using query parameter, compare to setting Property in Studio.
SR: Impossible to test things that are query-parameter based for API breakage.
SR and CM will discuss how to add tandem to TextNode that is the ComboBoxItem, refer to https://github.com/phetsims/phet-io/issues/1565.

**Comment by pixelzoom** [comment]
> SR and CM will discuss how to add tandem to TextNode that is the ComboBoxItem, refer to phetsims/phet-io#1565.

@samreid FYI.... I'm not planning to instrument the TextNodes in the ComboBox.  I'm going to add Solute `{Property.<string>} nameProperty`, and a listener for `nameProperty` in `SoluteComboBox.createItem`.

**Comment by pixelzoom** [comment]
Assigning to @samreid to review before I pass this on to @arouinfar. 

I have implemented as described in https://github.com/phetsims/ph-scale/issues/110#issuecomment-583151600.   An additional complication is that ComboBox is a fixed size, and not capable of growing if one of its items becomes longer.  So if a solute's name is changed, it's maxWidth is constrained to whatever the widest item was at startup - see SoluteComboBox lines 63 & 81.

**Comment by samreid** [comment]
This seems reasonable, and is an improvement.  The main disadvantage is that there is no obvious connection between the listBox items like `phScaleBasics.macroScreen.view.soluteComboBox.listBox.batteryAcid` and the corresponding solutes like: `phScaleBasics.global.model.solutes.batteryAcid`

I investigated a hack for rectifying this:

<details>

```diff

Index: js/ComboBoxListBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/ComboBoxListBox.js	(revision 1445d512af968a175a4164d4175443502d0cb323)
+++ js/ComboBoxListBox.js	(date 1581049794296)
@@ -117,6 +117,7 @@
       items.forEach( ( item, index ) => {
 
         // Create the list item node
+        const itemTandem = item.tandemName ? tandem.createTandem( item.tandemName ) : Tandem.OPTIONAL;
         const listItemNode = new ComboBoxListItemNode( item, highlightWidth, highlightHeight, {
           align: options.align,
           highlightFill: options.highlightFill,
@@ -126,7 +127,10 @@
           xMargin: 0.5 * options.xMargin,
           left: 0.5 * options.xMargin,
           top: ( 0.5 * options.yMargin ) + ( index * highlightHeight ),
-          tandem: item.tandemName ? tandem.createTandem( item.tandemName ) : Tandem.OPTIONAL
+          tandem: itemTandem
+        } );
+        listItemNode.addLinkedElement( item.value, {
+          tandem: itemTandem.createTandem( 'solute' )
         } );
         listItemNodes.push( listItemNode );
 

```

</details>

This links up the element like so:

![image](https://user-images.githubusercontent.com/679486/74001223-00d99380-4928-11ea-923c-19ba2675e714.png)

However, there are two problems: 
* this is still a 2-step process for editing the text (have to navigate to the solutes, then navigate to the child `nameProperty`
* This patch requires that all `item.value` are instrumented `PhetioObjects` which is true for pH-Scale Basics, but I'm not sure would be true across all sims.  So we would need to check or make that more robust.

I tinkered with adding the `nameProperty` as another linked element.  It is nice to edit the text of the combo box without leaving the combo box, but this is likely overkill.

![image](https://user-images.githubusercontent.com/679486/74001333-70e81980-4928-11ea-9573-f2fbdafa910a.png)

@pixelzoom what do you recommend?

**Comment by pixelzoom** [comment]
I don't think we need linked elements connection every listbox item back to its model element.   So let's proceed with what I've done so far. 

@arouinfar would you please review in master? To verify:

1. Run sim in Studio
2. Go to Macro screen
3. Choose a solute in combo box
4. Go to `global.model.solutes`, find the solute you selected in the combo box, edit its nameProperty.
5. Verify that the solute name in the combo box changes.
6. Switch to the Micro screen. Verify that the solute's name has also changed in the combo box there.

**Comment by arouinfar** [comment]
> I don't think we need linked elements connecting every listbox item back to its model element. 

Agreed. 

> @arouinfar would you please review in master? 

Master is behaving as expected @pixelzoom. Not sure if there is more that needs to be done in this issue, so back to you.
