### ISSUE TITLE
instrument values shown by H3O+/OH- Ratio view

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#112]
I'm not sure what to instrument here. Perhaps display the number of red (H30+) particles, number of blue (OH-) particles, and ratio?  But there are no Properties currently for these.   And this node is highly optimized to draw a lot of particles using Canvas, so I'm hesitant to add more overhead.

**Comment by pixelzoom** [comment]
... and if I did add Properties, then they would be set 1 at a time, and there would be invalid intermediate states until all 3 Properties had been set.

**Comment by pixelzoom** [comment]
@arouinfar I'm not sure what to do here.  Do you think we need instrumentation for this view? If so, what would you expect?

**Comment by arouinfar** [comment]
@pixelzoom I do not think we need to instrument the particles or the number of particles. A `ratioProperty` could potentially be useful, but I think we would want it to be calculated as `moleculeCountNode.countH3OProperty / moleculeCountNode.countOHProperty` rather than calculating the ratio from the number of red/blue particles.

**Comment by pixelzoom** [comment]
OK, I'll add `ratioProperty` as you've described in the previous comment.

**Comment by pixelzoom** [comment]
I added `ratioProperty` to `RatioNode`.  It can be moved elsewhere if you prefer, but this seems like the logical place for it, since the ratio is used only in the view, and only in `RatioNode`.  

Here's how it appears in the _Micro_ screen (_My Solution_  screen is similar):

<img width="646" alt="screenshot_121" src="https://user-images.githubusercontent.com/3046552/74385552-0b28e100-4db1-11ea-90c0-f2a68c5a1cc2.png">

Note that these is unavoidable floating-point error for 2 solutes: 
* "Coffee" ratio is 1E-5/1E-9 = 1E4, `ratioProperty` value is 9999.999999999998
* "Hand Soap" ratio is 1E-10/1E-4 = 1E-6, `rationProperty` value is 0.0000010000000000000002

@arouinfar please review in master.

**Comment by arouinfar** [comment]
@pixelzoom `ratioProperty` looks great in the tree!

> Note that these is unavoidable floating-point error for 2 solutes:

Understood, thanks.
