### ISSUE TITLE
set PhET-iO milestones

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#116]
Milestones in the [design document](https://docs.google.com/document/d/1RrILoln3Jdo1hSA1eOtTJN-j8015Q9clqP1caORVYCE/edit?ts=5e39ad31#heading=h.6y75prk97rmc) need to be fleshed out.  They are currently:

> **Milestones**
> * TBD: design completed
> * TBD: begin QA
> * TBD: any preliminary deliverables?
> * deliver to client “around end of March or mid April, if possible”

**Comment by arouinfar** [comment]
I do not know any more than you do @pixelzoom, so I'll leave it to @kathy-phet.

**Comment by kathy-phet** [comment]
Done.
