### ISSUE TITLE
autoFill query parameter 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#121]
From #117:

- [ ] We would like `macroScreen.model.autoFillEnabledProperty` and `microScreen.model.autoFillEnabledProperty` hooked up to a common query parameter to allow phet-brand users to access this feature. A flag called `autoFill` seems appropriate.

**Comment by pixelzoom** [comment]
>  A flag called `autoFill` seems appropriate.

Assuming that you want the sims to continue to behave as they do now without this query parameter...  A flag (i.e. `?autoFill`) is not appropriate. It needs to be a boolean (e.g. `autoFill=false`), default `true` for "pH Scale" and `false` for "pH Scale: Basics".  

@arouinfar is that acceptable.

**Comment by arouinfar** [comment]
Thanks for the clarification @pixelzoom. Let's proceed with the boolean query parameter.

**Comment by pixelzoom** [comment]
Implemented in the above commits. @arouinfar please verify in master. Be sure to test both ph-scale and ph-scale-basics.

**Comment by arouinfar** [comment]
Looks good in ph-scale and ph-scale-basics on master. Thanks @pixelzoom!
