### ISSUE TITLE
delete model.dropper.emptyProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#122]
From #117:

- [ ] Is `model.dropper.emptyProperty` ever false? Under what circumstance would the dropper ever be empty?

**Comment by pixelzoom** [comment]
I investigated, and the dropper is never empty in this sim, so it's not needed in the model.  My guess is that it was added because SCENERY_PHET/DropperNode has an optional `emptyProperty`.   

Would you like me to remove it from the model?

**Comment by arouinfar** [comment]
> I investigated, and the dropper is never empty in this sim, so it's not needed in the model.

Thanks @pixelzoom. Let's remove it from the model.

**Comment by pixelzoom** [comment]
`model.dropper.emptyProperty` was removed in the above commits. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
👍
