### ISSUE TITLE
add linked element to drainFaucetNode and waterFaucetNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#123]
From #117:

- [ ] `view.drainFaucetNode` and `view.waterFaucetNode` should probably both have a linked property that points back to the appropriate `model.x.flowRateProperty`. However, the flowRateProperty is read only, so we are not sure if adding *property is appropriate here. Does there need to be some property in the view that sets the flowRateProperty in the model?

**Comment by pixelzoom** [comment]
The dropper has a fixed flow rate; it's either on or off. `flowRateProperty` there should be replaced with a boolean on/off Property.

The 2 faucets have a variable flow rate, modeled in `FaucetNode` as `flowRateProperty`.  This Property is controlled by the faucet handle in the view.  (So no, there does not need to be some Property in the view that sets the flowRateProperty in the model.)

Adding a linked element from the faucets back to their `flowRateProperty` is easy. 

I experimented with making the water Faucet `flowRateProperty` have `phetioReadOnly: false`.  It's doable, but there's currently a problem.  The user controls `flowRateProperty` via a Studio slider and fills the beaker, like this:

<img width="637" alt="screenshot_158" src="https://user-images.githubusercontent.com/3046552/75593401-7a096980-5a42-11ea-90a8-8d9de761a8e4.png">

When the beaker becomes full, `flowRateProperty` needs to be set to zero, and remain zero until the beaker becomes "un-full" -- basically the Property needs to become read-only while the beaker is full. Similarly, the drain faucet's `flowRateProperty` needs to become read-only when the beaker is empty.   And that's currently impossible.

So... What is the use case where `flowRateProperty` needs to be `phetioReadOnly: false`?

**Comment by arouinfar** [comment]
Thanks the for the explanation @pixelzoom.

> Adding a linked element from the faucets back to their flowRateProperty is easy, I'll make it so.

Great!

> So... What is the use case where flowRateProperty needs to be phetioReadOnly: false?

Until now, we haven't seen read only linked properties, so we weren't sure if we could link directly to the `flowRateProperty` or not. I can't see a reason for it to be phetioReadyOnly: false, but thanks for the investigation.

**Comment by pixelzoom** [comment]
Next question.... `FaucetNode` is a common-code UI component.  Do you want this linked element to be added in `FaucetNode` (for all sims), or in sim-specific code (only for ph-scale and ph-scale-basics)?

**Comment by pixelzoom** [comment]
I said:
> The dropper has a fixed flow rate; it's either on or off. `flowRateProperty` in the dropper should be replaced with a boolean on/off Property.

This isn't true.  The `flowRateProperty` is important for the dropper.  It allows us to autoFill more quickly that manually filling.   So no change here, and `dropper.flowRateProperty` will remain `phetioReadOnly: true`.

**Comment by arouinfar** [comment]
> Next question.... `FaucetNode` is a common-code UI component. Do you want this linked element to be added in FaucetNode (for all sims), or in sim-specific code (only for ph-scale and ph-scale-basics)?

Great question @pixelzoom. Is `flowRateProperty` part of the common `FaucetNode`? If so, then it seems appropriate to add the linked property in common code. 

I remember a similar discussion around `isPlayingProperty` and `PlayPauseButton`, and we decided to handle it sim-by-sim since `isPlayingProperty` was specified in the sim. Not sure if this example is parallel or not.

**Comment by pixelzoom** [comment]
`flowRateProperty` is a required parameter for all FacuetNode instances:

```js
/**
 *
 * @param {number} maxFlowRate
 * @param {Property.<number>} flowRateProperty
 * @param {Property.<boolean>} enabledProperty
 * @param {Object} [options]
 * @mixes AccessibleSlider
 * @constructor
 */
function FaucetNode( maxFlowRate, flowRateProperty, enabledProperty, options ) {
```

It would be up to the client whether and how to instrument `flowRateProperty`. Then FaucetNode could add the link it `flowRateProperty` is instrumented.   

Let me know how you'd like to proceed.

**Comment by arouinfar** [comment]
@pixelzoom let's proceed with adding the linked property to `FaucetNode` itself.

**Comment by pixelzoom** [comment]
Done in the above commit.  This affects all sims that have a FaucetNode, and their API files have been updated. 

@arouinfar please verify in master.

**Comment by arouinfar** [comment]
This is looking good in master @pixelzoom. I don't know the full subset of sims that have both a FaucetNode and have been instrumented, but I did take a peek at beers-law-lab and things are looking good there too.
