### ISSUE TITLE
make enabledProperty read-only for zoom buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#124]
From #117:

- [ ] These properties should be read only, since the sim should control when these buttons are disabled rather than the client.
`microScreen.view.graphNode.linearGraphNode.zoomButtonGroup.zoomInButton.enabledProperty`
`microScreen.view.graphNode.linearGraphNode.zoomButtonGroup.zoomOutButton.enabledProperty`

**Comment by pixelzoom** [comment]
Done in the above commit.  @arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom!
