### ISSUE TITLE
restructure graph Properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#125]
From #117:

- [ ] Would it be possible to factor out all of the graph values into something like `microScreen.view.graphNode.values`? Currently, the same value appears in both the linearGraphNode and the logarithmicGraphNode (e.g. `microScreen.view.graphNode.linearGraphNode.valueH2OProperty` and `microScreen.view.graphNode.logarithmicGraphNode.valueH2OProperty`). To further complicate things, these values don't have units because they switch between concentration (mol/L) and quantity (mol) which could get confusing when filtering the data stream. 

Proposed structure:

```
-graphNode
  -values
    +valueConcentrationH2OProperty
    +valueQuantityH2OProperty
    (Repeat for H3O and OH)
```

**Comment by pixelzoom** [comment]
This is going to be a significant change.    It's going to require big changes to `LinearGraphNode` , `LogarithmicGraphNode`, and `GraphIndicatorNode`.   Estimate is 2-4 hours.

I think the right way to do this is to add a `Graph` model element, like this:

```
-model.graph
  +valueConcentrationH2OProperty
  +valueQuantityH2OProperty
  +valueConcentrationH30Property
  +valueQuantityH3OProperty
  +valueConcentrationOHProperty
  +valueQuantityOHProperty
```

... where all of these Properties are `phetioReadOnly: true`.

Then I'll link the graph view to the model, like this:

```
-view.graphNode
  *graph
```

@arouinfar does that sound acceptable?

**Comment by pixelzoom** [comment]
> To further complicate things, these values don't have units because they switch between concentration (mol/L) and quantity (mol) which could get confusing when filtering the data stream.

FYI... This was intentional in the original implementation, so that we are efficient with our use of resources and only compute what we're displaying. By changing this to have separate Properties for concentration vs quantity, half of the information we're computing will not be displayed.  This shouldn't be a performance problem in this specific case, but it's not recommend as a general approach.  You'll also find sims where Properties are updated only when something is visible, and doing otherwise may cause performance problems.

**Comment by pixelzoom** [comment]
> To further complicate things, these values don't have units because they switch between concentration (mol/L) and quantity (mol) which could get confusing when filtering the data stream.

FYI... This was intentional in the original implementation, so that we are efficient with our use of resources and only compute what we're displaying. By changing this to have separate Properties for concentration vs quantity, half of the information we're computing will not be displayed.  This shouldn't be a performance problem in this specific case, but it's not recommend as a general approach.  You'll also find sims where Properties are updated only when something is visible, and doing otherwise may cause performance problems.  That said...

This is going to be a significant change.    It's going to require big changes to `LinearGraphNode` , `LogarithmicGraphNode`, and `GraphIndicatorNode`.   Estimate is 2-4 hours.

I don't like adding `view.graphNode.values` (the "proposed structure"). I recommend adding a `Graph` model element, like this:

```
-model.graph
  +valueConcentrationH2OProperty
  +valueQuantityH2OProperty
  +valueConcentrationH30Property
  +valueQuantityH3OProperty
  +valueConcentrationOHProperty
  +valueQuantityOHProperty
```

... where all of those Properties are derived from pH and volume, and are therefore `phetioReadOnly: true`.

Then I'll link the graph view to the model, like this:

```
-view.graphNode
  *graph
  ...
```

@arouinfar does that sound acceptable?

**Comment by pixelzoom** [comment]
I went ahead and did this.   It took 1.75 hours.

Here's `model.graph` in Studio:

<img width="279" alt="screenshot_159" src="https://user-images.githubusercontent.com/3046552/75601093-0cc2fc00-5a75-11ea-9320-4db828de459d.png">

Here's `model.graphNode` in Studio:

<img width="260" alt="screenshot_160" src="https://user-images.githubusercontent.com/3046552/75601098-23695300-5a75-11ea-8a8b-846c3a80b878.png">

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! @kathy-phet and I reviewed this in studio and it is looking really good. We think `graph` could be a bit more descriptive though, perhaps `model.graphData` or `model.graphValues`? We don't have a strong preference between these, so we'll leave it up to @pixelzoom.

**Comment by pixelzoom** [comment]
The convention for mode/view naming is (by example) `Ball` and `BallNode`; `Particle` and `ParticleNode`, etc.   The model and view class names match, with `Node` appended to the model class name. That's why I went with `Graph` and `GraphNode`.  

Options:

(a) Violate the convention and do something like `GraphData` and `GraphNode`.  This will require additional internal documentation and would likely be flagged as "bad" in a code review.  Not recommended, but if this is what you want, I'll do it. 
(b) Stick with `Graph` and `GraphNode` and make the general convention clear in designer documentation.  This is my recommendation. 
(c) Come up with new names for both `Graph` and `GraphNode`, so that the convention is followed.

**Comment by arouinfar** [comment]
@pixelzoom thanks for the clarification. We didn't realize we would be breaking naming conventions. Let's stick with `Graph` and `GraphNode`.

**Comment by pixelzoom** [comment]
Reopening.  While working on #119, I realized that these Properties should not be in `model.graph`.  They should be added to `model.solution` in the Micro and My Solution screens, because they are Properties of the solution.   This will also make it easier to accomplish #119.

@arouinfar OK to proceed with this change?

**Comment by arouinfar** [comment]
Yes, @pixelzoom please proceed with this change.

**Comment by pixelzoom** [comment]
These Properties have been moved to `microScreen.model.solution` and `mySolutionScreen.model.solution` as part of #119.   

@arouinfar please review in master.

**Comment by pixelzoom** [comment]
You'll also see 3 `numberOf*MoleculesProperty` elements under `model.solution`.  These moved here from `view.moleculeCountNode` for these same reason as the graph Properties.

**Comment by arouinfar** [comment]
@pixelzoom the contents of `model.solution` look good.  However, I'm not seeing linked properties under `view.moleculeCountNode` and `view.graphNode.*GraphNode.indicator*Node` to the associated model properties.

**Comment by pixelzoom** [comment]
I was under the impression that we were using linked elements judiciously, not adding them in every view component, so I didn't add them to `view.moleculeCountNode`.  But it sounds like you want them, so I've added them.  Looks like this in Studio:

<img width="291" alt="screenshot_178" src="https://user-images.githubusercontent.com/3046552/76261854-8353bc80-6220-11ea-8717-0de0e4c459a8.png">

For `view.graphNode.*GraphNode.indicator*Node`... The indicators are wired up to internal/intermediate Properties that switch their value between concentration and quantity depending on `view.graphNode.graphUnitsProperty`.   So they are not currently capable of linking to something like `concentrationProperty` and `quantityProperty` because they have no knowledge of those Properties.   I can change that, but it's going to be a significant change, ~1 hour.  Let me know what you'd like me to do.

**Comment by pixelzoom** [comment]
... and if I add links to `concentrationProperty` and `quantityProperty` in `view.graphNode.*GraphNode.indicator*Node`, are you also going to want a link to `view.graphNode.graphUnitsProperty`, so that you know which Property is being displayed?

**Comment by arouinfar** [comment]
@pixelzoom I think it's generally nice for view elements to have links to their corresponding model elements. In the case of `moleculeCountNode` it lets clients know where exactly the corresponding data resides. That's all looking good in master currently.

Thinking about this a bit more, I don't think we want to link to `concentration*Property` and `quantity*Property`, in the GraphIndicatorNodes. Reviewing this with @kathy-phet, we think it would be helpful if these 6 properties were just under `view.graphNode`. We do not need to link to the `graphUnitsProperty` since that is all contained within `view.graphNode`.

**Comment by pixelzoom** [comment]
Reviewed with @arouinfar and @kathy-phet on Zoom.  They said everything looks good, see screenshot below.  Closing.

<img width="321" alt="screenshot_196" src="https://user-images.githubusercontent.com/3046552/76807015-a219fc00-67a8-11ea-83b5-b05af2c9a126.png">
