### ISSUE TITLE
Hide ArrowNode if GraphIndicatorNode is not pickable

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#126]
For #117 

On the My Solution Screen, the GraphIndicatorNode for H3O+ and OH- are interactive. They are decorated with a green arrow to cue the interactivity.

![image](https://user-images.githubusercontent.com/8419308/75726282-48410e80-5c9f-11ea-9ab4-9796b512285c.png)

PhET-iO clients may choose to set the pickableProperty of `indicatorH3ONode` and/or `indicatorOHNode` to false to prevent users from changing the pH via the GraphIndicatorNodes. However, the green arrows remain which leads to a strange UX.

We don't want to instrument these ArrowNodes, but it would be nice if they could be hidden when the corresponding element isn't interactive. Would it be possible for the visibility of the ArrowNode to listen to the pickableProperty of the corresponding GraphIndicatorNode?

**Comment by pixelzoom** [comment]
Done in the above commit.  Reminder that pickableProperty is not boolean -- it can be true, false, or null.   If it's true or null, then the arrows are visible; if it's false then the arrows are invisible. 

@arouinfar please review in master.

**Comment by arouinfar** [comment]
> Reminder that pickableProperty is not boolean -- it can be true, false, or null. If it's true or null, then the arrows are visible; if it's false then the arrows are invisible.

Understood, thanks @pixelzoom. The behavior is looking good in master.
