### ISSUE TITLE
State of solution is not being properly saved

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#127]
Discovered in #117.

When launching the sim from studio, the state of the solution is not correctly saved. The sim loads with the correct solute, but all other values in `model.solution` revert to the sim defaults. 

There is an additional quirk with the auto fill feature. If `autoFillEnabledProperty` is true when launched, the dropper will slowly fill the beaker to 0.50 L (as opposed to usual autoFill speed). If `autoFillEnabledProperty` is false when launched, the beaker will be empty. 

Method 1:
1. Open sim and select Macro or Micro
2. Choose a different solute
3. Add some water to the beaker
4. Launch the sim. The solute was remembered, but the dropper slowly auto fills the the beaker to the default volume.

Method 2:
1. Open sim and select My Solution
2. Change pH with GraphIndicatorNode or the pH probe.
3. Launch the sim. The pH goes back to the default value of 7.00.

**Comment by pixelzoom** [comment]
I thought that perhaps the autoFill was blowing away the saved state of the solution. But running with `?autoFill=false` I see that's not the case.   It looks like the solute and water volumes are not being restored. 

Disabling `autoFillEnabledProperty` when state is restored is a separate (and complicated) problem.

**Comment by pixelzoom** [comment]
Solution state is actually being saved correct.  But when it's restored, this bit of code in Solution.js is executed, and empties the beaker:

```js
    // solute
    this.soluteProperty.link( () => {

      // reset to volumes that were specified in the constructor
      this.waterVolumeProperty.set( waterVolume );
      this.soluteVolumeProperty.set( soluteVolume );
    } );
```

This is another case of "don't do that while PhetioEngine is restoring state".   And after working with @samreid on this same type of problem in https://github.com/phetsims/beers-law-lab/issues/247 today, my understanding is that we don't have a general solutions.

Assigning to PhET-iO team for guidance.  What is the general solution for short-circuiting code that should not be executed when PhetioEngine is restoring state?

**Comment by pixelzoom** [comment]
I created https://github.com/phetsims/phet-io/issues/1624 to come up with a general solution, assigned to the PhET-iO team.  This issue is blocked until that is addressed.

**Comment by pixelzoom** [comment]
Changing the above code to this does the job. But we need something clearer for general use.

```js
    this.soluteProperty.link( () => {

      const settingState = _.hasIn( window, 'phet.phetIo.phetioEngine' ) &&
                           phet.phetIo.phetioEngine.phetioStateEngine.isSettingState;

      if ( !settingState ) {
        // reset to volumes that were specified in the constructor
        this.waterVolumeProperty.set( waterVolume );
        this.soluteVolumeProperty.set( soluteVolume );
      }
    } );
```

**Comment by pixelzoom** [comment]
Over in phetsims/phet-io#1624,  `phet.joist.sim.isSettingPhetioStateProperty` was added to determine whether PhetioEngine is setting state. I'll proceed with that.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please verify in master. Run the sim, make some changes in Studio, press "Launch", and verify that solution matches the changes made in Studio.  Bonus points for testing with `?autoFill=false` and `?autoFill=true`.

**Comment by arouinfar** [comment]
This is working beautifully in master for both `autoFill=true` and `autoFill=false`. Thanks @pixelzoom!
