### ISSUE TITLE
My Solution screen tandem should be mySolutionScreen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#129]
Discovered during #117

The 3rd screen is called `My Solution` (singular).
![image](https://user-images.githubusercontent.com/8419308/75730488-4cbef480-5caa-11ea-8296-219858984950.png)

However, the tandem name is currently `mySolutionsScreen` (plural).
![image](https://user-images.githubusercontent.com/8419308/75730707-dbcc0c80-5caa-11ea-9f73-895ef050b62b.png)

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please verify in master.

**Comment by arouinfar** [comment]
👍
