### ISSUE TITLE
graphScaleProperty is irrelevant for My Solution screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#130]
From https://github.com/phetsims/ph-scale/issues/117#issuecomment-593706368:

- [ ] `mySolutionsScreen.view.graphNode.graphScaleProperty` is technically irrelevant on this screen since graph scale is always logarithmic. We don't see any particular harm in leaving it around since it labels the scale, but it should be `phetioReadOnly: true`.

**Comment by pixelzoom** [comment]
`graphScaleProperty` is now created only when we have both scales.  So it does not exist in the _My Solutions_ screen. 

@arouinfar please review in master.

**Comment by arouinfar** [comment]
👍
