### ISSUE TITLE
make drag handler appear as a child of GraphIndicatorNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#131]
From https://github.com/phetsims/ph-scale/issues/117#issuecomment-593706368:

- [ ] In the tree, the drag handlers of the GraphIndicatorNodes are siblings of the GraphIndicatorNode. For example:
`mySolutionsScreen.view.graphNode.logarithmicGraphNode.indicatorH3ODragHandler` and
`mySolutionsScreen.view.graphNode.logarithmicGraphNode.indicatorH3ONode`
We think it would be more intuitive for clients if the drag handler could be moved under the corresponding GraphIndicatorNode, but we aren't sure if it's doable/reasonable.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please review in master.

Here's how `phScale.mySolutionScreen.view.graphNode.logarithmicGraphNode ` looks in Studio:

<img width="219" alt="screenshot_162" src="https://user-images.githubusercontent.com/3046552/75733051-74fe2180-5cb1-11ea-87d0-3b7a3ca3a747.png">

**Comment by arouinfar** [comment]
Looks great, thanks @pixelzoom!
