### ISSUE TITLE
disable "auto fill" while state is being restored

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#132]
From #127:

> There is an additional quirk with the auto fill feature. If `autoFillEnabledProperty` is true when launched, the dropper will slowly fill the beaker to 0.50 L (as opposed to usual autoFill speed). If `autoFillEnabledProperty` is false when launched, the beaker will be empty.

**Comment by pixelzoom** [comment]
It really doesn't matter how fast the autoFill is.  When state is restored, there should be no autoFill.  Otherwise it would clear the solution and fill the beaker with 0.5L of solute. 

@arouinfar do you agree?

**Comment by pixelzoom** [comment]
This issue requires knowing when state is being restored, then skipping the autofill.

I created phetsims/phet-io#1624 to come up with a general solution, assigned to the PhET-iO team. This issue is blocked until that is addressed.

**Comment by pixelzoom** [comment]
I verified that adding this `settingState` flag in MacroModel does the job.  But we need something cleaner for general use.

```js
  /**
   * Starts the auto-fill animation.
   * @private
   */
  startAutoFill() {
    const settingState = _.hasIn( window, 'phet.phetIo.phetioEngine' ) &&
                         phet.phetIo.phetioEngine.phetioStateEngine.isSettingState;
    if ( this.autoFillEnabledProperty.value && this.autoFillVolume > 0 && !settingState ) {
      this.isAutoFillingProperty.value = true;
      this.dropper.dispensingProperty.set( true );
      this.dropper.flowRateProperty.set( 0.75 ); // faster than standard flow rate
    }
  }
```

**Comment by arouinfar** [comment]
> It really doesn't matter how fast the autoFill is. When state is restored, autoFill should be disabled.

Agreed @pixelzoom.

**Comment by pixelzoom** [comment]
Over in phetsims/phet-io#1624,  `phet.joist.sim.isSettingPhetioStateProperty` was added to determine whether PhetioEngine is setting state. I'll proceed with that.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please verify in master.  Run the sim with `?autoFill=true` (the default for ph-scale), make some changes in Studio, press "Launch", and verify that the beaker is not autoFilled when the sim launches.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom
