### ISSUE TITLE
why do graph indicators look disabled when values are zero?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#136]
This occurred to me while working on another issue. When the beaker is empty in the Macro screen, the graph indicators show '0'. This is correct and makes sense for both mol/L and mol.  But they also look disabled:

<img width="1041" alt="screenshot_172" src="https://user-images.githubusercontent.com/3046552/76149930-172b5a00-6062-11ea-9c72-d6068230a59e.png">

Imo, this looks bad aesthetically.  And more importantly, it doesn't make sense to disable them because they are never interactive and their values are still relevant and correct.  When they are interactive in the _My Solution_ screen, they will never be zero, because the beaker can never be empty.

@arouinfar would it be OK to make them look enabled when they have '0' values, like this?:

<img width="1039" alt="screenshot_173" src="https://user-images.githubusercontent.com/3046552/76149962-72f5e300-6062-11ea-97b2-6f4fc043b7b0.png">

**Comment by pixelzoom** [comment]
Note to self, relevant code is in GraphIndicatorNode.js:

```js
      // disabled when value is zero
      const isEnabled = ( value !== 0 );
      this.opacity = isEnabled ? 1.0 : 0.5;
      this.cursor = ( isEnabled && options.isInteractive ) ? 'pointer' : 'default';
```

**Comment by arouinfar** [comment]
@pixelzoom I think the reason they look disabled is because the concentration is technically undefined (dividing by zero), though quantity being zero is not problematic.  Would it be possible to display an emdash like we normally do for null/noValue? The position of the indicators could stay at the bottom of the graph.

Either way, I think we could make the GraphIndicatorNodes look enabled when the value is zero/null.

**Comment by pixelzoom** [comment]
@arouinfar It's not currently possible to display an emdash.  These indicators use SCENERY_PHET/ScientificNotationNode, which requires a number.  I'll investigate what's required to make them support `null`. 

I did make the indicators look enabled when the value is zero.

**Comment by pixelzoom** [comment]
Good news - ScientificNotationNode does support `null`.  The documentation was out of date.

**Comment by pixelzoom** [comment]
When the beaker is empty, graph indicators now display embash for concentration, 0 for quantity. 

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks great in master, thanks @pixelzoom.
