### ISSUE TITLE
instrumentation of microScreen.model.pHMeter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#137]
Something I noticed while working on another issue...

Instrumentation of the pH meter mode in _Macro_ screen looks like this:

```
-phScale
  -microScreen
    -model
      -pHMeter
        valueProperty
        -probe
          positionProperty
```

There are a few problems here:

* `valueProperty` is never updated, always `null`
* this meter doesn't have a separate movable probe, so both `probe` and `positionProperty` are irrelevant 
* it's created in the model, but not actually used in the view

Like the _My Solutions_ screen, there's no need for `microScreen.model.pHMeter`  -- it has no moving parts, and its pH is always the same as the solutions.   So it should be removed.

**Comment by pixelzoom** [comment]
Sorry, I was wrong here.  The Macro screen does have a movable probe.  The only change I'm going to make is to rename `valueProperty` to `pHProperty`, and that will be done in #138.  So closing.

**Comment by pixelzoom** [comment]
`microScreen.model.pHMeter` has been removed.  @arouinfar please review in master, let me know if you have any questions about this.

**Comment by arouinfar** [comment]
That all sounds reasonable to me @pixelzoom, and it looks good in master.
