### ISSUE TITLE
link pHMeterNode to associated pHProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#138]
... to make pHProperty easier to locate in Studio.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/sun/issues/575#issuecomment-596643759, we are discussing adding a Property linked element to NumberSpinner, and @arouinfar said:

> I'd generally agree, but it seems less clear-cut for pH Scale. There's already a link to pHProperty in the pHMeterNode which contains the spinner. Would you move the linked property down into the spinner, or would you add a 2nd linked property?

<img src="https://user-images.githubusercontent.com/8419308/76236208-f3971980-61f1-11ea-9752-2330b006cf4c.png" width=200>

**Comment by pixelzoom** [comment]
@arouinfar in the above commit, I've added a link to `pHProperty` only if `pHMeterNode` doesn't have a spinner.   The downside is a lack of consistency -- the `pHMeterNode` in _Macro_ and _Micro_ screens have a link , the one in _My Solutions_ does not.  See Studio trees below.

phScale.mySolutionScreen.view.pHMeterNode:

<img width="208" alt="screenshot_174" src="https://user-images.githubusercontent.com/3046552/76240004-1c221200-61f8-11ea-91dd-4be28c62879c.png">

phScale.microScreen.view.pHMeterNode:

<img width="238" alt="screenshot_175" src="https://user-images.githubusercontent.com/3046552/76240219-7a4ef500-61f8-11ea-9334-875843094028.png">

phScale.mySolutionScreen.view.pHMeterNode:

<img width="233" alt="screenshot_176" src="https://user-images.githubusercontent.com/3046552/76240278-9357a600-61f8-11ea-9a3b-d0fc9a0352d2.png">

**Comment by pixelzoom** [comment]
@arouinfar over to you for review.  The trade-off is consistency vs duplication for `phScale.mySolutionScreen.view.pHMeterNode`.  Let me know your preference, I don't have a strong feeling here.

**Comment by arouinfar** [comment]
> To avoid the duplication that you pointed out, I've added a link to pHProperty only if pHMeterNode doesn't have a spinner. The downside is a lack of consistency -- the Macro and Micro screens have a link at pHMeterNode.pHProperty, the My Solutions screen does not. See Studio trees below.

I think the duplication of having *pHProperty under `view.pHMeterNode` and *property under `view.pHMeterNode.spinner` (both pointing back to `model.solution.pHProperty`) would be confusing to clients.  I prefer the general pattern of including a link to the associated property within the common component, in this case, `NumberSpinner`. 

@pixelzoom I think tree in master is looking good, but I want to double check with @kathy-phet before closing.

**Comment by arouinfar** [comment]
Reviewed with @kathy-phet, and we decided that this tree structure is fine for now. We may revisit the duplicated `*pHProperty` if it becomes a client request.
