### ISSUE TITLE
Make enabledProperty read only for increment/decrement buttons

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/ph-scale#139]
@arouinfar and I noticed that for the MySolutions screen, the enabledProperty of pH increment and decrement buttons are controlled by the sim, so those should be made "read only" and "not featured" in the studio tree. 

Can you do one or either of this in the code, or do we need to do that manually overrides? We are thinking overrides, because you would need to reach into button and that is not clean, but let us know.

It seems like most spinners take over control of enabledProperty, so perhaps this is a general spinner sun issue?

**Comment by pixelzoom** [comment]
This is a general issues with NumberSpinner that should be handled as part of its PhET-iO design, in https://github.com/phetsims/sun/issues/575.   If you want to override what is decided in that general design issue, then it would be done in Studio.   

Feel free to close this issue if that answers your question.

**Comment by pixelzoom** [comment]
I've moved this question to https://github.com/phetsims/sun/issues/575. Closing.
