### ISSUE TITLE
rename solution.volumeProperty to solution.totalVolumeProperty? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#140]
This occurred to me while working on #119.

@arouinfar do you think it would be useful to rename `solution.volumeProperty` to `solution.totalVolumeProperty`, since it's waterVolume + soluteVolume?  

For example, `phScale.macroScreen.model.solution`:

<img width="239" alt="screenshot_177" src="https://user-images.githubusercontent.com/3046552/76245417-796e9100-6201-11ea-8ba9-605c277176c2.png">

**Comment by arouinfar** [comment]
Good suggestion @pixelzoom. I think `totalVolumeProperty` would be a bit clearer. Please make this change.

**Comment by pixelzoom** [comment]
Done in the above commit.  Note that in order to reuse the model throughout the sim, it needs to be `totalVolumeProperty` in _My Solutions_, even though it's the only volume in that screen.

@arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.
