### ISSUE TITLE
dropper: disable dragging without disabling button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#141]
Reported by @kathy-phet in https://github.com/phetsims/ph-scale/issues/118#issuecomment-591745256:
> it is not currently possible to make it unmoveable/unpickable without also making the add liquid button unpickable/not working. 

This is dependent on completion of https://github.com/phetsims/scenery/issues/1041.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery/issues/1041#issuecomment-597689077, @kathy-phet said that this feature is not a prerequisite to delivering a dev version (due 3/30/2020).

**Comment by pixelzoom** [comment]
> ... only becomes blocking for the final release (date TBD) if identified by the client.

The client did not flag this issue in their feedback.  @arouinfar @kathy-phet is it still the case that this does NOT need to be addressed for 1.0 publication?

**Comment by kathy-phet** [comment]
I think for 1.0 published release we do not need to address this issue.

**Comment by pixelzoom** [comment]
Another way to address this issue would be to attach the DragListener to a subset of the dropper's scenegraph (excluding the button).  That would require changing the EyeDropperNode API, and probably changing its internal structure.  And then clients would have to use a non-standard way of adding a DragListener to an EyeDropperNode.

Imo, coming up with a way to disable scenery input listeners is still the better approach. Using pickableProperty will always have this general problem, and it's not a great way of disabling interaction, because it forces us to have a pickableProperty for every Node, regardless of whether it's interactive.

**Comment by pixelzoom** [comment]
This was addressed in https://github.com/phetsims/ph-scale/issues/215, closing.
