### ISSUE TITLE
instrument pHMeterNode.spinner.numberDisplay

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#142]
In _My Solution_ screen, the pH meter's NumberSpinner needs to have its NumberDisplay instrumented.   

The desired tandem hierarchy for `phScale.mySolutionScreen.view.pHMeterNode.spinner` is:

```
-spinner
  opacityProperty
  pickableProperty
  *property
  visibleProperty
 +decrementButton
 +incrementButton
 +numberDisplay
```

This is problematic because NumberSpinner does not currently use NumberDisplay.  So this issue is dependent on resolution of https://github.com/phetsims/sun/issues/575.

**Comment by pixelzoom** [comment]
According to @arouinfar in 3/12/20 status meeting, this is not a prerequisite for the first PhET-iO release.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/ph-scale/issues/144#issuecomment-601464949, when NumberSpinner has its NumberDisplay instrumented, this element should be marked as `phetioHighFrequency: true`:

`phScale.mySolutionScreen.view.pHMeterNode.spinner.numberDisplay.valueText.textProperty`

**Comment by pixelzoom** [comment]
Common-code work has been complete in https://github.com/phetsims/sun/issues/575.  

The Studio tree for `phScale.mySolutionScreen.view.pHMeterNode` now looks like this:

<img width="205" alt="screenshot_423" src="https://user-images.githubusercontent.com/3046552/86977974-03405380-c13b-11ea-88fb-52898c7aa3aa.png">

And `phScale.mySolutionScreen.view.pHMeterNode.spinner.numberDisplay.valueText.textProperty` has been set to `phetioHighFrequency: true` as requested.

@arouinfar please verify in master.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.
