### ISSUE TITLE
changes to number of decimals in model.solution.pHProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#143]
Related to @arouinfar and @kathy-phet review of the data stream in #117.

New requirements for `model.solution.pHProperty`:

- [x] In the _Macro_ and _Micro_ screens, we do not want pHProperty's value to be round to a multiple of 0.01 increments. We want the full-resolution value.

- [x] In the _My Solution_ screen, changes made to `pHProperty` using the pH Meter spinner should result in its value being a multiple of 0.01.   If the value was not a multiple of 0.01, round to that increment before adding 0.01.  If adding/subtracting 0.01 results in floating-point error (e.g 7.02 + 0.01 -> 7.029999999999999) then round the value after adding/subtracting.

**Comment by pixelzoom** [comment]
_Macro_ and _Micro_ screens have been changed as requested.

_My Solution_ screen is problematic.  NumberSpinner doesn't have an API that allow me to round the value that the spinner sets.  I tried to work around this by using an adapter Property. But I'd have to make bot the adapter Property and `pHProperty` reentrant, and we don't want that.  So looks like I'll have to modify NumberSpinner.

**Comment by pixelzoom** [comment]
_My Solution_ screen is now working as requested.   @arouinfar please review in master.

Work on NumberSpinner was done in https://github.com/phetsims/sun/issues/576.  No PhET-iO API changes were required.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I reviewed this with @kathy-phet and it looks good.
