### ISSUE TITLE
Elements that should be phetioHighFrequency: true

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#144]
For #117 

Reviewing the data stream, there are several elements which update frequently and should be marked as phetioHighFrequency: true.  

## Macro & Micro Screens
- [x] `model.drainFaucet.flowRateProperty`
- [x] `model.dropper.positionProperty`
- [x] `model.pHMeter.probe.positionProperty` (Macro only)
- [x] `model.solution.pHProperty` (All 3 screens)
- [x] `model.solution.soluteVolumeProperty`
- [x] `model.solution.totalVolumeProperty` (All 3 screens)
- [x] `model.solution.waterVolumeProperty`
- [x] `model.waterFaucet.flowRateProperty`
- [x] `view.pHMeterNode.pHIndicatorNode.numberDisplay.valueText.textProperty` (Micro screen tandem doesn't have pHIndicatorNode)

## Micro & My Solution Screens
- [x] `model.solution.concentration*Property`
- [x] `model.solution.numberOf*MoleculesProperty`
- [x] `model.solution.quantity*Property`
- [x] `view.ratioNode.ratioProperty`

**Comment by pixelzoom** [comment]
I was able to address all but one Property in the above commit.   

It is currently not possible set `phetioHighFrequency: true` for `view.pHMeterNode.pHIndicatorNode.numberDisplay.valueText.textProperty`.  `numberDisplay` is a `NumberDisplay` (common UI component), and `valueText` may be either `Text` or `RichText` (scenery Nodes).   `NumberDisplay` currently has no API for customizing the metadata of its subcomponents, so this will involve PhET-iO work in common-code.

**Comment by pixelzoom** [comment]
NumberDisplay work was done in https://github.com/phetsims/scenery-phet/issues/588. 

`numberDisplay.valueText.textProperty` is now `phetioHighFrequency: true`.

**Comment by pixelzoom** [comment]
@arouinfar all requested Properties have been instrumented, ready for review in master.

I do want to raise one red flag here -- this is a lot more `phetioHighFrequency: true` than I've ever been asked to add, and definitely more in the model than I've ever seen.  I understand that lots of things in the model change frequently in this sim.  But the majority of the model, including all 13 Properties related to Solution, is now `phetioHighFrequency: true`.  This seems both odd and counter to the advice I've received from the PhET-iO team for past sims that I've instrumented. I've been advised to use `phetioHighFrequency: true` primarily for input events, and not try to make the data stream "human readable".  I also don't see this much `phetioHighFrequency: true` in Beer's Law Lab, which very similar (adding solute to solution).  So I would encourage you to discuss this sim, and this particular issue, with the PhET-iO team.

**Comment by pixelzoom** [comment]
Slack phet-io channel:

Kathy Perkins:spiral_calendar_pad:  10:06 AM
pH Scale is a challenging one for the data stream - and I think will push our thinking about the data stream in general - but it is hard to know which way to go with this setting without having a client who is really agressively using this particular feature. It's mostly been the researchers so far.

We will review it Chris. Amy and I feel like the data stream will be a "first pass" for this sim, and will be allowed to be revisited and improved when we have a use case of use.

Chris Malley  11:02 AM
Understood.  I realize that the client will not be using the data stream.  But I think it's worth discussing (generally) so we have some consensus about how to use this feature, and some uniformity of application.
new messages

Amy Rouinfar:spiral_calendar_pad:  11:07 AM
Seems like this would be good to discuss in Thursday’s PhET-iO meeting.

Chris Malley  11:08 AM
I'll label https://github.com/phetsims/ph-scale/issues/144 for discussion.

**Comment by pixelzoom** [comment]
I've move the general topic of "best practices for phetioHighFrequency" to https://github.com/phetsims/phet-io/issues/1629.

@arouinfar if you want to review and close this issue, that would probably be fine.

**Comment by pixelzoom** [comment]
@arouinfar Since you asked that `view.pHMeterNode.pHIndicatorNode.numberDisplay.valueText.textProperty` should be high-frequency, should `phScale.microScreen.view.pHMeterNode.numberDisplay.valueText.textProperty` also be high-frequency?

**Comment by pixelzoom** [comment]
@arouinfar you requested:

> - [x] `view.pHMeterNode.pHIndicatorNode.numberDisplay.valueText.textProperty` (Micro screen tandem doesn't have pHIndicatorNode)

But the micro screen does have:

`phScale.microScreen.view.pHMeterNode.numberDisplay.valueText.textProperty`

... which is another NumberDisplay whose textProperty changes with pH.  Should it also be high-frequency?

**Comment by pixelzoom** [comment]
And when the `NumberSpinner` in _My Solution_ screen is changed to use `NumberDisplay` (see #142 and  phetsims/sun#575) then we will have:

`phScale.mySolutionScreen.view.pHMeterNode.spinner.numberDisplay.valueText.textProperty`

Should that also be high frequency?

**Comment by arouinfar** [comment]
> But the Micro screen does have:
>
>`phScale.microScreen.view.pHMeterNode.numberDisplay.valueText.textProperty`
>
>... which is another NumberDisplay whose textProperty changes with pH. Should it also be high-frequency?

Yes, please mark this as high frequency.

>And when the NumberSpinner in My Solution screen is changed to use NumberDisplay (see #142 and phetsims/sun#575) then we will have:
>
>`phScale.mySolutionScreen.view.pHMeterNode.spinner.numberDisplay.valueText.textProperty`
>
>Should that also be high frequency?

Yes, assuming the outcome of https://github.com/phetsims/phet-io/issues/1629 doesn't change our decisions around phetioHighFrequncy.

I reviewed the data stream with @kathy-phet, and these two properties should be marked as high frequency:
- [ ] `phScale.macroScreen.model.pHMeter.pHProperty`
- [ ] `phScale.microScreen.view.pHMeterNode.numberDisplay.valueText.textProperty`

**Comment by pixelzoom** [comment]
Done, back to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks good @pixelzoom!
