### ISSUE TITLE
identify featured elements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#146]
Feedback on initial PhET-iO instrumentation was completed in https://github.com/phetsims/ph-scale/issues/117, and all resulting GitHub issues have been either addressed or deferred.

The sim is now ready to identify featured elements using Studio.

**Comment by arouinfar** [comment]
@kathy-phet and I have reviewed the Macro Screen and most of the Micro Screen. We still need to review the graph on the Micro screen, as well as the My Solution screen. I've committed our progress so far.

Please note that the phetioFeatured metadata for ComboBox will be handled in https://github.com/phetsims/sun/issues/587.

**Comment by pixelzoom** [comment]
The features elements for the Macro screen will be the same in ph-scale-basics.  To save some time, I've copied the relevant overrides to ph-scale-basics-phetio-elements-overrides.js.   @arouinfar please review in master.

**Comment by arouinfar** [comment]
@pixelzoom ph-scale and ph-scale-basics are looking good. There is just one outstanding issue related to https://github.com/phetsims/sun/issues/587 (`comboBox.button.visibleProperty` should be phetioFeatured: false). Leaving this issue open and self-assigned until the ComboBox issue is resolved.

**Comment by pixelzoom** [comment]
I created a ph-scale issue for the `comboBox.button.visibleProperty` issue, see  https://github.com/phetsims/ph-scale/issues/163.  

OK to close this issue @arouinfar?
