### ISSUE TITLE
H3O molecule can be hard to see in blood option

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#148]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/487
Found in the published sim. This seemed to be the only combination that could cause issues. If this is determined to be not worth addressing, feel free to close.
On the Micro screen the red dot that represents the H3O molecules blends in with the color of the blood option, making them hard to see.

**Visuals**
![reddots](https://user-images.githubusercontent.com/41024075/77474931-96988780-6ddd-11ea-977a-2245f8b427c3.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html
Version: 1.4.0-dev.15 2020-03-23 21:08:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This is @arouinfar's call, so I'm going to unassigned myself.

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

@pixelzoom I need some clarification before I can make a decision. What colors are the dots in the beaker? They seem to change based on the contents, which makes me wonder if they are layered behind the beaker contents or if they have reduced opacity making their apparent color change. 

The GraphIndicatorNodes and the checkbox label for H3O+/OH- Ratio use different colors. The actual color of the dots in the beakers seems to depend on the contents. Compare undiluted Milk and Blood:
![image](https://user-images.githubusercontent.com/8419308/77483424-bb94f680-6ded-11ea-9ac8-a3c98164331e.png)

![image](https://user-images.githubusercontent.com/8419308/77483404-addf7100-6ded-11ea-8b41-dda8d30b95e3.png)

**Comment by pixelzoom** [comment]
Base colors are in PHScaleColors.js:

```js
  // base colors for molecules in 'ratio' view, alpha added later
  H3O_MOLECULES: new Color( 204, 0, 0 ),
  OH_MOLECULES: new Color( 0, 0, 255 )
```

Opacity (alpha) depends on whether the molecule is a majority or minority species.  In RatioNode.js:

```js
const MAJORITY_ALPHA = 0.55; // alpha of the majority species, [0-1], transparent-opaque
const MINORITY_ALPHA = 1.0; // alpha of the minority species, [0-1], transparent-opaque
```

**Comment by pixelzoom** [comment]
@arouinfar If you want to play around with making the molecules always be opaque, I could create a dev version, or you can edit RatioNode.js and change `MAJORITY_ALPHA` from 0.55 to 1.0, i.e.:

```diff
- const MAJORITY_ALPHA = 0.55; // alpha of the majority species, [0-1], transparent-opaque
+ const MAJORITY_ALPHA = 1.0; // alpha of the majority species, [0-1], transparent-opaque
```

I tried this and it looks a little severe to me.

**Comment by pixelzoom** [comment]
@arouinfar If you want to play around with making the molecules always be opaque, I could create a dev version, or you can edit RatioNode.js and change `MAJORITY_ALPHA` from 0.55 to 1.0, i.e.:

```diff
- const MAJORITY_ALPHA = 0.55; // alpha of the majority species, [0-1], transparent-opaque
+ const MAJORITY_ALPHA = 1.0; // alpha of the majority species, [0-1], transparent-opaque
```

I tried this and it looks a little severe to me.  It also doesn't really address the "H3O+ on Blood" problem.

`MAJORITY_ALPA = 0.55`:

<img width="458" alt="screenshot_209" src="https://user-images.githubusercontent.com/3046552/77563870-76250780-6e87-11ea-8d98-7d2ecd58fe83.png">

`MAJORITY_ALPA = 1.0`:

<img width="477" alt="screenshot_208" src="https://user-images.githubusercontent.com/3046552/77563877-79b88e80-6e87-11ea-9740-bf28acc2cade.png">

**Comment by pixelzoom** [comment]
@arouinfar I've added additional options to RatioNode.js that you might want to experiment with. They let you add an optional stroke around the H3O+ and/or OH- molecules:

```js
const H3O_STROKE = null; // optional stroke around H3O+ molecules
const H3O_LINE_WIDTH = 0.25; // width of stroke around H3O+ molecules, ignored if H3O_STROKE is null
const OH_STROKE = null; // optional stroke around OH- molecules
const OH_LINE_WIDTH = 0.25; // width of stroke around OH- molecules, ignored if OH_STROKE is null
```

For example, if I change `H3O_STROKE = 'black'`, then Blood and Milk look like this:

<img width="513" alt="screenshot_212" src="https://user-images.githubusercontent.com/3046552/77566094-cc477a00-6e8a-11ea-9b62-b446d69fea47.png">

<img width="528" alt="screenshot_211" src="https://user-images.githubusercontent.com/3046552/77566110-cf426a80-6e8a-11ea-83d8-408d961dd7d1.png">

**Comment by arouinfar** [comment]
@pixelzoom thank you so much for the explanation and screenshots. The information was really helpful.

I don't think changing alpha levels is the way to go, especially since there will be so much variability for different colored solutions. I like the 0.25 black stroke shown in https://github.com/phetsims/ph-scale/issues/148#issuecomment-603974146. Let's proceed with that change, applying it to both species.

**Comment by pixelzoom** [comment]
Both molecule species now have `stroke: 'black'` and `lineWidth: 0.25`.  @KatieWoe @arouinfar please review in master.  If it looks OK, the last person to review please close this issue.

**Comment by arouinfar** [comment]
Looks good to me @pixelzoom

**Comment by KatieWoe** [comment]
Looks good
