### ISSUE TITLE
Long strings overlap with molecule count boxes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#150]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/487. Found in the published version. Unlikely to impact any actual translations. Feel free to close.
When strings are long, the labels on the beakers can go behind the molecule count boxes.

**Visuals**
![overlaplong](https://user-images.githubusercontent.com/41024075/77484808-1aa83a80-6df1-11ea-834c-46168ecdc15b.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.15/phet/ph-scale_all_phet.html?stringTest=long
Version: 1.4.0-dev.15 2020-03-23 21:08:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Fixed in the above commit, see screenshot below.  @KatieWoe please verify in master, close this issue if it looks OK.

<img width="534" alt="screenshot_204" src="https://user-images.githubusercontent.com/3046552/77508013-48ac6f80-6e2f-11ea-9825-9534e324b700.png">

**Comment by KatieWoe** [comment]
Not sure if it's #149 or this, but rtl now throws an error and doesn't load:
![newrtlissue](https://user-images.githubusercontent.com/41024075/77551413-ef1c6300-6e77-11ea-88ea-b8d10bef5dab.png)
It does seem to load in the built version.

**Comment by KatieWoe** [comment]
Otherwise looks ok on master

**Comment by pixelzoom** [comment]
The `stringTest=rtl` error is not related to this issue. Moved to #151.

Closing.
