### ISSUE TITLE
stringTest=rtl fails

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#151]
In https://github.com/phetsims/ph-scale/issues/149#issuecomment-603893176 and https://github.com/phetsims/ph-scale/issues/150#issuecomment-603893619, @KatieWoe reported:

Not sure if it's https://github.com/phetsims/ph-scale/issues/150 or this, but rtl now throws an error and doesn't load:

![newrtlissue](https://user-images.githubusercontent.com/41024075/77551080-8503be00-6e77-11ea-9636-a9d3c4b1e991.png)

It does seem to load in the built version.

**Comment by pixelzoom** [comment]
This is a problem with PhET-iO instrumentation.  In SoluteComboBox.js:

```
      items.push( new ComboBoxItem( hBox, solute, {
        tandemName: _.camelCase( solute.name )
      } ) );
```

This is using the translated solute names to create tandems.  That's a general anti-pattern, because there are constraints on what chars may appear in a tandem name, and translated (or even English) strings may violate those constraints.   With `stringTest=rtl` those constraints are indeed violated, hence the "should match the regex pattern" error message.

**Comment by pixelzoom** [comment]
Fixed in the above commits. @KatieWoe please verify in master, feel free to close.

**Comment by KatieWoe** [comment]
Looks good on master
