### ISSUE TITLE
Spinner Buttons Do Not Allow For Full Range Control

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/ph-scale#152]
For https://github.com/phetsims/QA/issues/487 the spinner buttons on the "My Solution" screen do not allow for the full range of pH values to be reached. The maximum and minimum pH achievable is 15 and -1 respectively. This is achieved by sliding the H30 and OH graph indicators to their maximum positions. It would follow that the pH would be able to be set to a range of -1 to 15 using the spinner buttons on the pH reader, however the range of values that can be set by the buttons is -0.01 to 14.01. When the user tries to increase the pH above 14.01 or below -0.01 using the buttons the button is greyed out and not able to be interacted with. The disconnect between the maximum values achievable by the graph indicators and spinner buttons is a bit of a consistency issue, The first image shows the pH at the maximum of 15, while the second image shows the pH at 14.01 with the increase button greyed out.

(_@pixelzoom: edited the above to use correct UI terminology._)

![pH_Scale_Slider](https://user-images.githubusercontent.com/30352536/77576028-09ffcf00-6e9a-11ea-9578-a656ea16c7bd.JPG)

![pH_Scale_Buttons](https://user-images.githubusercontent.com/30352536/77575597-61ea0600-6e99-11ea-95f7-c92c54a85b20.JPG)

**Comment by KatieWoe** [comment]
Noting that this issue does not happen in the published version. Can also be seen when dragging the boxes by looking at the arrow buttons and when they grey out.

**Comment by pixelzoom** [comment]
@JRomero0613 @KatieWoe are you referring to the spinner buttons? There is no slider in this sim.

**Comment by pixelzoom** [comment]
Reading the description again and looking at the screen shot, the answer to my question is obviously "yes".   The UI component in the pH meter is a spinner, a standard UI component.  The things you drag on the graph have been referred to by the design team as graph indicators (but you'd have no way of knowing that).  I've changed the title of this issue and the description to use that terminology.  Let me know if I've misunderstood.

**Comment by pixelzoom** [comment]
This is a problem in NumberSpinner, introduced in https://github.com/phetsims/sun/issues/576.  Reopening that issue.

**Comment by pixelzoom** [comment]
Fixed in master. @JRomero0613 or @KatieWoe please review.  If it looks OK, please close.

**Comment by KatieWoe** [comment]
Looks good in master
