### ISSUE TITLE
update credits for 1.5.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#155]
Current credits are shown below.  @arouinfar @KatieWoe please let me know what you'd like to change.  

<img width="850" alt="screenshot_232" src="https://user-images.githubusercontent.com/3046552/77971578-47a29480-72ac-11ea-9ab0-9af7460d2d9d.png">

**Comment by arouinfar** [comment]
The convention for design credits has been to include the legacy lead/team.

@pixelzoom please...
- [ ] Add Archie Paulson to lead design
- [ ] Add Wendy Adams, Jack Barbera, and Laurie Langdon to the team

While ph-scale-basics does not have a Java version, it is essentially the  first screen of ph-scale, so I think it's appropriate to credit the legacy team there as well. I suspect the credits are already shared between the two sims (as was done in the Gas Props suite), but I wanted to be clear that I understand these changes will affect both sims.

**Comment by pixelzoom** [comment]
@arouinfar Yes, the same credits are shared by ph-scale and ph-scale-basics.

**Comment by pixelzoom** [comment]
@arouinfar FYI, here are the revised credits:

<img width="829" alt="screenshot_233" src="https://user-images.githubusercontent.com/3046552/77975932-bdacf880-72b8-11ea-942d-df8631c9d9bf.png">

**Comment by KatieWoe** [comment]
So far Logan Bray and Jacob Romero should be added to QA

**Comment by pixelzoom** [comment]
Updated QA credits are shown below. @KatieWoe I'll leave this assigned to you until the QA process is finished, in case we need to add additional names.

<img width="632" alt="screenshot_234" src="https://user-images.githubusercontent.com/3046552/78052895-fee6ec00-733c-11ea-9422-7b7155fa8bb6.png">

**Comment by pixelzoom** [comment]
@KatieWoe now that 1.4.0-rc.1 testing is completed, please indicate who you would like to add to the QA credits.

**Comment by KatieWoe** [comment]
Sorry about that. Everyone looks accounted for in https://github.com/phetsims/ph-scale/issues/155#issuecomment-606744897

**Comment by pixelzoom** [comment]
1.4 release branches have been abandoned, and the RC process will be restarted with a new release branch.  See https://github.com/phetsims/ph-scale/issues/166#issuecomment-681178035. 

Changing the title of this issue for 1.5 release.

**Comment by stemilymill** [comment]
Found during https://github.com/phetsims/qa/issues/669

My name is in the Team section instead of the QA section, and I think Brooklyn Lash and Clifford Hardin need to be added to QA as well @KatieWoe 

![name in wrong section of credits](https://user-images.githubusercontent.com/85511101/125675678-4e1f8aea-7ad5-4168-b161-4f36adf47183.jpg)

**Comment by KatieWoe** [comment]
Good catch

**Comment by pixelzoom** [comment]
QA credits updated, patched in 1.5 branches for ph-scale and ph-scale-basics. Example screenshot below, from master.  Ready for verification in next RC.

<img width="696" alt="screenshot_1063" src="https://user-images.githubusercontent.com/3046552/125719800-be8da7c2-a4aa-45bc-a5be-d88b06f556d2.png">

**Comment by pixelzoom** [comment]
Looks like I need to add @Nancy-Salpepi "Nancy Salpepi" to the QA credits in master and 1.5 branches. Self assigning.

**Comment by stemilymill** [comment]
@pixelzoom @KatieWoe  Devon Quispe has also worked on pH. I don't know if anyone else is missing

**Comment by pixelzoom** [comment]
Updated QA credits are shown below, added Nancy Salpepi and Devon Quispe in master and 1.5 branches.  Ready for verification in next RC.

<img width="666" alt="screenshot_1074" src="https://user-images.githubusercontent.com/3046552/126243674-557c77b7-0947-4ea9-810d-0263d3a3dfb7.png">

**Comment by KatieWoe** [comment]
This looks ok in rc.2
