### ISSUE TITLE
faucet 'tap' does not always dispense 0.05L

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#157]
ph-scale and ph-scale-basics suffer from the problem with FaucetNode that is described in https://github.com/phetsims/scenery-phet/issues/593.  

In PHScaleConstants.js, options to FaucetNode are specified. These are used for both the water and drain faucets. 

```js
  // faucets
  FAUCET_OPTIONS: {
    tapToDispenseAmount: 0.05, // L
    tapToDispenseInterval: 333, // ms
    shooterOptions: {
      touchAreaXDilation: 37,
      touchAreaYDilation: 60
    }
  },
```

These options would lead one to believe that tapping the faucet will dispense 0.05L over 333 ms.  That is not the case, since FaucetNode currently doesn't not support a way to dispense a precise amount. 

In https://github.com/phetsims/scenery-phet/issues/593#issuecomment-606374782, @arouinfar said:
> I do not think this needs to be addressed for ph-scale 1.4.0. Please transfer this issue to scenery-phet. Deferring also seems reasonable.

**Comment by pixelzoom** [comment]
@ariel-phet Since you closed https://github.com/phetsims/scenery-phet/issues/593 (and I support your decision in https://github.com/phetsims/scenery-phet/issues/593#issuecomment-610707415), can we also close this issue?

**Comment by ariel-phet** [comment]
Yes, we can close this issue.
