### ISSUE TITLE
ComboBox listbox does not resize when last item is made invisible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#162]
ph-scale and ph-scale basics have a problem with their Solute combobox, recently introduced in common code and described in https://github.com/phetsims/sun/issues/588.

@arouinfar is this a blocking issue for publication?

**Comment by pixelzoom** [comment]
If the combo selection is changed in either of the above 2 scenarios, then the listbox resizes to eliminate the gap where 'Water' was.

**Comment by arouinfar** [comment]
@pixelzoom I don't think this is blocking, given that the list box now resizes when the last option is removed. Not sure if you want to keep this open since there is still discussion going on in https://github.com/phetsims/sun/issues/588.

**Comment by pixelzoom** [comment]
I'm going to close this and trust that it will be handled in phetsims/sun#588.
