### ISSUE TITLE
comboBox.button.visibleProperty should be phetioFeatured: false

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#163]
phetsims/sun#587 (comboBox.button.visibleProperty should be phetioFeatured: false) is a pre-requisite to publishing a dev version for the client.

**Comment by pixelzoom** [comment]
Work was done in phetsims/sun#587, and I've confirmed that `comboBox.button.visibleProperty` is now `phetioFeatured: false`.  For example:

<img width="656" alt="screenshot_269" src="https://user-images.githubusercontent.com/3046552/79513185-7042c200-8000-11ea-8f1f-cb64ab11e993.png">

@arouinfar please verify, and feel free to close.

**Comment by arouinfar** [comment]
Looks good @pixelzoom!
