### ISSUE TITLE
publish PhET-iO dev versions for the client 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#164]
@kathy-phet would like to deliver PhET-iO dev versions of both ph-scale and ph-scale-basics to the client for review.
 
From status meeting, the process is:

1. @kathy-phet sign off on open issues labeled "status:blocks-publication"
2. @pixelzoom: publish dev versions, add links to this issue
3. @arouinfar: review and sign off
4. @kathy-phet: delivery to the client

**Comment by pixelzoom** [comment]
> 1. @kathy-phet sign off on open issues labeled "status:blocks-publication"

GitHub issues labeled "blocks-publication" as of Fri Apr 17 17:10:33 MDT 2020. A checked box indicates that the issue was identified as non-blocking for these dev versions.

- [x] phetsims/joist#627
- [x] phetsims/phet-io-wrappers#342
- [ ] phetsims/scenery#490
- [x] phetsims/studio#119
- [x] phetsims/studio#40
- [x] phetsims/studio#37
- [x] phetsims/studio#35
- [x] phetsims/studio#30
- [x] phetsims/studio#28
- [x] phetsims/studio#22
- [x] phetsims/studio#18
- [x] phetsims/studio#16
- [x] phetsims/studio#14
- [x] phetsims/sun#591

<details>
<summary>Slack discussion</summary> 

Summary of Slack message to @arouinfar @kathy-phet @ariel-phet @samreid @zepumph @chrisklus about the above issues

Amy Rouinfar  4:52 PM
The studio issues only block RC publication.

Amy Rouinfar  4:59 PM
I don’t see why sun 591 is blocking.
Chris Malley  4:59 PMhttps://github.com/phetsims/sun/issues/591 is blocking because it's parent issue was blocking, https://github.com/phetsims/sun/issues/588 (edited) 

Amy Rouinfar  5:01 PM
phetsims/phet-io-wrappers#342 shouldn’t block ph-scale. I commented in the ph-scale specific issue about this, see https://github.com/phetsims/ph-scale/issues/161#issuecomment-614308068

Michael Kauzmann  5:05 PM
Large systemic change to scenery that is unreviewed and after your dev test. . . Master is working, and the phet-io team + JO worked on some more of it today. I'm a bit worried about those being published. 490 has been in master for over a week and has not caused trouble though. So likely it is fine for a dev version review delivery.

Kathy Perkins  5:12 PM
Looks like #490 has led API changes that I would like to understand before delivering another dev version.

</details>

phetsims/scenery#490 has not been cleared as non-blocking. Assigned to @kathy-phet for followup.

**Comment by kathy-phet** [comment]
OK - We will pick this up next week.

**Comment by chrisklus** [comment]
From https://github.com/phetsims/scenery/issues/1046#issuecomment-616685891:

>`visibleProperty` is broken in Studio on master. Marking blocks-publication and adding to the list in https://github.com/phetsims/ph-scale/issues/164.

I'll start looking into the problem.

**Comment by samreid** [comment]
From the slack thread:

@samreid said:
> I don’t think #490 led to API changes in itself.  And our work in https://github.com/phetsims/scenery/issues/1046 was complex and systemic but did not change the API (if i recall correctly.)

**Comment by samreid** [comment]
In today's meeting, we agreed that code reviews are not blocking for https://github.com/phetsims/scenery/issues/1046 or https://github.com/phetsims/scenery/issues/490, and as long as they pass our internal QA dev test, it will be OK to share with the client.  But we will need to fix the visibleProperty issue identified in https://github.com/phetsims/scenery/issues/1046#issuecomment-616685891 first.

**Comment by chrisklus** [comment]
The `visibleProperty` problem from https://github.com/phetsims/scenery/issues/1046 is fixed. Checking off the blocks-publication list.

**Comment by pixelzoom** [comment]
Thanks @ariel-phet.  Self assigning, and I'll proceed with creating and testing dev versions.

**Comment by pixelzoom** [comment]
Here are links to the dev versions.

pH Scale:
https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-dev.3/phet-io/
https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-dev.3/phet/ph-scale-basics_en_phet.html

pH Scale: Basics:
https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.20/phet-io/
https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.20/phet/ph-scale_en_phet.html

From the Wrapper Index, I tested the links for Standalone, Studio, and State Wrapper. In Studio, I also tested the "Launch" feature. I did not see any problems. 

Over to @arouinfar for review and sign-off.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Everything looks good to me. 

@kathy-phet the sim is ready for delivery to the client. I've shared the links to the guide docs on Slack.

**Comment by kathy-phet** [comment]
Thanks! Dev version sent to client, closing!

**Comment by pixelzoom** [comment]
Great! Looking forward to getting feedback and moving on to RC.
