### ISSUE TITLE
titleText.visibleProperty gets reset when you switch screens

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/ph-scale#169]
<b>Test Device</b>

Desktop PC

<b>Operating System</b>

Windows 1909

<b>Browser</b>

Edge 84.0.522.40

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/514. In studio, if you set `general.view.navigationBar.titleText.visibleProperty` to false, then click the home screen button in the sim, `general.view.navigationBar.titleText.visibleProperty` is reset to true.

**Comment by samreid** [comment]
It seems 2 approaches to this problem are:

(a) Add another intermediate (uninstrumented `Node`) to the scene graph which has its visibility controlled by whether the home screen is showing.  This would retain the same tandem structure as we have had previously.
(b) Add a model Property like `sim.general.model.navigationBarTitleVisible` which would be used to control that visibility.

I don't recall which solution we have used previously, but I'm inclined to recommend (a) because it keeps the standard `visibleProperty` pattern for showing and hiding the title.

**Comment by pixelzoom** [comment]
I don't agree.  `naturalSelection.homeScreen.view.titleText` and `naturalSelection.general.view.navigationBar.titleText` are 2 different Nodes, and they look like they have their own `visibleProperty`.  If they share a visiblyProperty, then it should live in `general.model` and it should be clear visibility of both are controlled via the same Property.

**Comment by samreid** [comment]
I added an intermediate parent Node with this comment:

```js
  // Container node so that the visibility of the Navigation Bar title text can be controlled
  // independently by PhET-iO and whether the user is on the homescreen.
```

It is working well in my testing.  @muedli can you please test on master/phettest?  Also, it seemed straightforward but I think it warrants a code review.  @pixelzoom or @zepumph are you available for that part?  It is just a few lines of code.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/joist/commit/af85f2bdeca4ea01b03a11baec2c7c951afdc8fd reviewed, looks OK.

**Comment by pixelzoom** [comment]
phetsims/joist@af85f2b reviewed, looks OK.

I verified that this fixes the problem, so no need to be verified by QA.  To be regression tested in next RC.

**Comment by pixelzoom** [comment]
Looks like this needs to be patched into 1.4 branches of ph-scale and ph-scale-basics.  Self assigning.

**Comment by pixelzoom** [comment]
Cherry picked to joist branches ph-scale-1.4 and ph-scale-basics-1.4, and patched into 1.4 branches for ph-scale and ph-scale-basics.

**Comment by pixelzoom** [comment]
In duplicate https://github.com/phetsims/ph-scale/issues/176, @KatieWoe reported that this also occurs where switching between screens, not just when returning to the home screen.  I'll amend the issue title to reflect this.

**Comment by pixelzoom** [comment]
To verify this in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio
2. Go to a non-home screen.
3. Set general.view.navigationBar.titleText.visibleProperty to false, verify that title disappears from navigation bar.
4. Press the home screen button in the sim.
5. Verify that general.view.navigationBar.titleText.visibleProperty is still false

**Comment by KatieWoe** [comment]
Looks good on Win 10 Chrome in 1.5.0-dev.1
