### ISSUE TITLE
Switching to empty beaker disables water faucet

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#170]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/515 and https://github.com/phetsims/QA/issues/514.
This is mostly seen in pH Scale Basics, but can be reproduce in pH Scale by using the autoFill=false query parameter. If you switch to a solution, and the bucket does not fill, the add water faucet is greyed out until liquid is added. It is not greyed out if the bucket was drained, but had liquid in it, and it is not greyed out when the sim is first loaded. This does not occur in the published version.
**Steps to reproduce**
1. Go to the basics sim
2. Observe faucet
3. Switch to a new solution
4. Observe faucet.

**Visuals**
![greyhandle](https://user-images.githubusercontent.com/41024075/87834714-5a83a980-c848-11ea-968e-4b41cefbbf81.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: X
URL: https://phet-dev.colorado.edu/html/ph-scale-basics/1.4.0-rc.1/phet/ph-scale-basics_all_phet.html?stringTest=X
Version: 1.4.0-rc.1 2020-07-09 22:22:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Reproduced in 1.4.0-rc.1 and master.

**Comment by pixelzoom** [comment]
Fixed in master, ph-scale 1.4, and ph-scale-basics 1.4.  Tested both sims with `autoFill=true` and `autoFill=false`.  Ready for regression testing in next RC.

**Comment by pixelzoom** [comment]
To reproduce in ph-scale 1.4.0-rc.2:

1. Run the sim with `autofill=false`
2. Switch solutes using the combo box.
3. Verify that the water faucet does not become disabled.

**Comment by phet-steele** [comment]
Looks good in phetsims/QA/issues/533 and phetsims/QA/issues/535.
