### ISSUE TITLE
Studio search feature is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#172]
For phetsims/QA#514 and phetsims/QA#515.

See https://github.com/phetsims/studio/issues/171.

**Comment by pixelzoom** [comment]
Assigning to @arouinfar, because this is blocked until we get her feedback on https://github.com/phetsims/studio/issues/171.

**Comment by pixelzoom** [comment]
phetsims/studio#171 is resolved.  I ran into merge issues when cherry-picking https://github.com/phetsims/studio/commit/f847cd4763c7619f731a24a0ec281134f48aa0ef, in the list of commits in https://github.com/phetsims/studio/issues/171#issuecomment-666481584.   @zepumph and I resolved these problems by:

1. Replacing the body of Search `findMatches` with the new implementation, then changing 2 uses of singleton `studio` to `this.studio` and `Studio`. 
2. In Select.js, moving constant `screenPropertyID` to a local variable at use sites, so that unit tests would pass (necessary to commit.)
3. Run `git add .` and `git commit`, then proceed with cherry-picking.

**Comment by pixelzoom** [comment]
Ready for testing in next RC.

**Comment by pixelzoom** [comment]
This is not working correctly in master when "Featured" is selected.  Reopening phetsims/studio#171, blocking.

**Comment by pixelzoom** [comment]
Note to self:  When phetsims/studio#171 is fixed, cherry-pick to ph-scale 1.4 and ph-scale-basics 1.4.  Test in local builds.

**Comment by arouinfar** [comment]
See https://github.com/phetsims/studio/issues/175

**Comment by pixelzoom** [comment]
phetsims/studio#171 has been re-closed. The broken part of Search is now being tracked in phetsims/studio#175.

**Comment by pixelzoom** [comment]
Just a reminder that this is the sole issue blocking the next RC of ph-scale.  The delivery milestone for ph-scale is 9/1/2020, and we'll need at least 1 more RC cycle.  Turnaround for the first cycle was 25 days.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/studio/issues/175 is fixed and ready for cherry-pick to ph-scale 1.4 and ph-scale-basics 1.4.

In https://github.com/phetsims/studio/issues/175#issuecomment-673713352, @zepumph said:
>  ... here is the ordered list to cherry-pick for this issue:
https://github.com/phetsims/studio/commit/130ca7d42b1097670fb57a77359ca26fbdabe2b4
https://github.com/phetsims/studio/commit/7b291656e59297e06353b7bdb3a59c1fed3cc09e
https://github.com/phetsims/studio/commit/b6fd9136e5d17d003f347f3afc4cc894730dad65

https://github.com/phetsims/studio/commit/130ca7d42b1097670fb57a77359ca26fbdabe2b4 cherry-picked OK.

https://github.com/phetsims/studio/commit/7b291656e59297e06353b7bdb3a59c1fed3cc09e is causing merge conflicts in both Select.js and Studio.js.  No idea how to resolve these, because it looks like there have been other changes since shas were taken for ph-scale.  And I may have already picked Studio.js changes for #168.

https://github.com/phetsims/studio/commit/b6fd9136e5d17d003f347f3afc4cc894730dad65 cherry-pick hasn't been attempted yet. 

I'm going to need assistance from the iO team on this.

**Comment by pixelzoom** [comment]
@samreid @chrisklus and I spent ~45 minutes working on this via Zoom.  After cherry-picking phetsims/studio@130ca7d, we had to manually apply relevant changes from the remaining 2 shas, and you can see the result in https://github.com/phetsims/studio/commit/decf8af891e15c850bf61bfe189d1d8ddcf97491.

To test in ph-scale 1.4.0-rc.2 and ph-scale-basics 1.4.0-rc.2:

1. Run the sim in Studio
2. Verify that you can search for "listBox" with filtering set to "Featured" and "All".

**Comment by pixelzoom** [comment]
The cherry-picks that I picked up above apparently also include fixes for https://github.com/phetsims/studio/issues/168 (Studio clears tree selection when switching between "Featured" and "All" radio buttons).  So I've updated https://github.com/phetsims/ph-scale/issues/172#issuecomment-675023940 to include tests for that issue.

**Comment by brooklynlash** [comment]
Looks like this works on Chromebook.

**Comment by pixelzoom** [comment]
Thanks @brooklynlash.

@KatieWoe are you planning to test on other platforms, or can this be closed?

**Comment by KatieWoe** [comment]
Closing
