### ISSUE TITLE
PhET-iO Elements "All" needs to be selected to complete client requests

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#175]
For https://github.com/phetsims/QA/issues/514 and https://github.com/phetsims/QA/issues/515.
When looking at the client requests in https://github.com/phetsims/phet-io-client-guides/blob/master/ph-scale/client-requests.pdf, some of the requested element changes are in the "All" PhET-iO Elements section. Since they were specifically requested by the client, wouldn't it make sense for them to be available in the "Featured" section?
![allelementsneeded](https://user-images.githubusercontent.com/41024075/88106769-3cc58580-cb63-11ea-99c0-a09efed9b4d9.gif)

**Comment by pixelzoom** [comment]
In general, I don't think that an element related to a client request necessarily is required to be featured.  There may be some client requests that are very "tweaky", and that we don't want to have front-and-center for all Studio users.   But for this sim specifically, that's up to the sim designers.  I believe that @arouinfar and @kathy-phet carefully considered and reviewed awhich elements should be featured.

Assigning to @arouinfar.  Let me know if you want any changes. Also note that any changes that you make to overrides.js will need to be cherry-picked to the 1.4 branches of ph-scale and ph-scale-basics.

**Comment by kathy-phet** [comment]
I favor keeping it as is. In general, we don't want to encourage clients to change these aspects on the nav bar.

**Comment by arouinfar** [comment]
This is a good question @KatieWoe, and something that @muedli has also asked. I can understand the expectation that a client's request would be featured, but @pixelzoom summarizes it well. We make decisions about phetioFeatured that are more general. We think about what kinds of customizations clients may want to do generally, and what sorts of customizations could be used for a pedagogical purpose. 

Not everything a client wants to do will necessarily be featured, and not everything we feature will be something the client wants to customize. However, it's safe to say that most things a client would want to do are probably going to be featured. In reviewing the client requests, if you notice a customization that could be related to some particular learning goal and it seems weird that it's not featured, please check with a designer.

In this particular case, however, these are not elements that we want to feature.
