### ISSUE TITLE
Title text does not stay off when switching screens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#176]
For https://github.com/phetsims/QA/issues/514. Involves a request made in https://github.com/phetsims/phet-io-client-guides/blob/master/ph-scale/client-requests.pdf
When manipulating `phScale.general.view.navigationBar.titleText.visibleProperty` the setting made is not retained when you move to a new screen. If you turn it off on screen one, and then move to screen two it turns back on and stays on, even when going back to screen one. This means that it cannot be off if there is more than one accessible screen. I noticed that it is off by default on the home screen, and wonder if this contributes to the issue. 
![titletextdoesntstayoff](https://user-images.githubusercontent.com/41024075/88109018-068a0500-cb67-11ea-872e-f143b81f8139.gif)

**Comment by pixelzoom** [comment]
@KatieWoe This is a duplicate of https://github.com/phetsims/ph-scale/issues/169.  If you agree, please close this issue. If not, please explain how it's different. Thanks!

**Comment by KatieWoe** [comment]
Sorry about that. Closing
