### ISSUE TITLE
empty Solute list box causes the sim to crash

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#177]
For https://github.com/phetsims/QA/issues/514 and https://github.com/phetsims/QA/issues/515. Issue with studio.
If you remove the visibility of all of the options in the list box and then try to add one back can lead to the entire sim disappearing. The set up is a bit complicated, but it seems to occur if you have the list box closed when no option have visibility, try to open the box, then try to add the currently active option back to the list.

Steps:
1. Go to a screen with the list box (element `soluteComboBox.listBox`)
2. While list box is closed, set `visibleProperty` to false for all items in the list box
3. In the sim, try to open the list box
4. Try to add the currently-selected solute (probably water) back to the list by setting its `visibleProperty` to true
5. After this, trying to add any option back will cause the bug (the entire sim disappearing).
6. It seems the page must be refreshed to fix this bug.

![wholesimgoesaway](https://user-images.githubusercontent.com/41024075/88113534-2e7d6680-cb6f-11ea-9fd2-32d510234f18.gif)

**Comment by pixelzoom** [comment]
Reproduced in 1.4.0-rc.1.

The problem is that step 3 above results in a fatal error. 

In the built version for 1.4.0-rc.1, the console reports:

```
Error: <g> attribute transform: Expected number, "matrix(NaN,NaN,NaN,NaN,…".
```

For the unbuilt version in master, the console output is more illuminating:

```js
Uncaught Error: Assertion failed: scales should be finite
    at window.assertions.assertFunction (assert.js:22)
    at ComboBoxListBox.scale (Node.js:2109)
    at SoluteComboBox.scaleListBox (ComboBox.js:372)
    at ComboBox.js:250
    at TinyForwardingProperty.emit (TinyEmitter.js:69)
    at TinyForwardingProperty.notifyListeners (TinyForwardingProperty.js:120)
    at forwardingListener (TinyForwardingProperty.js:41)
    at TinyEmitter.emit (TinyEmitter.js:69)
    at BooleanProperty._notifyListeners (Property.js:273)
    at BooleanProperty.set (Property.js:171)
```

Since the list box has no contents, attempting to scale it fails.   I'm not sure what should be done to correct this. Should we ignore an attempt to popup the list box when the list is empty? And I'm concerned that there may be other related problems. Because we're allowing the client to put the ComboBox into a state (no items) that should be impossible.

@arouinfar thoughts?

**Comment by arouinfar** [comment]
We punted on two somewhat related ComboBox issues in https://github.com/phetsims/sun/issues/588 and https://github.com/phetsims/sun/issues/591. The customization is unrealistic and broke the sim, and there is probably precedent for this elsewhere in phet-io-land. It would be nice if there could be some solution that would prevent the sim from crashing, so let's check in with the PhET-iO team. I believe @zepumph is on deck for the pH Scale rc, but please feel free to reassign as necessary.

**Comment by pixelzoom** [comment]
>  ... It would be nice if there could be some solution that would prevent the sim from crashing, so let's check in with the PhET-iO team.  ...

ComboBox was not designed (or implemented) to accommodate an empty list, since an empty list makes no sense in practice. But since an empty list is now possible via PhET-iO,  I think that we need to modify ComboBox so that it does something other than crash when the list is empty.  My recommendation is to make the combo box button do nothing when the list is empty.

**Comment by pixelzoom** [comment]
Since this issue is not specific to ph-scale, I've opened a more general issue, https://github.com/phetsims/sun/issues/606. Let's continue the discussion there.

This issue is on hold until  https://github.com/phetsims/sun/issues/606 is resolved.

**Comment by pixelzoom** [comment]
phetsims/sun#606 has been resolved, and the fixes cherry-picked to the ph-scale and ph-scale 1.4 branches.   Ready for testing in the next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio
2. Go to `phScale.macroScreen.view.soluteComboBox.listBox` in the Studio tree
3. For all of the solutes under `listBox`, set their `visibleProperty` to false
4. Press the solute combo box in the Macro screen. Verify that it does nothing, and does not crash.
5. Set `phScale.macroScreen.view.soluteComboBox.listBox.water.visibleProperty` to true.
6.  Press the solute combo box in the Macro screen. Verify that it pops up the listbox, showing "Water" as the only choice.

**Comment by brooklynlash** [comment]
This works in Chromebook, no freezing and water shows up in the list box.

**Comment by pixelzoom** [comment]
Thanks @brooklynlash.

@KatieWoe are you planning to test on other platforms, or can this be closed?

**Comment by KatieWoe** [comment]
Closing
