### ISSUE TITLE
rename ?autoFill to ?autofill

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#179]
For phetsims/QA#515 & phetsims/QA#514

The `autoFill` query parameter is new for PhET-iO, see https://github.com/phetsims/ph-scale/issues/121.  

While working on https://github.com/phetsims/ph-scale/issues/178, I discovered that the correct spelling is "autofill", see https://en.wikipedia.org/wiki/Autofill.   

Should we change the spelling to "autofill" ?

**Comment by arouinfar** [comment]
@pixelzoom yes, let's use `autofill`. Let me know when the change has been made, and I'll propagate it to the client docs.

**Comment by pixelzoom** [comment]
Changed in master, patched into 1.4 branches for ph-scale and ph-scale basics. 

In addition to the query parameter, I also renamed occurrences in code (e.g. `autofillEnabledProperty`) and occurrences in overrides.js (e.g. featuring `phScale.microScreen.model.autofillEnabledProperty`).

Assigning to @arouinfar to propagate to client docs.  When that has been done, please unassign, and label this issue with "status:fixed-awaiting-deploy" so that it gets schedule for regression testing in the next RC.

**Comment by pixelzoom** [comment]
@arouinfar if there are changes to client docs that need to be patched into the 1.4 branches for ph-scale and ph-scale basics, let me know and I'll handle that.

**Comment by arouinfar** [comment]
Thanks, I've updated the client guides to use `autofill`. I'll go ahead and close this since #167 is the guide-specific issue.

**Comment by pixelzoom** [comment]
This needs to remain open until verified by QA in the next RC.  Labeled fixed-pending-deploy.

**Comment by arouinfar** [comment]
Sorry @pixelzoom, I should have read further back that your most recent comment 🤦

**Comment by pixelzoom** [comment]
No problem!

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2 for brand=phet:

1. Run the sim with `autofill=false` to verify that it turns off autofill.

To verify in ph-scale 1.4.0-rc.2 for brand=phet-io:

1. Run the sim in Studio
2. Search for "autofill"
3. Verify that all hits are "autofill" or "Autofill"

**Comment by brooklynlash** [comment]
For brand=phet on Chromebook, the autofill spellings are correct, but on default with no extra query parameter, ph-scale basics does not autofill and ph-scale does autofill. Is this a problem or intended?

**Comment by pixelzoom** [comment]
@brooklynlash Thanks for reporting. That's actually the desired behavior; ph-scale autofills, ph-scale-basics does not.   From ph-scale-basics-main.js:

```js
// If autofill query parameter was not in the URL, change the default.
if ( !QueryStringMachine.containsKey( 'autofill' ) ) {
  PHScaleQueryParameters.autofill = false;
}
```

Closing.
