### ISSUE TITLE
Faucet knobs don't have indicated pointer areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#180]
**Test device**
Jordan and Dell
**Operating System**
Mac 10.14 and Win 10
**Browser**
Safari and Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/514 and https://github.com/phetsims/QA/issues/515. Occurs in published.
The blue knobs for the water and drain faucets do not seem to be grabable all over. The location where it stops being grabable seems to on the lower half of the knob. It can be seen by when the mouse is an arrow and when it is a hand.

**Visuals**
![knobnotallthere](https://user-images.githubusercontent.com/41024075/88226816-e66f4a00-cc29-11ea-8dc6-176324ebca69.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.1/phet/ph-scale_all_phet.html?showPointerAreas
Version: 1.4.0-rc.1 2020-07-09 22:04:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
The faucet (FaucetNode) is a common-code UI component.  @KatieWoe can you reproduce this on other sims that have faucets?

**Comment by KatieWoe** [comment]
Looks like it does happen in other sims on master.

**Comment by pixelzoom** [comment]
Is the problem only with mouseArea (blue) or is it also a problem with touchArea (red)?

**Comment by KatieWoe** [comment]
Only seeing it with mouse, but then touch has snag to pick up, so it would be pretty hard to see it if it were an issue.

**Comment by pixelzoom** [comment]
This is a common-code problem, tracking in https://github.com/phetsims/scenery-phet/issues/614.

Labeling this issue as "on hold" until https://github.com/phetsims/scenery-phet/issues/614 is fixed.

**Comment by pixelzoom** [comment]
@KatieWoe if the touchArea were incorrect, then you wouldn't be able to snag in the bottom part of the touchArea.

**Comment by pixelzoom** [comment]
@KatieWoe it looks to me like touchArea is also broken.  Testing 1.4.0-rc.1 on iPad6, I can't snag in the bottom part of the touchArea.

**Comment by jonathanolson** [comment]
The cause seems to be this Scenery Image node, which is layered on top of the shooter:

![image](https://user-images.githubusercontent.com/480878/88312820-dc078b80-cccf-11ea-8367-b7cd7c2462bf.png)

**Comment by jonathanolson** [comment]
This is triggered by an inputListener on the FaucetNode specifically. I'd recommend just changing the visual stacking order, @pixelzoom is that possible?

**Comment by pixelzoom** [comment]
phetsims/scenery-phet#614 is resolved and the fix has been cherry-picked.

Ready for regression testing in next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim with `?showPointerAreas`
2. Verify that the mouseArea and touchArea work as expected for the faucets on the Macro screen (no need to do Micro screen)

**Comment by brooklynlash** [comment]
Works on Chromebook.

**Comment by pixelzoom** [comment]
Thanks @brooklynlash.

@KatieWoe are you planning to test on other platforms, or can this be closed?

**Comment by KatieWoe** [comment]
It didn't seem to be platform dependent, so I think it can be closed.
