### ISSUE TITLE
Tandem.REQUIRED is no longer checked 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#183]
Need a fix for https://github.com/phetsims/tandem/issues/192.

**Comment by pixelzoom** [comment]
A workaround was devised for phetsims/tandem#192., see https://github.com/phetsims/tandem/issues/192#issuecomment-663235438.   That workaround has been cherry-picked.  Ready for testing in the next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio with `?phetioValidation=true`
2. Verify that there are no console errors

**Comment by loganbraywork** [comment]
Seems to be working as intended on both Chrome and Firefox for windows
