### ISSUE TITLE
Long string is off center on home screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#184]
**Test device**
Dell and Dalton
**Operating System**
Win 10 and Mac 10.12
**Browser**
Chrome and Safari
**Problem description**
For https://github.com/phetsims/QA/issues/514. Not in published.
When strings are long, the title text on the home screen seems to be further to the left than center.

**Visuals**
![longoffcenter](https://user-images.githubusercontent.com/41024075/88338684-f05e7f00-ccf5-11ea-8df5-f373047651cd.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.1/phet/ph-scale_all_phet.html?stringTest=long
Version: 1.4.0-rc.1 2020-07-09 22:04:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This is not specific to pH Scale, it a general problem in joist.  @KatieWoe could you please create a joist issue, link it to this one, and assign it to someone with high priority?  Probably someone on the PhET-iO team, since I believe that this was introduced by adding the StringProperty for sim title.  (There's the cost of dynamic strings again.)

**Comment by KatieWoe** [comment]
Issue made above

**Comment by pixelzoom** [comment]
On hold pending resolution of phetsims/joist#645.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/joist/issues/645 is resolved and the fix has been cherry-picked to ph-scale and ph-scale-basics 1.4 branches.  Ready for testing in next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim with `?dev&stringTest=long`
2. Verify that the title is horizontally centered in the layoutBound on the home screen

**Comment by KatieWoe** [comment]
I think this is happening a bit, but less so, on https://github.com/phetsims/ph-scale/issues/184

**Comment by pixelzoom** [comment]
@KatieWoe if this is still a problem, please reopen phetsims/joist#645, label it as "block publication", and provide specifics/examples.

**Comment by pixelzoom** [comment]
This is still broken on some browsers, see https://github.com/phetsims/joist/issues/645#issuecomment-670650086.  On hold until https://github.com/phetsims/joist/issues/645 is resolved again.

**Comment by pixelzoom** [comment]
I don't think this needs to be fixed for pH Scale 1.4, since it generally looks fine and is only noticeable on Safari with an extremely long title.  So I'm closing this issue as "won't fix".   @arouinfar @ariel-phet if you disagree, please reopen.
