### ISSUE TITLE
Graphical Glitch when dragging dropper

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#185]
**Test device**
Dalton
**Operating System**
Mac 10.12
**Browser**
Safari 12
**Problem description**
For phetsims/QA#514. Is in published.
When dragging the dropper back in forth, there seems to be a graphical glitch where the part of the dropper and/or stream disappears on the leading edge. This goes away when the dragging stops and can be difficult to see. Wasn't able to reproduce on Win 10 Chrome, so it may be platform dependent, or it may be performance dependent. Easiest to see on the stream with a bright color such as hand soap. Likely doesn't need to be addressed.

**Visuals**
![ezgif com-optimize](https://user-images.githubusercontent.com/41024075/88344221-551ed700-cd00-11ea-8eb8-c25fc8235eeb.gif)

**Comment by pixelzoom** [comment]
This is one of those graphics things that just happens on some (usually older) platforms.  We might be able to address it by trying a different scenery renderer for the dropper and solute stream.   But I really don't think it's worth putting any effort into this, and recommend closing as "won't fix".

@arouinfar do you agree?

**Comment by arouinfar** [comment]
The glitch looks relatively minor to me, so closing as `wontfix` is fine by me.
