### ISSUE TITLE
3rd Screen Ratio dots do not show up on launched sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#187]
For https://github.com/phetsims/QA/issues/514. Seen on Win 10 Chrome, Firefox, and ChromeOS, so it seems to be independent of platform. 
On the third screen, if you have the ratio dots on in studio and launch or download html, then the launched sim will not show the dots. The checkbox will still be marked. If you change the pH or uncheck and recheck the box the dots will appear. This also does not seem to happen on the second screen.

![thirdscreenratio](https://user-images.githubusercontent.com/41024075/88567866-4e8caa00-cff5-11ea-8f5e-24918c0fd87d.gif)

**Comment by KatieWoe** [comment]
This also shows up in the state wrapper.

**Comment by pixelzoom** [comment]
Verified in Studio using the "Launch" button.  Not platform specific, occurs on all platforms.

It's odd that it's a problem only on the "My Solution" screen, and not on the "Micro" screen.  Their implementations of the ratio view are identical, see RatioNode.js.

To reproduce:

1. Start the sim in Studio via phetmarks
2. Go to the "My Solution" screen.
3. Check the "H3O+/OH- Ratio" check box.
4. Press the Launch button in Studio.
5. In the launched sim, note that the "H3O+/OH- Ratio" check box is checked, but the particles (dots) are not visible in the beaker.

**Comment by pixelzoom** [comment]
Usages of RatioNode look identical:

```js
// MicroScreenView.js
    const ratioNode = new RatioNode( model.beaker, model.solution, modelViewTransform, viewProperties.ratioVisibleProperty, {
      visible: viewProperties.ratioVisibleProperty.get(),
      tandem: tandem.createTandem( 'ratioNode' )
    } );

// MySolutionScreenView.js
    const ratioNode = new RatioNode( model.beaker, model.solution, modelViewTransform, viewProperties.ratioVisibleProperty, {
      visible: viewProperties.ratioVisibleProperty.get(),
      tandem: tandem.createTandem( 'ratioNode' )
    } );
```

**Comment by pixelzoom** [comment]
The difference in the above is the type of `model.solution`.  RatioNode documents it as `@param {MicroSolution|MySolution} solution` -- _MicroSolution_ for the Micro screen, MySolution for the _My Solution_ screen.

**Comment by pixelzoom** [comment]
This bug was introduced in the conversion of RatioNode `setVisible` to ES6.   You can see the problem in https://github.com/phetsims/ph-scale/commit/c28ca975f112104014c858c26d4c75082688d5ff.  No idea why it worked in one screen and not the other.

Fixed and cherry-picked in the above commits. Ready for testing in the next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio
2. Go to the Micro screen.
3. Check the "H3O+/OH- Ratio" check box
4. Press the "Launch" button in Studio
5. In the launched sim, verify that the "H3O+/OH- Ratio" check box is checked and the dots are visible.

**Comment by phet-steele** [comment]
This seems fixed on my Win 10 Chrome while testing phetsims/QA/issues/648.
