### ISSUE TITLE
Mirror wrapper may be unsynced during a slow load 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#188]
Linking to https://github.com/phetsims/phet-io-wrappers/issues/359, since it was created for this sim's RC test, phetsims/QA#514.

On hold until https://github.com/phetsims/phet-io-wrappers/issues/359 is addressed.

**Comment by pixelzoom** [comment]
@arouinfar please indicate whether this issue (and therefore phetsims/phet-io-wrappers#359) blocks publication.

**Comment by arouinfar** [comment]
I commented in https://github.com/phetsims/phet-io-wrappers/issues/359. It doesn't seem particularly blocking to me.

**Comment by pixelzoom** [comment]
phetsims/phet-io-wrappers#359 is resolved and has been cherry-picked.

Ready for testing in next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2, read the description in https://github.com/phetsims/phet-io-wrappers/issues/359.

**Comment by phet-steele** [comment]
I tested phetsims/QA/issues/648 with Win 10 Chrome and it worked out just fine. I throttled my CPU to make sure things loaded slowly, and I couldn't get the wrapper out of sync.
