### ISSUE TITLE
Set opacity doesn't show up in launched sim if item was disabled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#189]
For https://github.com/phetsims/QA/issues/514. Found on Win 10 Chrome and Mac 10.12 Chrome.
In studio, if you disable something the opacity of that thing may change. If you also change the opacity of that disabled object, then the launched/downloaded version of the sim will have the default disabled opacity rather than the opacity you set.

Steps:
1. Go to the second screen in Studio
2. Disable the Ratio checkbox with `phScale.microScreen.view.beakerControlPanel.ratioCheckbox.enabledProperty`
3. Observe new opacity
4. Change the ratio checkbox's opacity with `phScale.microScreen.view.beakerControlPanel.ratioCheckbox.opacityProperty` What you change it too doesn't really matter, as long as you can see the difference.
5. Launch the sim and observe the checkbox.

This does not seem to happen if the item was not disabled.
![setopacityitems](https://user-images.githubusercontent.com/41024075/88841539-5423f480-d19b-11ea-9b2b-f92b51733e48.gif)

**Comment by pixelzoom** [comment]
This is a general issue with all PhET Nodes and common-code UI components.  Setting `enabledProperty` adjusts opacity. If you try to adjust both, then your opacity changes will be overwritten when state is restored.   

Assigning to @arouinfar to decide how to proceed. If you'd like to address this generally, please create a scenery issue, identify whether it's blocking, and link to this issue.

**Comment by arouinfar** [comment]
This is not a blocking issue @pixelzoom, and the sim is behaving as expected. See https://github.com/phetsims/scenery/issues/1047 for a general discussion about (un)instrumenting `opacityProperty`.
