### ISSUE TITLE
Old search remains when reopening studio tab from history

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#191]
See https://github.com/phetsims/studio/issues/174.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/studio/issues/174 has been resolved and cherry-picked.

Ready for testing in next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale 1.4.0-rc.2:

1. Run the sim in Studio, using Chrome
2. Enter "listbox" in the search text field
3. Close the Studio tab in Chrome
4. Reopen the Studio tab in Chrome by choosing History > Recently Closed > Studio.
5. Verify that the search text field is empty

**Comment by brooklynlash** [comment]
The search bar tab is now empty on Chromebook, seems to be no problems.

**Comment by pixelzoom** [comment]
Thanks @brooklynlash.

@KatieWoe are you planning to test on other platforms, or can this be closed?

**Comment by KatieWoe** [comment]
Closing
