### ISSUE TITLE
X button on dialog may have too small pointer area

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#194]
Fix to be applied from https://github.com/phetsims/sun/issues/610.

See https://github.com/phetsims/sun/issues/610#issuecomment-671525020

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/issues/610#issuecomment-671525020 recommended cherry-picking https://github.com/phetsims/sun/commit/9c9f26324b8635536e8fcacb01f8c634afd5940b.  I ran into big merge conflicts. Since https://github.com/phetsims/sun/commit/9c9f26324b8635536e8fcacb01f8c634afd5940b only modified 2 lines of code, I ended up applying the changes manually. 

Ready for testing in next RC.

**Comment by pixelzoom** [comment]
To verify in ph-scale and ph-scale-basics 1.4.0-rc.2:

Open the About dialog and inspect the size of its 'X' close button.

**Comment by brooklynlash** [comment]
Touch area and mouse area are a good size on Chromebook.

**Comment by pixelzoom** [comment]
Thanks @brooklynlash.

@KatieWoe are you planning to test on other platforms, or can this be closed?

**Comment by KatieWoe** [comment]
Closed
