### ISSUE TITLE
Add "Item" suffix to Solute combo box items

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#195]
Over in https://github.com/phetsims/sun/issues/615, it was decided that elements in a group should still have a tandem name that indicates their type.   

In pH Scale, the combo box items under `soluteComboBox.listBox` should all have an "Item" suffix.  Doing this by concatenating "Item" onto the solute tandemName is OK.   

TODO list:

- [x] add "Item" suffix in SoluteComboBox.js
- [x] update any ids that appear in overrides.js
- [x] update ph-scale client guides
- [x] update ph-scale-basics client guides
- [x] cherry pick to ph-scale 1.4
- [x] cherry-pick to ph-scale-basics 1.4
- [x] cherry-pick common-code changes that enforce "Item" suffix

**Comment by pixelzoom** [comment]
@arouinfar please review the changes to the client guides for ph-scale and ph-scale-basics. They have been pushed to master, ph-scale 1.4, and ph-scale-basics 1.4.   If they look OK, you can unassign yourself and leave the issue assigned to me. Thanks.

**Comment by pixelzoom** [comment]
ComboBoxItem change is https://github.com/phetsims/sun/commit/187ac987c2939da26f9f5da2aa876bae14e346b9 and has been cherry-picked to ph-scale 1.4 and ph-scale-basics 1.4.

**Comment by pixelzoom** [comment]
Cherry-picked https://github.com/phetsims/sun/commit/55c4fc0ed7c427c46256138fc13a578512bcaad2, which improves the error message for the assertion in ComboBoxItem.

**Comment by pixelzoom** [comment]
To verify this for ph-scale 1.4.0-rc.2 and ph-scale-basics 1.4.0-rc.2:

1. Run the sim in Studio
2. Verify that all of the combo box items under `phScale.macroScreen.view.soluteComboBox.listBox` have a name that ends with "Item". E.g. "batteryAcidItem".
3. (ph-scale only) Verify that all of the combo box items under `phScale.microScreen.view.soluteComboBox.listBox` have a name that ends with "Item". E.g. "batteryAcidItem".

**Comment by arouinfar** [comment]
@pixelzoom the changes are all looking good in master. I reviewed the tree, client guides, and checked that relevant elements remained phetioFeatured.

**Comment by pixelzoom** [comment]
Ready for testing in next RC. 

To verify this for ph-scale 1.4.0-rc.2 and ph-scale-basics 1.4.0-rc.2:

Run the sim in Studio
Verify that all of the combo box items under phScale.macroScreen.view.soluteComboBox.listBox have a name that ends with "Item". E.g. "batteryAcidItem".
(ph-scale only) Verify that all of the combo box items under phScale.microScreen.view.soluteComboBox.listBox have a name that ends with "Item". E.g. "batteryAcidItem".

**Comment by KatieWoe** [comment]
Win 10 Chrome 1.5.0-dev.1 https://github.com/phetsims/ph-scale/issues/195#issuecomment-674403550 looks ok. Closing
