### ISSUE TITLE
PropertyStateHandler dependency registration leaks memory 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#200]
See phetsims/axon#328. This block publication of 1.4.  A full memory test (both brands) is required.

**Comment by zepumph** [comment]
A memory leak was outlined and fixed in master over in https://github.com/phetsims/axon/issues/328#issuecomment-681042541. It effects PhET brand. Please follow that link to cherry-pick changes into the next maintenance release of this sim.

**Comment by pixelzoom** [comment]
1.4 release branches have been abandoned, and the RC process will be restarted with a new release branch.  See https://github.com/phetsims/ph-scale/issues/166#issuecomment-681178035.  A complete new version of PhET-iO will be obtained from master and memory tested. So closing this issue.
