### ISSUE TITLE
ComboBox has bad interaction between enabledProperty and displayOnlyProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#204]
See https://github.com/phetsims/sun/issues/617.
 
@arouinfar please indicate whether this is blocking for ph-scale 1.4, and label this issue and https://github.com/phetsims/sun/issues/617 accordingly.

**Comment by pixelzoom** [comment]
1.4 release branches have been abandoned, and the RC process will be restarted with a new release branch. Seehttps://github.com/phetsims/ph-scale/issues/166#issuecomment-681178035. 

Unassigning, to be evaluated before the 1.5 branches are created.

**Comment by pixelzoom** [comment]
@arouinfar please indicate whether this is blocking for ph-scale 1.5, and label this issue and phetsims/sun#617 accordingly.

**Comment by arouinfar** [comment]
This does not block ph-scale 1.5. The buggy behavior is a result of unrealistic customizations, and the parent issue is deferred.

**Comment by pixelzoom** [comment]
Closing this issue.  It's a general issue that pertains to any PhET-iO sim that has a combo box, being tracked in phetsims/sun#617.  We've decided for a couple of releases that it's not blocking for this sim, and that's not going to change.
