### ISSUE TITLE
SoluteIO conversion to new IO Type pattern

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#205]
In 9317b6ba0ec4ecc51952fef71e003ff2afd5ae4d and 2a3de471a61d6c162bb821ce3b71c3fd9ecaa6ba for https://github.com/phetsims/tandem/issues/211, SoluteIO was changed to:

```js
const SoluteIO = new IOType( 'SoluteIO', {
  isValidValue: value => value instanceof Solute,
  supertype: ReferenceIO( IOType.ObjectIO ),
  toStateObject: solute => ( {
    phetioID: solute.tandem.phetioID,
    name: solute.name,
    pH: solute.pH
  } ),
  fromStateObject( stateObject ) {
    return ReferenceIO( IOType.ObjectIO ).fromStateObject( stateObject.phetioID );
  }
} );
```

This doesn't look correct.  Solute uses the same "static instance" pattern as Allele (in Natural Selection).  So I believe that SoluteIO should be:

```js
const SoluteIO = new IOType( 'SoluteIO', {
  valueType: Solute,
  supertype: ReferenceIO( IOType.ObjectIO )
} );
```

**Comment by pixelzoom** [comment]
I change SoluteIO in the above commit, and moved it into Solute.  Since there's no longer a circular reference, I was also able to move SoluteInstances into Solute.   Tested in Studio and State Wrapper.

@samreid please review.

**Comment by samreid** [comment]
I'll take a look, but please also see my comment in https://github.com/phetsims/beers-law-lab/issues/259#issuecomment-696160487

**Comment by samreid** [comment]
Looks good to me, thanks!  Closing.

**Comment by samreid** [comment]
On second thought, was it specifically requested that we put the "name" and "pH" in the state so they would appear in studio?  I'm not arguing that is the best plan (maybe the current commits would be better), I just want to understand why it was done this way.

**Comment by pixelzoom** [comment]
Ah right... We probably do want "name" and "pH" to appear in Studio.  Too bad we have to resort to this, because I can that being a common pattern for static instances.   So I should restore `toStateObject`.

But why is it then necessary to define `fromStateObject` as this?

```js
  fromStateObject( stateObject ) {
    return ReferenceIO( IOType.ObjectIO ).fromStateObject( stateObject.phetioID );
  }
```

Won't it be properly restored with ReferenceIO's default implementation of `fromStateObject`?

**Comment by pixelzoom** [comment]
It looks to me like ReferenceIO's default `fromStateObject` is identical to what you provided for SoluteIO.

ReferenceIO.js:
```js
      fromStateObject( stateObject ) {
        assert && assert( typeof stateObject === 'string', 'phetioID should be a string' );
        if ( phet.phetio.phetioEngine.hasPhetioObject( stateObject ) ) {
          return phet.phetio.phetioEngine.getPhetioObject( stateObject );
        }
        else {
          throw new CouldNotYetDeserializeError();
        }
      }
```

phetioEngine.js:
```js
  getPhetioObject( phetioID ) {
    assert && this.assertPhetioObjectFound( phetioID );
    return this.phetioObjectMap[ phetioID ];
  }
```

So for SoluteIO, can I just provide `toStateObject`, and use the default `fromStateObject`?

**Comment by pixelzoom** [comment]
I demonstrate that what I described above doesn't work, and now I understand why.  I also reverted to the original implementation of SoluteIO and documented why it's necessary to provide `toStateObject` and `fromStateObject`.

Here's the confusing thing about ReferenceIO.  `fromStateObject` has a param named `stateObject`.  It passes `stateObject` to 2 methods of phetioEngine:

```js
      fromStateObject( stateObject ) {
        assert && assert( typeof stateObject === 'string', 'phetioID should be a string' );
        if ( phet.phetio.phetioEngine.hasPhetioObject( stateObject ) ) {
          return phet.phetio.phetioEngine.getPhetioObject( stateObject );
```

Both of those methods of phetioEngine have parameter named `phetioID`.  Very confusing to me a stateObject is considered a phetioID.  Or maybe this is another case of incorrect/questionable parameter names in the API.   It sure made it more difficult to understand.  

Back to @samreid in case he wants to do anything about:
(1) the param names
(2) having to override toStateObject and fromStateObject for what is likely a common situation for static instances

Then feel free to close.

**Comment by samreid** [comment]
I renamed the parameter in the commit.  

> (2) having to override toStateObject and fromStateObject for what is likely a common situation for static instances

I wasn't sure what you meant by this.  Are you asking if we can provide library support to make this commonplace occurrence easier?  Also, it looks to me like `Solute.SoluteIO` shouldn't specify` supertype: ReferenceIO( IOType.ObjectIO ),` if it supplies its own toStateObject/fromStateObject

**Comment by pixelzoom** [comment]
> Are you asking if we can provide library support to make this commonplace occurrence easier? 

Yes. Not being able to use ReferenceIO for reference-type serialization in this case seems like a PhET-iO (or Studio?) design flaw.

> Also, it looks to me like Solute.SoluteIO shouldn't specify supertype: ReferenceIO( IOType.ObjectIO ), if it supplies its own toStateObject/fromStateObject

OK, changed in the above commit, tested in State wrapper.

**Comment by samreid** [comment]
I can't see a much better way to implement this, let's ask @zepumph.

**Comment by zepumph** [comment]
I tried hard to understand the whole scope of the discussion above, and I doubtless missed something, but I think I have an idea that will clean things up here.

We should make ReferenceIO's stateObject and object with a member called `phetioID`.

The ReferenceIO can be a better `interface` as opposed to forcing an API that is different from all other stateObjects (string).

Here is an untested patch. @samreid what do you think?

```diff
Index: ph-scale/js/common/model/Solute.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- ph-scale/js/common/model/Solute.js	(revision 5bef6a5380f1bafdda831faf5593eff76a6cfaa4)
+++ ph-scale/js/common/model/Solute.js	(date 1600730479126)
@@ -130,15 +130,12 @@
  * @public
  */
 Solute.SoluteIO = new IOType( 'SoluteIO', {
-  valueType: Solute,
+  valueType: ReferenceIO( IOType.ObjectIO ),
   toStateObject: solute => ( {
     phetioID: solute.tandem.phetioID,
     name: solute.name,
     pH: solute.pH
-  } ),
-  fromStateObject( stateObject ) {
-    return ReferenceIO( IOType.ObjectIO ).fromStateObject( stateObject.phetioID );
-  }
+  } )
 } );
 
 // Static instances
Index: tandem/js/types/ReferenceIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/ReferenceIO.js	(revision ed99942a75bb5afc71d79c640084d22c2b73c2ed)
+++ tandem/js/types/ReferenceIO.js	(date 1600730479129)
@@ -36,17 +36,22 @@
        * Return the json that ReferenceIO is wrapping.  This can be overridden by subclasses, or types can use ReferenceIO type
        * directly to use this implementation.
        */
-      toStateObject: phetioObject => phetioObject.tandem.phetioID,
+      toStateObject: phetioObject => {
+        return {
+          phetioID: phetioObject.tandem.phetioID
+        };
+      },
 
       /**
        * Decodes the object from a state, used in PhetioStateEngine.setState.  This can be overridden by subclasses, or types can
        * use ReferenceIO type directly to use this implementation.
-       * @param {string} phetioID - from toStateObject
+       * @param {{phetio:string}} stateObject - from toStateObject
        * @returns {PhetioObject}
        * @throws CouldNotYetDeserializeError
        * @public
        */
-      fromStateObject( phetioID ) {
+      fromStateObject( stateObject ) {
+        const phetioID = stateObject.phetioID;
         assert && assert( typeof phetioID === 'string', 'phetioID should be a string' );
         if ( phet.phetio.phetioEngine.hasPhetioObject( phetioID ) ) {
           return phet.phetio.phetioEngine.getPhetioObject( phetioID );

```

NOTE: you would need to change all usages of `ReferenceIO( .... ).toStateObject` to make sure it was an object with a `phetioID` field instead of the string itself.

**Comment by samreid** [comment]
That makes `SoluteIO` look very nice.  The state will be a bit more verbose like:

```js
sim.screen.tandem:'phetioid'
```

would become:

```js
sim.screen.tandem: {
   phetioID: 'phetioid'
}
```

But that is probably worth it.  I don't think conciseness in the state file is a primary concern.  Let's run this proposal past @pixelzoom for feedback.

**Comment by pixelzoom** [comment]
For `valueType` in my IO Type definition, I'm expecting to see the associated Core Type.  So `valueType: ReferenceIO( IOType.ObjectIO )` seems like a step in the wrong direction.   

Maybe the Core Type could have an (optional) method that converts it to what is shown for the "Initial value" in Studio?

**Comment by samreid** [comment]
Perhaps @zepumph meant `supertype` instead of `valueType`?

**Comment by zepumph** [comment]
yes yes `supertype` indeed, not valueType.

Verbosity in the state wrapper for references doesn't matter to me at all.

>I don't recall why we combined that with the toStateObject. Maybe it could default to toStateObject but you could opt in with a different optional method. I'll invite @zepumph back to discuss that aspect.

I think that it is right to have one channel (toStateObject) for both use cases (initial state/state object for setting). Really `stateObject` is just a serialized manifestation of the instance. We also already have a way to hide any part of the state that we don't want to see (nested under `private`). Furthermore, this seems like a feature that we are designing around a bad UI in studio (which only provides the "inital value"). 

@samreid there was another issue, perhaps about ComboBox layout, in which it would have been nice to get a notification when the state of an object would change. This feels like the same sort of problem, but I don't remember what the context was for the other conversation (so I can't find the issue). I wonder if it would be beneficial to have a `stateChangedEmitter` or something to opt into so that studio could know when to update the state view in the "instance panel".

**Comment by pixelzoom** [comment]
Serialization should be decouplable from how a value is displayed in Studio.  You shouldn't have to change serialization to change how something is displayed in Studio.

This accurately describes serialization, and gives us some default for how the value is displayed in Studio:

```js
const SoluteIO = new IOType( 'SoluteIO', {
  valueType: Solute,
  supertype: ReferenceIO( IOType.ObjectIO )
} );
```

If we don't like how the value is displayed in Studio, then we have to resort to changing serialization.  In this example, we have to handle the reference-type serialization ourselves. And this really isn't even a clear/accurate way of specifying what to show in Studio.  (I have no desire to show the phetioID in Studio, but I'm forced to because it's needed for serialization.)

```js
const SoluteIO = new IOType( 'SoluteIO', {
  isValidValue: value => value instanceof Solute,
  supertype: ReferenceIO( IOType.ObjectIO ),
  toStateObject: solute => ( {
    phetioID: solute.tandem.phetioID,
    name: solute.name,
    pH: solute.pH
  } ),
  fromStateObject( stateObject ) {
    return ReferenceIO( IOType.ObjectIO ).fromStateObject( stateObject.phetioID );
  }
} );
```

Something like this separates serialization for how the value is displayed in Studio:

```js
const SoluteIO = new IOType( 'SoluteIO', {
  valueType: Solute,
  supertype: ReferenceIO( IOType.ObjectIO ),
  toDisplay: solute => {
    name: solute.name,
    pH: solute.pH
  }
} );
```

**Comment by zepumph** [comment]
Instead of thinking about dividing on studio display and serialization, what about thinking about SoluteIO as a subtype of ReferenceIO. With work done in https://github.com/phetsims/tandem/issues/218, it is easy to add to the ReferenceIO functionality. @samreid please review, and then pass to @pixelzoom for a spot check.

**Comment by pixelzoom** [comment]
This issue stalled 27 days ago.  Self-assigning so that I can see what's need to get it resolved.

**Comment by pixelzoom** [comment]
Where we are at:

@samreid is assigned to review changes that @zepumph made to SolutionIO in c552c9d.

I would very much like to wrap this up, because this sim is on the deliverable list for the client, and is liable to become "needed" at any time.

**Comment by samreid** [comment]
The conversion to ReferenceIO looks great to me, over to @pixelzoom for a spot check.

**Comment by pixelzoom** [comment]
Looks good to me too. Closing.
