### ISSUE TITLE
replace ZoomButton with  MagnifyingGlassZoomButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#207]
Over in https://github.com/phetsims/scenery-phet/issues/652, ph-scale was identified as a sim that should be converted to use `MagnifyingGlassZoomButtonGroup`, a new common-code component.

**Comment by pixelzoom** [comment]
Done in the above commit.  Labeling this for testing during the next QA cycle.

**Comment by KatieWoe** [comment]
Looks ok on Win 10 Chrome on 1.5.0-dev.1. Closing
