### ISSUE TITLE
pH Scale 1.5 release (6/30/2021)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#209]
In July 2020, we set a goal of publishing pH Scale 1.4.0, the first production version with PhET-iO.  About a month later, we abandoned that effort (and the 1.4 branch) because there were too many PhET-iO changes. See https://github.com/phetsims/ph-scale/issues/166.

We'll try again in pH Scale 1.5, and this issue will track that release.  

From the note in the QA Pipeline:

pH Scale 1.5.0-rc.1

* 10/23/20 status update from KP:  
> pH Scale is now downgraded to "nice to have" but not urgent. I would keep that on hold for now until the new sims are through QA, unless there is a QA lull.
* new 1.5 branch
* brands=phet,phet-io
* full dev + RC QA process
* also includes ph-scale-basics

From 1/14/2021 PhET-iO meeting, milestones are to begin QA 4/1/21, publish 5/15/21.

1.5 will be a new release branch. It will require a full dev test, and full RC test.

FYI @arouinfar @kathy-phet

**Comment by pixelzoom** [comment]
A 4/8/21 Q2 planning meeting, dates were adjusted:

4/1/21 start
5/30/21 end

**Comment by pixelzoom** [comment]
Status:  There is 1 issue (#215) remaining for review before QA process could being. QA will be a full dev + RC process.  So 5/30/21 (3 weeks) is no longer a realistic publication date. Assigning to @kathy-phet and @arouinfar to establish new milestones.

**Comment by arouinfar** [comment]
@pixelzoom I'll take a look at #215, but https://github.com/phetsims/studio/issues/95 is still a blocking issue. It might be acceptable for a dev test (the behavior in master seems fine), but given the review comments, there will likely be code changes.

I cannot determine a new milestone, so leaving that up to @kathy-phet.

**Comment by pixelzoom** [comment]
@kathy-phet changed milestones to:

4/1/21 start
6/30/21 end

**Comment by pixelzoom** [comment]
We're now 1 week past the milestone. Assigning to @kathy-phet to revise.  Feel free to assign back to me when you're ready to proceed with publishing this release.

**Comment by pixelzoom** [comment]
Published for QA testing:
* pH Scale 1.5.0-dev.3, https://github.com/phetsims/qa/issues/665
* pH Scale: Basics 1.5.0-dev.1, https://github.com/phetsims/qa/issues/666

**Comment by pixelzoom** [comment]
RC tests published on 7/13/21, per @arouinfar:

* https://github.com/phetsims/qa/issues/669
* https://github.com/phetsims/qa/issues/670

**Comment by pixelzoom** [comment]
RC tests (spot-check) published on 7/23/21:
* https://github.com/phetsims/qa/issues/677
* https://github.com/phetsims/qa/issues/678

**Comment by pixelzoom** [comment]
RC test (spot-check) published on 7/26/2021:
* https://github.com/phetsims/qa/issues/679

**Comment by pixelzoom** [comment]
RC test (spot-check) published on 7/27/2021:
* https://github.com/phetsims/qa/issues/681

**Comment by pixelzoom** [comment]
https://github.com/phetsims/ph-scale/issues/232 was closed as "won't fix", so another RC is not necessary. Proceeding with production publication.

**Comment by pixelzoom** [comment]
pH Scale 1.5.0 was published on 7/27/21.  `grunt production --branch=1.5 --brands=phet,phet-io` prints some reminders:

> If this is a version that will be used with students, then make sure to remove the password protection. See https://github.com/phetsims/phet-io/blob/master/doc/phet-io-security.md for details.

N/A.

> Make sure that the current level of instrumentation is represented here in the Instrumentation Status Spreadsheet. On the spreadsheet, provide the version number like MAJOR.MINOR (without maintenance number) so that maintenance releases will seamlessly upgrade. Update both the text and the link
https://docs.google.com/spreadsheets/d/18_QNGuVtYtxOEKG9xRBs_PSQpyvzySF1Gk5puR-5Fv4/edit#gid=1881767354
And check that the link in the public-facing document has the correct text and link:
https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vReSXUUxC63CQCKHIoO6qY4ycWrqgw8eaX25io3_r2hRmO3RbXuyNRRMz5J2C1c5mCN9nxumvrv6snj/pubhtml?gid=2141068918&single=true

Done, added:
https://phet-io.colorado.edu/sims/ph-scale/1.5/wrappers/index
https://phet-io.colorado.edu/sims/ph-scale-basics/1.5/wrappers/index

> Make sure the sim is listed in perennial/data/phet-io-api-stable, if it has had a designed production release, and update the checked in API file to match the published version.

Verified that they are listed.

> If you are delivering this to a partner, update partners.md (phet-io/doc/partners.md) to show this delivery. Read the intro of the document to make sure that you format the entry correctly.

These sims are not in partners.md, and I don't know what to do here. Tracking in https://github.com/phetsims/phet-io/issues/1804, assigned to PhET-iO team.
