### ISSUE TITLE
CT: Assertion failed: Attached listeners should be cleared before pointer disposal

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#212]
I only see this once in CT.  But since CT hasn't been running all tests, I think I'll investigate.   It failed for ph-scale-basics, but that's a subset of ph-scale.

```
ph-scale-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/phet-io-wrappers/state/?sim=ph-scale-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22ph-scale-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1615727329507%22%2C%22timestamp%22%3A1615753336193%7D
Uncaught Error: Uncaught Error: Assertion failed: Attached listeners should be cleared before pointer disposal
Error: Assertion failed: Attached listeners should be cleared before pointer disposal
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/assert/js/assert.js:25:13)
at Touch.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/Pointer.js:427:15)
at Input.removePointer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/Input.js:960:13)
at Input.touchEndAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/Input.js:418:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/axon/js/Action.js:225:18)
at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/Input.js:1192:25)
at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/InputFuzzer.js:233:25)
at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/InputFuzzer.js:55:12)
at InputFuzzer.fuzzEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/scenery/js/input/InputFuzzer.js:105:7)
at Sim.fuzzInputEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1615727329507/joist/js/Sim.js:1084:24)
id: Bayes Chrome
Snapshot from 3/14/2021, 7:08:49 AM
```

**Comment by pixelzoom** [comment]
Reproduced very quickly by running in phetmarks with `
phet-io-wrappers/state/?sim=ph-scale-basics&phetioDebug&fuzz`.

And my suspicion about CT is correct. This isn't showing up regularly because this test is rarely being run:

<img width="1117" alt="screenshot_913" src="https://user-images.githubusercontent.com/3046552/111204138-72542e80-858b-11eb-80d5-b54d961ddec5.png">

**Comment by pixelzoom** [comment]
This same test is failing with the same assertion for color-vision. 

@jonathanolson has something changed in scenery?

**Comment by jonathanolson** [comment]
I'm working to reproduce this with additional changes to debug (it's being particularly tricky).

I'm not sure what broke this yet, because it's showing an inputListener existing AFTER release(). I promise I'm on it!

**Comment by jonathanolson** [comment]
Tt seems like phet-io is updating the main Scenery display synchronously on callbacks (e.g. restoring state?) on a button press.

It seems ill-advised to display-update DURING a normal press of a ResetAllButton, and it's incidentally triggering this (reset all (interrupts) => display update => validatePointers => enter event fired on change => RE-touch-snags item before disposal). Can we delay the Display update until another time, or is it truly needed synchronously?

@zepumph or @samreid, thoughts on how this could be avoided?

![image](https://user-images.githubusercontent.com/480878/111552945-00294880-8749-11eb-8eb8-cf8750a9f166.png)
Above are the stack traces for how this triggers a press() from WITHIN the release() callback (which, while it didn't error out, probably isn't a best practice).

**Comment by samreid** [comment]
`updateViews` does 2 things:

```js
currentScreen && currentScreen.view.step && currentScreen.view.step( 0 );

phet.joist.display.updateDisplay();
```

Even if we really do need to step the current screen view synchronously (which we may not), I don't know a reason why `updateDisplay` couldn't be asynchronous.  Maybe @zepumph can prove me wrong!

**Comment by pixelzoom** [comment]
This is also showing up in charges-and-fields, faradays-law, wave-on-a-strings,...

**Comment by samreid** [comment]
I'd like to check in with @zepumph before making changes here--@zepumph what do you recommend?

**Comment by zepumph** [comment]
This method was created and added to as we found that, in the state wrapper, updating state sometimes didn't show in the downstream sim. I don't think it has to be done sync. Good luck!

**Comment by jonathanolson** [comment]
@samreid would using something like animationFrameTimer or a legitimate `setTimeout(,0)` be best here?

**Comment by zepumph** [comment]
We have to be careful about using `animationFrameTimer `, and often state can be set on a sim where its `Sim.activeProperty` is false.

**Comment by samreid** [comment]
It seems we should run `currentScreen.view.step( 0 );` synchronously but `phet.joist.display.updateDisplay();` asynchronously, does that sound right to you?

**Comment by zepumph** [comment]
I believe so. Good luck!

**Comment by samreid** [comment]
I switched to use `setTimeout` for updateDisplay, and it seems to be working OK in testing.  @zepumph @pixelzoom or @jonathanolson can you please review?

**Comment by jonathanolson** [comment]
That looks good to me, but I'd like someone else to also review (since I recommended that approach).

**Comment by pixelzoom** [comment]
I have no familiarity with PhetioStateEngine or the cause of this problem, so I can't review the solution.  

I can report that, after a pull-all.sh, running with `phet-io-wrappers/state/?sim=ph-scale-basics&phetioDebug&fuzz` is NOT fuzz testing the State Wrapper.   So something is broken here, and this solution doesn't appear to be ready for review.

**Comment by pixelzoom** [comment]
After a clear cache, `phet-io-wrappers/state/?sim=ph-scale-basics&phetioDebug&fuzz` is now working.

**Comment by pixelzoom** [comment]
The reported problem no longer occurs after 5 mintues of fuzz testing with 
`phet-io-wrappers/state/?sim=ph-scale-basics&phetioDebug&fuzz`

**Comment by pixelzoom** [comment]
Changing label to "blocks-publication", since this is not specific to ph-scale and affects multiple sims.

**Comment by pixelzoom** [comment]
Should this issue be transferred to a more general repo, like phet-io?

**Comment by zepumph** [comment]
`setTimeout` feels like it could have bad side effects too. For example, what about reproduceable playbacks in a case where you are recording and you set the state of the simulation.

Could we use `stepTimer` instead?

**Comment by jonathanolson** [comment]
> Could we use stepTimer instead?

Presumably this needs to work when the simulation is NOT being stepped? Also was unsure about animationFrameTimer, as it would presumably have similar behavior to setTimeout.

**Comment by jonathanolson** [comment]
> For example, what about reproduceable playbacks in a case where you are recording and you set the state of the simulation.

Presumably setTimeout with 0 would be run next... which would fail in consistency if we step the simulation multiple times in a row (like what snapshot comparison does). Hmm, thoughts?

I'm also seeing animationFrameTimer stepped outside of animation frames (at the startup), but it seems like maybe that would be the most consistent? BUT would never happen if we're not actually firing animation frames for the sim.

**Comment by zepumph** [comment]
>I'm also seeing animationFrameTimer stepped outside of animation frames (at the startup)

I'm sorry. I got stepTimer and animationFrameTimer  mixed up. I think we should use animationFrameTimer. 


Doing this once on startup didn't seem buggy to @samreid  and I.

**Comment by samreid** [comment]
> I'm also seeing animationFrameTimer stepped outside of animation frames (at the startup), but it seems like maybe that would be the most consistent? BUT would never happen if we're not actually firing animation frames for the sim.

I think the `animationFrameTimer` is "always on", so it seems like it is our best bet.  I tested that out and it seemed OK in testing, so I'll commit.

**Comment by samreid** [comment]
Committed, @zepumph can you please spot check?

**Comment by zepumph** [comment]
This feels exactly like what `animationFrameTimer` was made for. @pixelzoom does this fix your error? Feel free to close.

**Comment by pixelzoom** [comment]
I have no idea whether  https://github.com/phetsims/phet-io/commit/65d1d3ccd39c73e9840668d1ecaa949462800166 fixed my error.  This error has not occurred in CT for many days.  It could have disappeared due to one of the other approaches that you tried, or something else entirely.  And I don't have an opinion on whether https://github.com/phetsims/phet-io/commit/65d1d3ccd39c73e9840668d1ecaa949462800166 is an appropriate solution.   

Closing.
