### ISSUE TITLE
pH Meter value text is not aligned properly on the initial set state

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ph-scale#218]
1. In the State wrapper (also happens in the Studio wrapper when previewing the sim), enter the Macro or Micro screens.
2. If you entered the Macro screen, you can already see in the lower sim that the readout on the pH meter has the incorrect alignment. Dragging the probe over the solution will display text like this:

![image](https://user-images.githubusercontent.com/5863899/118047742-722ca100-b338-11eb-9b95-e6a1300c8028.png)

3. If you entered the Micro screen, you will see this text start off incorrectly in the lower sim:

![image](https://user-images.githubusercontent.com/5863899/118047838-99836e00-b338-11eb-92ae-b5a807ee6e59.png)

Some notes!
- The issue is corrected once you swap to a different solute.
- The issue can easily return by pressing Reset All.
- I have not seen buggy behaviour on the My Solution screen. EDIT: Yea I do in Studio if I Preview a sim while the pH is negative.

Seen on Win 10 Chrome and FF. For phetsims/QA/issues/648.

**Comment by pixelzoom** [comment]
Thanks @phet-steele, I'll investigate.  Sounds like code that's changing the displayed value, but forgetting to center it in the meter.

**Comment by pixelzoom** [comment]
PHMeterNode.js is the place to start.

**Comment by pixelzoom** [comment]
Here's a full screenshot of the State wrapper, showing the downstream alignment problem for the pH meter in the Macro screen:

<img width="537" alt="screenshot_984" src="https://user-images.githubusercontent.com/3046552/118172897-26d2cb00-b3ea-11eb-9307-f3b4419f44f8.png">

It's also a problem with the pH meter in the Micro screen:

<img width="532" alt="screenshot_983" src="https://user-images.githubusercontent.com/3046552/118172979-41a53f80-b3ea-11eb-821c-7a3939f9778f.png">

I'm beginning to suspect a general problem with NumberDisplay.  These 2 meters were recently changed to use NumberDisplay in https://github.com/phetsims/ph-scale/issues/96.

**Comment by pixelzoom** [comment]
Definitely a problem with NumberDisplay.  I made these changes in NumberDisplay, so that I can see the background with a red stroke:

```diff
-      stroke: options.backgroundStroke,
-      lineWidth: options.backgroundLineWidth,
+      stroke: 'red',
+      lineWidth: 3,
```

Here's a screenshot, and the NumberDisplay's background is in the correct position. What is not correct is the alignment of the value on the background, which is the responsibility of NumberDisplay.

<img width="154" alt="screenshot_985" src="https://user-images.githubusercontent.com/3046552/118174025-8c738700-b3eb-11eb-93dc-5b39d2c90966.png">

**Comment by pixelzoom** [comment]
After moving the probe out of the solution, the "No value" (—) character is also misaligned in the downstream sim.  It is supposed to be `noValueAlign: 'center'`, but appears to be `noValueAlign: 'left'`.

<img width="529" alt="screenshot_986" src="https://user-images.githubusercontent.com/3046552/118175695-af069f80-b3ed-11eb-942c-e3fac4cd25a3.png">

**Comment by pixelzoom** [comment]
This is indeed a general problem with NumberDisplay.  Here's the problem:

```js
    const valueText = new Constructor( longestString, merge( {
      tandem: options.tandem.createTandem( 'valueText' )
    }, options.textOptions, {
      maxWidth: null // we are handling maxWidth manually, so we don't want to provide it initially.
    } ) );

// display the value
    const numberObserver = value => {
...
      const align = ( value === null ) ? options.noValueAlign : options.align;
...
      // horizontally align value in background
      if ( align === 'center' ) {
        valueText.centerX = backgroundNode.centerX;
      }
      else if ( align === 'left' ) {
        valueText.left = backgroundNode.left + options.xMargin;
      }
      else { // right
        valueText.right = backgroundNode.right - options.xMargin;
      }
      valueText.centerY = backgroundNode.centerY;
    };
    numberProperty.link( numberObserver );
```

`valueText` is fully instrumented, including its `textProperty`.  The State wrapper is restoring saving and restoring that `textProperty`.    But the alignment of `valueText` is handled in the `numberProperty` observer. 

This can be fixed by moving the alignment code into an observer of `valueText.boundsProperty`, and I'll do that.

**Comment by pixelzoom** [comment]
Fixed in the above commit, tested in State Wrapper.

@phet-steele please verify in master.  If it's OK, you can simply close this issue.  Since this problem was introduced recently by #96, it was never published in a production version.

**Comment by phet-steele** [comment]
This looks fixed in master my Win 10 Chrome.

**Comment by pixelzoom** [comment]
Thanks @phet-steele.
