### ISSUE TITLE
Autofill is slower in downstream sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#219]
For https://github.com/phetsims/QA/issues/650. Seen on Mac 11.4 Safari and Win 10 Chrome.
In the state wrapper (or presumably the studio wrapper) setting the state during an autofill will cause the downstream sim to autofill, but at a much slower pace than the auto fill should be. It fills to the same level however.

Steps:
1. Use a touch screen if possible, as this can require some fast timing.
2. Open the dropdown box and pick a new substance
3. Quickly set state while box is filling

![slowautofill](https://user-images.githubusercontent.com/41024075/119569376-e79e6580-bd6b-11eb-81e0-5e4711af00c9.gif)

**Comment by KatieWoe** [comment]
If you reset the sim, the autfill seems to be sped up.

https://user-images.githubusercontent.com/41024075/119724980-9f934780-be2c-11eb-84ba-6f61b31179bc.MP4

**Comment by pixelzoom** [comment]
This is being reported for https://phet-dev.colorado.edu/html/ph-scale/1.5.0-dev.2/phet-io.

@KatieWoe can you reproduce this in the previous release branch, in https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.2/phet-io/ ?

**Comment by KatieWoe** [comment]
It does seem to happen there. It is a bit harder to see since the setting of state happens at predetermined intervals there, and I can't seem to go fast enough to test the reset aspect I saw in https://github.com/phetsims/ph-scale/issues/219#issuecomment-849086865. But the slow autofill does seem to be happening.

**Comment by pixelzoom** [comment]
I suspect that this is related to https://github.com/phetsims/ph-scale/issues/132.  In that issue, changes were made so that autofill is disabled while state is being restored.   

In MacroModel.js:

```js
  startAutofill() {

    // This is short-circuited while PhET-iO state is being restored. Otherwise autofill would activate and change
    // the restored state. See https://github.com/phetsims/ph-scale/issues/132
    if ( this.autofillEnabledProperty.get() && this.autofillVolume > 0 && !phet.joist.sim.isSettingPhetioStateProperty.get() ) {
      this.isAutofillingProperty.set( true );
      this.dropper.isDispensingProperty.set( true );
      this.dropper.flowRateProperty.set( 0.75 ); // faster than standard flow rate
    }
    else {
      this.updateFaucetsAndDropper();
    }
  }
```

Note that the above typically accelerates `dropper.flowRateProperty` during autofill.  And that's not happening while state is being restored.   So perhaps this line can be moved before the `if then else`:

```js
 this.dropper.flowRateProperty.set( 0.75 );
```

Before I try this in master, I have another question @KatieWoe:  Can you reliably reproduce this in master?

**Comment by pixelzoom** [comment]
@KatieWoe I can't tell what you're doing in the movie that you provided in https://github.com/phetsims/ph-scale/issues/219#issuecomment-849086865.  I assume that you're pressing the Reset All button at some point during the slow autofilling.  Are your pressing the Reset All button in the upstream or downstream sim?

**Comment by KatieWoe** [comment]
Yes I can reliably reproduce in master. I am hitting the reset all button in the downstream (bottom) sim.

**Comment by pixelzoom** [comment]
I'm totally confused as to why ANY autofill is occurring. The change noted in https://github.com/phetsims/ph-scale/issues/219#issuecomment-849110147 is supposed to prevent autofill from being turned on while state is being restored. 

I'm going to have to punt this one over to the PhET-iO team. Assigning to @samreid.

**Comment by samreid** [comment]
It would probably be best to look at this together.  Some questions I have:

> I'm totally confused as to why ANY autofill is occurring.

Autofill is expected in the upstream sim, right?  `isAutofillingProperty` looks phet-io instrumented, so maybe that is being transmitted to the bottom sim.  Also, I didn't have a touch device at the moment, but was unable to reproduce the problem by setting the "Set State Rate" and changing the solution at the right time.  I'll reach out to @pixelzoom on slack.

**Comment by pixelzoom** [comment]
5/27/21 phet-io meeting:

@kathy-phet said that this has lower priority than general "blocks-publication" issues.  I'm going to wait to address this until pH Scale is on deck for publication.  I requested a 1-week notice for that.

**Comment by samreid** [comment]
@pixelzoom and I looked at this today, a guard around the nested property set seems to help:

```js
    // Toggle the flow rate when the dropper is turned on/off.
    this.isDispensingProperty.link( dispensing => {
      if ( !phet.joist.sim.isSettingPhetioStateProperty.get() ) {
        this.flowRateProperty.set( dispensing ? options.maxFlowRate : 0 );
      }
    } );
```

Also, a simplified startAutofill seems to work:

```js
  startAutofill() {
    this.isAutofillingProperty.set( true );
    this.dropper.isDispensingProperty.set( true );
    this.dropper.flowRateProperty.set( 0.75 ); // faster than standard flow rate
    this.updateFaucetsAndDropper();
  }
```

@pixelzoom volunteered to investigate further.

**Comment by pixelzoom** [comment]
The change to `startAutofill` in the above comment was not quite right, and introduced new problems. The correct change was to simply remove the `isSettingPhetioStateProperty` check, since it is moved to the `isDispensingProperty` listener.   See above commit.

@KatieWoe can you please test this in master? If it looks OK, please close this issue.

**Comment by KatieWoe** [comment]
It does look fixed on master
