### ISSUE TITLE
Metacog recording doesn't work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#220]
For https://github.com/phetsims/QA/issues/650. Win 10 Chrome.
When trying to use this https://phet-dev.colorado.edu/html/ph-scale/1.5.0-dev.2/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=5&promptText=Enter%20a%205%20Digit%20ID&publisher_id=5d4c8ae1}&key_name=testing&widget_id=ph-scale-1.5.0dev2-qaTest&metacog metacog link, the sim is blank with this console error.
<img width="952" alt="metacognotworking" src="https://user-images.githubusercontent.com/41024075/120037710-4a3b6f80-bfbf-11eb-8ad1-28184f1a0daf.png">

From @samreid on Slack:
>Metacog recently changed some of their infrastructure--they said sims wouldn’t be impacted.  I wonder if it is related?

Putting issue here, but feel free to move if needed.

**Comment by samreid** [comment]
@KatieWoe can you please run this test on a sim that it was known to work for in the past, to see if it is working or not?

**Comment by samreid** [comment]
@KatieWoe and found that a { sneaked into the URL.  Once we removed it, everything seemed OK.
