### ISSUE TITLE
Incorrect pointer areas for pH probe

### ISSUE THREAD

**Issue by stemilymill** [phetsims/ph-scale#222]
**Test device**
Dell laptop

**Operating System**
Win10

**Browser**
Chrome 91.0.4472.124

**Problem description**
For https://github.com/phetsims/qa/issues/666 , https://github.com/phetsims/qa/issues/665
**Does not impact performance**
When the probe is near the bottom of the container, the pointer area appears to rotate counterclockwise from the actual probe. The actual area for input does not change.
Occurs in pH Basics, regular pH scale Macro screen, and on published versions.

**Steps to reproduce**
Go to Macro screen of pH Scale or to pH Scale: Basics
Drag pH probe towards the bottom of the beaker, either above or below it.

**Visuals**
![show pointer areas probe moves weirdly1](https://user-images.githubusercontent.com/85511101/125352133-e4b4ff80-e32e-11eb-8615-ee7242def0c7.gif)

Pointer Area is not actual hitbox
![show pointer areas probe moves weirdly2](https://user-images.githubusercontent.com/85511101/125352141-e67ec300-e32e-11eb-95b2-9a51116261ac.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale: Basics‬
URL: https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.0-dev.1/phet/ph-scale-basics_all_phet.html?showPointerAreas
Version: 1.5.0-dev.1 2021-07-07 22:11:01 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
Nice find @stemilymill. Looks like https://github.com/phetsims/scenery-phet/issues/488 again @pixelzoom.

**Comment by pixelzoom** [comment]
This is a known problem with all sims that have a probe. The problem has been around for a couple of years, and has never been fixed -- https://github.com/phetsims/scenery-phet/issues/488 wasn't fixed, it was moved to https://github.com/phetsims/kite/issues/77.    On the bright side https://github.com/phetsims/kite/issues/77#issue-441455994, says that this is "a display-only problem", so the actual pointer area works correctly, it's the debug rendering of it that's incorrect.  

@arouinfar Unless you feel like this is the time to address this, please close this issue as "won't fix".

**Comment by arouinfar** [comment]
I don't see kite issue as particularly important since it's a display-only problem. However, this will likely continue to be reported by QA. I recommend we hide the pointerArea on the ProbeNode if it is using the default bounds, but I'll leave that up to @pixelzoom.

**Comment by pixelzoom** [comment]
I noted the recurring QA/dev cost in phetsims/kite#77.

I'll leave this issue open until  phetsims/kite#77 is addressed, in the hopes that QA won't report it again.

**Comment by samreid** [comment]
https://github.com/phetsims/kite/issues/77 has a proposed fix and is out for review.

**Comment by pixelzoom** [comment]
Self assigning. I'm going to wait until @jonathanolson has reviewed and closed https://github.com/phetsims/kite/issues/77 before I close this issue.

**Comment by samreid** [comment]
https://github.com/phetsims/kite/issues/77 has been reviewed and closed.
