### ISSUE TITLE
Update Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#228]
The Teacher Tips were last updated in 2015 and would likely benefit from review/revision. Note that this does not block the 1.5 release, as the updated tips cannot be uploaded until *after* publication.

TODOs:
- [x] Add a section for query parameters - `autofill`, `screens`, `supportsPanAndZoom`
  * autofill:  If true, the dropper will autofill the beaker to 0.50 L when switching solutes.
- [x] Document the precision issues discovered in #225

**Comment by pixelzoom** [comment]
@arouinfar The `showRatio` query parameter was reverted to private in #225, so you can skip that checklist item above.

**Comment by pixelzoom** [comment]
@arouinfar pH Scale 1.5.0 and pH Scale: Basics 1.5.0 have been published, so you can proceed with updating the Teacher Tips.

**Comment by arouinfar** [comment]
Updated tips for both sims have been uploaded to the PhET site, closing.
