### ISSUE TITLE
showRatio numbers are hard to read against a large number of ions

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#230]
For https://github.com/phetsims/qa/issues/679 in relation to https://github.com/phetsims/ph-scale/issues/229.
When testing the query parameter showRatio, I noticed that the number ratio was a black number on the beaker. When the ratio is large, and there are a large number of red or blue ions in the beaker, the black number can be hard to see.
![image](https://user-images.githubusercontent.com/41024075/127066369-662119a4-9fe3-457a-9dad-969b3b9cfb16.png)
![image](https://user-images.githubusercontent.com/41024075/127066384-5f4d5f60-de65-4d98-8f7f-99bc36b4bee7.png)

**Comment by pixelzoom** [comment]
Sorry for not coordinating with you on creation of this issue. Closing this as a duplicate, because it's a subset of #231.
