### ISSUE TITLE
pH Scale - Publish 1.6 with PhET-iO Upgrades

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/ph-scale#236]
As part of the "batch release" milestone https://github.com/orgs/phetsims/projects/44, publish _pH Scale_, for brands=phet,phet-io.

Ditto for _pH Scale: Basics_.  The 2 sims will be tested and published together.

**Comment by pixelzoom** [comment]
Unassigning until this becomes a priority.

**Comment by samreid** [comment]
I observed that ph-scale is next in the project board https://github.com/orgs/phetsims/projects/44, so I messaged on slack:

> anything I can to to help ph-scale phet-io?

After discussion, we concluded:

* #241 and #240 still needed work, but both of those have been addressed.

@pixelzoom said:

> I’m also not at all clear on the goals or timeline for pH Scale.  At this point, it’s very unlikely to be republished by the end of the year.

Anyways, GitHub project board notes don't show history, so we don't know how/when ph-scale was added there.  But if true, this is coming up for republication.

**Comment by pixelzoom** [comment]
12/14/2022...

@samreid said in a Slack DM:

> Hi @pixelzoom. @zepumph and I closed https://github.com/phetsims/phet-io/issues/1899 so I think you are all set to move forward with ph-scale.  Please let us know if you run into trouble

@kathy-phet said in Slack#phet-io:

> Kathy Perkins
@zepumph @samreid Has pH Scale been unblocked? Would be a good time to move it into QA queue.
> 
> Chris Malley
Yes, they notified me that it’s unblocked. I’ll get to it later today or tomorrow.
> 
> Kathy Perkins
Tomorrow is great. QA is finishing up RaP today. They have some more testing to finish up ESP, so will start Friday or Monday.

**Comment by pixelzoom** [comment]
12/15/2022 Begin dev testing for 1.6 release.

ph-scale:
* https://github.com/phetsims/qa/issues/866
* https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.6/

ph-scale-basics:
* https://github.com/phetsims/qa/issues/867
* https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-dev.1/

**Comment by pixelzoom** [comment]
12/23/2022 Begin RC testing for 1.6 release, `brands=phet,phet-io`.

ph-scale:
* https://github.com/phetsims/qa/issues/873
* https://phet-dev.colorado.edu/html/ph-scale/1.6.0-rc.1/

ph-scale-basics:
* https://github.com/phetsims/qa/issues/874
* https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/

**Comment by zepumph** [comment]
See https://github.com/phetsims/ph-scale/issues/280 for getting rc.2 ready

**Comment by pixelzoom** [comment]
@zepumph and team phettucine. This is the kind of comment I'm anticipating will be added when an RC is added to the QA Pipeline.

---

1/30/2022 RC spot-check begins for 1.6 release, `brands=phet,phet-io`.

ph-scale:
* https://github.com/phetsims/qa/issues/892
* https://phet-dev.colorado.edu/html/ph-scale/1.6.0-rc.2/

ph-scale-basics:
* https://github.com/phetsims/qa/issues/893
* https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.2/

**Comment by samreid** [comment]
RC testing completed.  @matthew-blackman and @arouinfar and I discussed, and agreed to cherry pick a change to documentation, and new credits.  We did this via 2 more RC's which looked good.  Then we published 1.6.0 Published.  We will do the same for ph-scale-basics after lunch.  @pixelzoom would you like to review or double check anything?  If not, this issue can be closed.

**Comment by pixelzoom** [comment]
Published PhET-iO versions:
* https://phet-io.colorado.edu/sims/ph-scale/1.6
* https://phet-io.colorado.edu/sims/ph-scale-basics/1.6

**Comment by pixelzoom** [comment]
👍🏻

**Comment by pixelzoom** [comment]
For anyone else who is keeping metrics... Elapsed time between for the QA process was 54 days.
