### ISSUE TITLE
Update QA credits for 1.6 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#237]
Update QA credits for 1.6 release.

Credits are shared with ph-scale-basics via `PHScaleConstants.CREDITS`.

**Comment by samreid** [comment]
@KatieWoe can you please advise what the QA credits would be for this sim, if it went into testing in the next several business days?

**Comment by pixelzoom** [comment]
@samreid QA credits are not revised before testing. They are revised during testing, and often revised after the final RC test. There's no need for @KatieWoe to answer this question yet, and I'll be tracking it as the sim moves through the QA process.

**Comment by pixelzoom** [comment]
@samreid QA credits are not revised _before_ testing, because there's no way to know for certian who will be involved. They are revised _during_ testing, and often after the final RC test, to reflect who actually worked on QA for the sim. So there's no need for @KatieWoe to answer this question yet, and I'll be tracking it as the sim moves through the QA process.

**Comment by samreid** [comment]
Good to know, thanks!

**Comment by samreid** [comment]
We got the credits from @Nancy-Salpepi, cherry picked into ph-scale and basics.  Checked in RC and double checked in published version.  Closing.
