### ISSUE TITLE
Migration rules for 1.6 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#240]
#239 (add support for dynamic locale) will certainly result in many API changes. According to the PhET-iO spreadsheet, this sim needs to provide migration support from 1.5 to 1.6. So migration rules will be needed.

Note that this also includes ph-scale-basics.

Previous versions, for generating *-custom-wrapper.html files:

* https://phet-io.colorado.edu/sims/ph-scale/1.5/
* https://phet-io.colorado.edu/sims/ph-scale-basics/1.5/

**Comment by samreid** [comment]
I'll reassign this when we get closer to that stage. Self-unassigning for now.

**Comment by samreid** [comment]
@pixelzoom said on slack:

> If pH Scale is indeed up next, the PhET-iO team might want to take a look at https://github.com/phetsims/ph-scale/issues/240 (Migration rules for 1.6 release). My understanding is that it’s a blocking issue, on-hold until PhET-iO design review is completed in https://github.com/phetsims/ph-scale/issues/241. (edited)

**Comment by arouinfar** [comment]
Design review has been completed in #241. As far as I'm aware, there's nothing blocking this issue.

**Comment by samreid** [comment]
I added migration rules for ph-scale and ph-scale-basics. @zepumph and I can review/discuss/improve the rules, but they seem equal to the quality of the rules approved for gravity and orbits, so this issue is no longer blocking an RC.

**Comment by pixelzoom** [comment]
My understanding is that part of this process is to familiarize developer with migration rules. @samreid Can you give me an overview of rules? -- specifically: how you identified them, how you implemented them, and how to review them.

**Comment by samreid** [comment]
Discussion with @pixelzoom and @zepumph:

How to deal with breaking changes in minor versions? Not possible at the moment.
How to factor out rules across sims?  Don't do it at the moment.
When you change an API file, it goes with a migration rule (or deleting a migration rule)

20 rules across sims in order


{
	myRule: rule,
	timestamp: dec 6, 2022
}



Assumption that migration versions are MAJOR.MINOR:
publish 1.5

publish 1.6.0
publish 1.6.1


publish 1.0
publish 1.1
1.2 is on master

client needs 1.0.1 with a breaking API change

enhancedSound => extraSound
extraSound => enhancedSound
enhancedSound => extraSound

identical to
enhancedSound => extraSound

###
Update: we would like to use MAJOR.MINOR.MAINTENANCE for the keys, and allow migration between maintenance versions.

**Comment by samreid** [comment]
@zepumph and I closed https://github.com/phetsims/phet-io/issues/1899#issuecomment-1341198162, so this issue is either ready to be closed, or ready for review by @pixelzoom.  @pixelzoom what do you recommend?

**Comment by pixelzoom** [comment]
I'm going to assume that this was rigorously tested by the developers who wrote the migration rules, and any remaining issues will be identified by QA.  So closing this issue.

**Comment by pixelzoom** [comment]
Reopening.  There's more work to be done here.

- [ ] Address general problems for https://github.com/phetsims/phet-io-sim-specific/issues/17

- [ ] Review https://github.com/phetsims/ph-scale/issues/260

Since a major feature of the 1.6 release is migration, I expect the *-migration-rules.ts files to be production quality.  That's not currently the case. After I cleaned up *-migration-rules.ts for  https://github.com/phetsims/ph-scale/issues/260, @samreid added some things that are not production quality.

- [ ] Remove dead code, like this:

```
   // new TandemFragmentRenamed( `${simName}.general.view.navigationBar.titleText.textProperty`, `${simName}.general.model.strings.${simName}.${simName}.titleStringProperty` ),
    new TandemFragmentRenamed( 'phScale.general.view.navigationBar.macroScreenButton.text.textProperty', 'phScale.general.model.strings.phScale.screen.macroStringProperty' ),
    // new TandemFragmentRenamed( `${simName}.general.view.navigationBar.microScreenButton.text.textProperty`, `${simName}.general.model.strings.${simName}.screen.microStringProperty` ),
    // new TandemFragmentRenamed( `${simName}.general.view.navigationBar.mySolutionScreenButton.text.textProperty`, `${simName}.general.model.strings.${simName}.screen.mySolutionStringProperty` ),
    // new TandemFragmentRenamed( `${simName}.modelScreen.view.playAreaNode.starPlanetSceneView.timeCounter.clearButton.textNode.textProperty`, `${simName}.general.model.strings.${simName}.clearStringProperty` ),
```

- [ ] Address this confusing comment. Either add a `TandemFragmentDelete` rule, or make the comment clear. 

```
    // 'phScale.macroScreen.view.pHMeterNode.pHIndicatorNode.numberDisplay.valueText.textProperty' no longer customizable
```

- [ ] Are we ordering this file by common rules at the top, followed by sim-specific rules?  If not, delete this comment:

```typescript
    //////////////////////////////////////////////////////
    // ph-scale specific rules
```

**Comment by samreid** [comment]
I'll take a look...

**Comment by matthew-blackman** [comment]
Update license.json file to remove reference to nonexistent image lightBulbMiddleHighIcon.png:
https://github.com/phetsims/circuit-construction-kit-common/commit/be56f00433c9114452db36503f8e9617111ea053

**Comment by pixelzoom** [comment]
@matthew-blackman how does https://github.com/phetsims/ph-scale/issues/240#issuecomment-1363228606 relate to this ph-scale issue?

**Comment by pixelzoom** [comment]
12/22/2022 phet-io meeting

@samreid addressed #260. 
Back to me to review the migration-rules.ts files.

**Comment by pixelzoom** [comment]
I reviewed ph-scale-migration-rules.ts and ph-scale-basics-migration-rules.ts.  Looks OK to proceed, and tested OK in 1.5 to master (1.6) migration.  Closing.

**Comment by pixelzoom** [comment]
I fixed the immediate problem in the above commit, so that there's no message when there are no errors. But there's more to be done here.

The 2 console.log calls are in this context:

```js
```
      assert && assert( !fail, 'MigrationRules renamed a phetioID to something not in new API.\n' + message );
      fail && console.log( fail, message );
...
      assert && assert( !fail, 'migration rules must handle all elements that converted to be LinkedElementIO.\n' + message );
      fail && console.log( fail, message );
```

When there are errors, I'm wondering if the console.log is necessary, since we'll likely be running with assertions enabled.  And if they are necessary, they console.log messages are certainly lacking information that's in the assertion messages --- they have no context about what aspect of migration failed.
 
Over to @samreid @zepumph to delete or improve the console.log calls.

**Comment by samreid** [comment]
It looks like that last comment was moved to https://github.com/phetsims/phet-io-wrappers/issues/479#issuecomment-1364460120, reclosing.

**Comment by pixelzoom** [comment]
@samreid https://github.com/phetsims/ph-scale/issues/240#issuecomment-1364459868 was originally made in the wrong issue. I'll delete that comment.
