### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#242]
Based on my experiences with adding dynamic-locale support to other sims, it's easier if the sim is in TypeScript.  For natural-selection (JavaScript), I did not convert to TypeScript, and it took ~2x as long as converting geometric-optics (a similar-size TypeScript sim). For molecule-polarity, I waited until I ran into problems to convert it to TypeScript, then the last (and most difficult) 20% went quickly.  So...

Since ph-scale is a relatively small sim (5910 lines), I'm going to convert it to TypeScript before I do more work on #239 (add support for dynamic locale).  I anticipate that this will make #239 easier/lower-cost, while getting TypeScript conversion for (almost) free.   And having the sim in TypeScript will certainly be a win for future maintenance.
 
@kathy-phet FYI.

**Comment by kathy-phet** [comment]
Sounds good!

**Comment by pixelzoom** [comment]
All files are converted to TypeScript.   

There are 24 type-related problems that need to be resolved. Search for `TODO https://github.com/phetsims/ph-scale/issues/242` in the code.

**Comment by pixelzoom** [comment]
There are 9 TODOs remaining. They are all related to the fact that pH (and concentration) can be `number | null`.  They are `null` when the beaker is empty.

**Comment by pixelzoom** [comment]
Done, closing.

**Comment by pixelzoom** [comment]
Thanks for the fix. A more complete fix is in the commit above -- the local variable and assertion are no longer needed, because `model.pHMeter` is now `pHMeter: MacroPHMeter` instead of `pHMeter: MacroPHMeter | null`.

No idea why this didn't error in my local lint, or in git hooks. 

Closing.

**Comment by samreid** [comment]
I think ph-scale and basics need to be added to tsconfig/all, I'll self-assign to do that.

**Comment by pixelzoom** [comment]
This is news to me. What is "tsconfig/all"?  And when do I need to add a repo to it?

**Comment by pixelzoom** [comment]
Looks like you mean chipper/tsconfig/all/tsconfig.json.   I have not been adding anything to this file, because I didn't know it was a requirement.  Missing are: molecule-polarity, ph-scale, ph-scale-basics, beers-law-lab, concentration.

**Comment by samreid** [comment]
I added the missing remaining sims.  After changes in https://github.com/phetsims/chipper/issues/1324, the linter will tell us if it trying to lint any files that are not covered by the tsconfig, so that will help.  I think this issue can be closed.

**Comment by pixelzoom** [comment]
👍🏻
