### ISSUE TITLE
Horizontal separator in the control panel does not resize when locale is changed.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#244]
In https://github.com/phetsims/ph-scale/issues/239#issuecomment-1242464933, @arouinfar reported:

2.  `phScale.microScreen.view.beakerControlPanel.separator` does not change in size when the panel expands to accommodate long strings. Not sure if this is something that can be handled within the scope of dynamic layout, but wanted to point it out in case this behavior is unexpected or can be corrected. (Feel free to veto if overly complicated.)
     <img width="239" alt="image" src="https://user-images.githubusercontent.com/8419308/189440604-659e2e8c-6482-4f0c-a0d6-7401811b3c3a.png">

**Comment by pixelzoom** [comment]
Resizing of the separator was address in the above commit.  

Because of https://github.com/phetsims/scenery/issues/1448, "separator" is now "divider", and that changes the PhET-iO API. This is the 3rd API that I've to change because of this today, and there are more on the way.  I don't think it's an improvement.  @kathy-phet FYI.

@arouinfar please review the behavior and API changes.  The revised phetioIDs are:

```
phScale.microScreen.view.beakerControlPanel.divider
phScale.microScreen.view.beakerControlPanel.divider.visibleProperty
phScale.mySolutionScreen.view.beakerControlPanel.divider
phScale.mySolutionScreen.view.beakerControlPanel.divider.visibleProperty
```

**Comment by arouinfar** [comment]
The dynamic layout issue has been addressed, and I don't see any technical issues with the new phetioIDs. However, we should make a decision about terminology in https://github.com/phetsims/scenery/issues/1448 before closing this out.

<img width="210" alt="image" src="https://user-images.githubusercontent.com/8419308/189713575-b2011f83-f968-4fca-a831-5bf9f8070864.png">

**Comment by pixelzoom** [comment]
"Separator" terminology was restored in https://github.com/phetsims/scenery/issues/1448, and "separator" tandem names were restored in the above commit.  

@arouinfar please review, close if OK.  You can verify for searching for "divider" and "separator" in Studio.

**Comment by pixelzoom** [comment]
"Separator" terminology was restored in https://github.com/phetsims/scenery/issues/1448, and "separator" tandem names were restored in the above commit.  

@arouinfar please review, close if OK.  You can verify for searching for "divider" and "separator" in Studio.

**Comment by arouinfar** [comment]
Looks good, thanks!
