### ISSUE TITLE
Title on pH meter in Macro screen does not remain centered.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#245]
In https://github.com/phetsims/ph-scale/issues/239#issuecomment-1242464933, @arouinfar reported:

1.  `pHStringProperty` - the text does not remain centered and escapes the bounds of the pH Meter.
     <img width="154" alt="image" src="https://user-images.githubusercontent.com/8419308/189437763-12bf300b-919e-4cff-8f66-2efa2fbd1438.png">

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good.
