### ISSUE TITLE
Add Solute link to nameProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#246]
Related to https://github.com/phetsims/ph-scale/issues/243 ...

We removed `name` from SoluteIO because name is now dynamic, a Property, and as @samreid said in https://github.com/phetsims/ph-scale/issues/243#issuecomment-1242815159:
> Copying the current value of one instrumented property so it will show up in the state of another PhetioObject doesn't sound like a good idea to me.

So when  https://github.com/phetsims/axon/issues/414 has been addressed, I will link Solute to its `nameProperty`.

**Comment by pixelzoom** [comment]
Before I actually do this, since it will be an API change...  In https://github.com/phetsims/ph-scale/issues/243, recall that we removed 'name' for SoluteIO, because it's now dynamic.   Would you like each Solute's `nameProperty` linked back to its corresponding translated string Property?  

Here's how the the Studio tree currently looks.  The addition would be a `*nameProperty` link under each Solute.  For example, `batteryAcid.nameProperty` would like to `phScale.general.model.strings.phScale.choice.batteryAcidStringProperty`.

<img width="366" alt="screenshot_1866" src="https://user-images.githubusercontent.com/3046552/189942336-84e99a00-2fcc-4f1f-9a51-73c5397d2ba3.png">

**Comment by arouinfar** [comment]
Great question @pixelzoom. If I remember correctly, `global.model.solutes` previously contained the `nameProperty` for each solute. Now that solute names are now under `general.model.strings` it seems best to link back to the appropriate `stringProperty`. Please proceed @pixelzoom.

**Comment by pixelzoom** [comment]
Done in the above commit, for ph-scale and ph-scale-basics.  Screenshot below shows the ph-scale-basics Studio tree.

@arouinfar please review. Feel free to close.

<img width="245" alt="screenshot_1887" src="https://user-images.githubusercontent.com/3046552/192368910-d78800e5-8fa7-48a9-9192-025beea343d9.png">

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!
