### ISSUE TITLE
Why are Solute instances of phetioType ObjectIO?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#247]
We are passing `Solute.SoluteIO` in as a phetioType, so I would have thought that would be the phetioType. Discovered while investigating https://github.com/phetsims/ph-scale/issues/243.

SOLUTION:

Ahhh, because all solutes are static instances, and so is the IOType. We need to create the IOType before the other statics. Commit coming soon.

**Comment by zepumph** [comment]
@pixelzoom, this was my confusion over in (2) of https://github.com/phetsims/ph-scale/issues/243#issuecomment-1242549370. Note now how you can see the ph of the Solute in something like `phScale.global.model.solutes.blood` in studio as an "initial value". Please review.

**Comment by pixelzoom** [comment]
Thanks. Good to know that TS is just as stupid as JS when it comes to static definitions.  I'll need to apply this to other sims too.

**Comment by zepumph** [comment]
It is worth tagging @samreid just to make sure that he sees https://github.com/phetsims/ph-scale/commit/734e5ef5dec4f4acfccb298d1829930471a64485
