### ISSUE TITLE
Dropper does not need to be movable for alt input.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#252]
Related to #249 (support for alt input)...

@arouinfar and I discussed potential problems with the dropper.  

Being able to move the dropper is not significant to learning goals, but (during Java version design) was kept to make the sim more "fun".  That immediately caused problems with how to press the button and drag the dropper at the same time, which we did figure out how to do for mouse/touch.  Figuring that out for alt input would be a big lift, and (again) is not a necessary user interaction. 

Making the dropper movable also presents focus issues. Currently, the dropper gets focus, then the dropper button gets focus.  That seems odd, but maybe it's OK.  And it's complicated because the dopper is in common code, while the sim is responsible for making it movable.  In any case, this would require a full a11y design for the dropper.  That's something that we do not have time for right now, and it's moot if the dropper is not movable.

So... We decided that it's OK for the dropper to remain in a fixed location, and not be focusable.  I will remove the dropper's focusability, KeyboardDragListener, and revise the keyboard help.

**Comment by pixelzoom** [comment]
Before making changes, I published [1.6.0-dev.4](https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.4/phet/ph-scale_en_phet.html) with the original alt-input behavior of the dropper, where the dropper is movable via the keyboard.   

After making changes, I published [1.6.0-dev.5](https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.5/phet/ph-scale_en_phet.html) with the revisions described above -- where the dropper is NOT movable via the keyboard. 

@arouinfar please review. Reminder to review keyboard help. If this looks OK, feel free to close.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in dev.5, closing.
