### ISSUE TITLE
Dashed line absent from pH scale value in newest version

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale#262]
**Test device**
MacBook Air (m1 chip) and Dell

**Operating System**
macOS 13.0.1

**Browser**
chrome and FF

**Problem description**
For https://github.com/phetsims/qa/issues/866, on the Macro Screen I noticed that the dashed line extending from the value in the pH scale is no longer present. I see one in published and in version 1.5. Was this change intentional?

**Visuals**
<img width="503" alt="Screenshot 2022-12-20 at 9 37 01 AM" src="https://user-images.githubusercontent.com/87318828/208725418-dc75a0ad-cbd8-4a29-a879-aec61bda38f2.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪pH Scale‬
URL: https://phet-dev.colorado.edu/html/ph-scale/1.6.0-dev.6/phet/ph-scale_all_phet.html
Version: 1.6.0-dev.6 2022-12-15 16:50:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1463x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Good catch @Nancy-Salpepi! The rendering order was inadvertently changed while adding support for alternative (5aeb7b8c for https://github.com/phetsims/ph-scale/issues/249).  So the dashed line was now _behind_ the pH scale, and could not be seen.   Fixed in the above commit. Please verifying in master and close if it looks OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in master in pH Scale and in the Basics version. Closing!
