### ISSUE TITLE
Disabling Dropper dragListener in version 1.5 results in disabled Dropper Button in version 1.6

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale#263]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/866 and https://github.com/phetsims/qa/issues/867, in Studio version 1.5 if I set `view.dropperNode.dragListener.enabledProperty` to false --the dropper can't be moved from side to side, but the button still works and liquid can be dispensed. Loading this version into Studio 1.6, results in the dropper button being disabled as well.  I see there are changes to that portion of the tree, but wanted to make sure that was the intended outcome OR if in this case, it should have reverted to the default setting?

<img width="500" alt="Screenshot 2022-12-21 at 9 03 14 AM" src="https://user-images.githubusercontent.com/87318828/208926206-c2e3277d-d531-41fd-8cee-ad9ed54b50e5.png">

**Steps to reproduce**
In pH Scale:
1. In Studio version 1.5, select "all" for PhET-iO elements
2. On either the Macro or Micro screens, set `view.dropperNode.dragListener.enabledProperty` to false
3. Save version
4. Upload into Studio version 1.6
5. Try to dispense liquid

**Comment by pixelzoom** [comment]
What, another problem with dropper interactions? How suprising :)  

There's no pedagogical reason for making the dropper movable. We did it to make interacting with the dropper move "fun".  But it has caused nothing but problems (and continuing cost) in both the Java and HTML5 versions.   An incomplete list of problems includes:  How to keep the drag handler from swallowing button events, how to hold down the button while dragging the dropper, how to design alt input (we punted), ... now how to workaround PhET-iO problems.  

So before I incur yet-another cost related to this... Can we please revisit whether the dropper needs to be movable?  @arouinfar thoughts?

**Comment by pixelzoom** [comment]
Also note that in https://github.com/phetsims/ph-scale/issues/252 (alt input), we decided that moving the dropper via alt input is not necessary.  In PHDropperNode.ts:

```
    // NOTE: Moving the dropper via the keyboard is not necessary.
    // See https://github.com/phetsims/ph-scale/issues/252
```

If it's not necessary for keyboard, then it's presumably not necessary for mouse & touch either.

**Comment by pixelzoom** [comment]
Investigating more, and rereading @Nancy-Salpepi's report:
> in Studio version 1.5 if I set view.dropperNode.dragListener.enabledProperty to false --the dropper can't be moved from side to side, but the button still works and liquid can be dispensed.

This sounds like a bad migration rule, and here's the bad rule:

```
    new TandemFragmentRenamed( 'dropperNode.dragListener.enabledProperty', 'dropperNode.inputEnabledProperty' ),
```

The original Property disabled the button's dragListener.  This rule maps that to disabling all input for the entire dropper, including the button.  This definitely needs to be addressed, regardless of whether the dropper remains movable. @samreid @zepumph FYI.

Also note that if we remove dragging from the dropper, that will one or more migration rules. So maybe we want to leave it as is.

**Comment by pixelzoom** [comment]
@arouinfar nevermind. We're keeping the dropper movable. I can't bear to deal with making it unmovable at this point in the release process.

In the above commits, I instrumented `dropperNode.dragListener.enabledProperty` (which appears in 2 places in the Studio tree), so that it matches the 1.5 API.    Then I deleted the bogus `TandemFragmentRenamed` rule from the migration-rules.ts files.

This is an excellent example of a couple of pitfalls:
(1) Rules may succeed but still totally break the sim.
(2) "Common" rules are not necessarily applicable to all situations, and should be individually considered, not bulk/blindy copy-pasted.
(3) Having developers who are not familiar with the sim write migration rules is liable to break the API in subtle ways.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi ready for review in master.  If it looks OK, please close.

To test:

* `dropperNode.dragListener.enabledProperty` should enabled/disable only dragging for the dropper
* `dropperNode.inputEnabledProperty` should enable/disable all input for the dropper

There are 2 occurrences of each of the above PhET-iO elements in ph-scale, 1 occurence in ph-scale-basics.

**Comment by Nancy-Salpepi** [comment]
Looks good in all occurrences in master. Closing.
