### ISSUE TITLE
Problems with record wrapper

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#265]
In https://github.com/phetsims/qa/issues/867#issuecomment-1363403993, @KatieWoe reported the following with https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-dev.1/phet-io/:

> I saw this error when testing the recording wrapper. Not sure what it is, since I didn't see any bugs along with it.
![sawrecording](https://user-images.githubusercontent.com/41024075/209236233-3f06fd00-2bfa-4e46-ace5-975f6cd49e3f.png)

I did not reproduce this in ph-scale 1.6.0-dev.6 or ph-scale-basics 1.6.0-dev.1.  But in master, if I choose "record" in phetmarks, I'm seeing this error. Then the record wrapper does not start.

> MigrationEngine.ts:25 Uncaught TypeError: Cannot read properties of undefined (reading 'preloads')
    at MigrationEngine.ts:25:32
(anonymous) @ MigrationEngine.ts:25
Recorder.js:103 Recorder initialized, sending data to:  ['console']

Assigning to @samreid.

**Comment by pixelzoom** [comment]
To test for https://github.com/phetsims/qa/issues/872 and https://github.com/phetsims/qa/issues/873:

* run the record wrapper with ?console, verify that there is no error on startup
* run the record wrapper with ?localFile, verify that there is no error on startup

**Comment by pixelzoom** [comment]
I have no familiarity with the record wrapper. @samreid has not described what he fixed, or how to verify.  I'm going to proceed with RC testing, and have QA verify this issue.  QA, please wait to verify until @samreid has decribed what the problem was, and how to verify the fix.

**Comment by samreid** [comment]
There were 2 problems, both corrected in the commit.

1. The problem with unbuilt version with the symptom `MigrationEngine.ts:25 Uncaught TypeError: Cannot read properties of undefined (reading 'preloads')
at MigrationEngine.ts:25:32` is that the unbuilt playback wrapper html wasn't updated when MigrationEngine was introduced as a dependency.  The fix can be tested in an unbuilt version by launching the playback wrapper.  If it shows an error like https://github.com/phetsims/ph-scale/issues/265#issue-1509939397 it is still missing the scripts.  If it doesn't have an error like that, then it is OK.  It seems fixed on master.
2. The unexpected token 'export' problem was introduced in https://github.com/phetsims/phet-io-wrappers/commit/17d9f6399f7a8cfa34a6f170fac5a45c1bfd6d01, which made it so saveFile must be loaded as script type = module.  It was corrected by loading the script type as type module.

This issue inspired me to open https://github.com/phetsims/phet-io-wrappers/issues/477 and https://github.com/phetsims/phet-io-wrappers/issues/478

**Comment by samreid** [comment]
Based on the comments and emojis above, I'll assign this to QA and add it to the "issues to verify" column.

**Comment by pixelzoom** [comment]
It's listed in "Issues to Verify" in https://github.com/phetsims/qa/issues/872 and https://github.com/phetsims/qa/issues/873, and the instructions says to label as "ready-for-review".  My understanding is that it's up to @KatieWoe to assign, and move to the "Issues to Verify' column of the QA Pipeline board.

**Comment by samreid** [comment]
Sounds good, I removed the note from the QA column.

**Comment by KatieWoe** [comment]
Looks good in RC.1
