### ISSUE TITLE
Move forward/backward should change the visible ordering in the combo box

### ISSUE THREAD

**Issue by samreid** [phetsims/ph-scale#266]
@matthew-blackman @zepumph and @arouinfar and I committed a fix in https://github.com/phetsims/sun/issues/814 that makes it so that "Move forward" and "Move Backward" correctly skip over invisible children.  That should be cherry picked for https://github.com/phetsims/qa/issues/872.  There is only one commit to cherry-pick, it is https://github.com/phetsims/scenery/commit/6fe6985dd8b36346f224ee500f9cf1699f53f049.  That SHA may change after we merge the branch to master (@zepumph thinks it won't though).

The same should be done for ph-scale-basics as part of https://github.com/phetsims/qa/issues/873

**Comment by pixelzoom** [comment]
This blocks publication of the next RC.

**Comment by pixelzoom** [comment]
This blocks publication of the next RC.  It needs to be patched into both ph-scale 1.6 and ph-scale-basics 1.6.

**Comment by pixelzoom** [comment]
Since https://github.com/phetsims/ph-scale/issues/271 went so poorly due to migration problems, I'm waiting to move forward on this issue until all migration-related issues are resolved and patched.

**Comment by zepumph** [comment]
@samreid and I will cherry pick this.

**Comment by samreid** [comment]
This is cherry picked, and @zepumph and I verified it locally.  It is straightforward to confirm and does not require QA expertise for verification.  @zepumph and I will verify it again in RC.2.

**Comment by zepumph** [comment]
This looks great in the published RC version (basics too). Closing.

I tested:
* that invisible items in the combo box aren't noticed when using "move up" or "move down"
* You cannot move up or down past the edges
* When you move past an invisible node, and then display the visible node again, it is still in the correct location.
