### ISSUE TITLE
You cannot set state on a phetioState:false object!!

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#268]
This issue is to make sure that whatever work in done in https://github.com/phetsims/phet-io/issues/1903 that should be in ph-scale, gets into it. Marking as blocking. No work to be done until I note it.

**Comment by pixelzoom** [comment]
The assertion error for this is:

> must support phetioState to be set

And I'm now seeing this in https://github.com/phetsims/ph-scale/issues/271

**Comment by pixelzoom** [comment]
@zepumph please patch this in ph-scale 1.6 and ph-scale-basics 1.6 when ready.

**Comment by samreid** [comment]
@zepumph and I cherry picked this, and verified it locally by migrating a state from 1.5 using the version migration wrapper.  Nothing more to test that would require QA expertise.  @zepumph and I will test again when RC.2 is up.

**Comment by zepumph** [comment]
This is working great in RC versions. Closing
