### ISSUE TITLE
Customized strings in old studio version applies to active language

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#269]
This issue is to make sure that whatever work in done in https://github.com/phetsims/joist/issues/899 that should be in ph-scale, gets into it. Marking as blocking. No work to be done until I note it.

**Comment by samreid** [comment]
@zepumph and I cherry-picked this and confirmed it works well.  We recommend @Nancy-Salpepi double check it in RC.2 following the directions in https://github.com/phetsims/joist/issues/899

**Comment by zepumph** [comment]
I confirmed in ph-scale and basics 1.6.0-rc.2 that this is working. Ready for close after QA verification

**Comment by Nancy-Salpepi** [comment]
Following the steps in https://github.com/phetsims/joist/issues/899, the sim opens in the current language that is set in studio 1.6 instead of the language it was saved in when using version 1.5.
