### ISSUE TITLE
Improve the version-migration wrapper

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#275]
https://github.com/phetsims/phet-io-wrappers/issues/481 may be relevant for https://github.com/phetsims/qa/issues/873 and https://github.com/phetsims/qa/issues/872

**Comment by zepumph** [comment]
To test for QA:
* You should have a link to test with the version-migration wrapper in the qa issues
* Make customizations in the top version of studio (pointing to the "old" ph-scale 1.5)
* Press the migrate button 
* You will need to enter credentials in the lower simulation.
* Ensure those customizations are migrated to the bottom instance, running 1.6. 
* Be creative and feel free to customize a good amount of stuff, but please please don't spend the time to customize every single option in studio to make sure it can be propagated. Use your judgement.
* Please note that you can set an automatic "migration rate" with the slider (defaults to 0/off). Note that this may make it harder to double check your work, so don't think you need to start here.

**Comment by zepumph** [comment]
Things are good for me in RC.2. Ready for QA to test out the new tool and feel free to close.

**Comment by Nancy-Salpepi** [comment]
Things look good using the directions in https://github.com/phetsims/ph-scale/issues/275#issuecomment-1407134204.
As a side and related to https://github.com/phetsims/phet-io-wrappers/issues/485, I have to enter credentials twice when accessing the wrapper. The first one opens the new version. The second opens the old version. 

I will keep this issue open until @KatieWoe completes testing.

**Comment by samreid** [comment]
> I have to enter credentials twice when accessing the wrapper. 

Yes, that is unfortunuate, but to be expected.

**Comment by KatieWoe** [comment]
Things look pretty good to me too.
