### ISSUE TITLE
Prune unused migration rules

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#278]
Looking into https://github.com/phetsims/ph-scale-basics/issues/56 with @samreid, we are seeing that multiple rules in ph-scale are not actually being used when migrating a PhET-iO state (the only supported migration for 1.6 release). We should clean that up. My guess is that it was vestigial from when we originally copied "common" rules over from gravity-and-orbits.

**Comment by samreid** [comment]
@zepumph and I used this very nice patch to help print out the unused rules.  But this coverage wouldn't be accurate once we start adding other non-state migration rules, so we don't want to assert or console.log it all the time.

<details>

```diff

Subject: [PATCH] Prune unused migration rules, see https://github.com/phetsims/ph-scale/issues/278
---
Index: common/js/migration/MigrationEngine.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/common/js/migration/MigrationEngine.ts b/common/js/migration/MigrationEngine.ts
--- a/common/js/migration/MigrationEngine.ts	(revision 11c46bd47d74931c5b9f69baee5154ca9426c572)
+++ b/common/js/migration/MigrationEngine.ts	(date 1674680340968)
@@ -56,6 +56,11 @@
       const result = migrationRule.processCommand( command, this.oldAPIFlat, this.newAPIFlat );
       command = result.command;
       messageBatches.push( result.messages );
+
+      // If there were no messages, output to the console to say the rule was not used.
+      // if ( result.messages.length === 0 ) {
+      //   console.log( 'Migration rule not used: ' + migrationRule.toString() );
+      // }
     } );
 
     this.migrationCheckers.forEach( checker => checker.call( this, command ) );


```

</details>

**Comment by zepumph** [comment]
We are ready for cherry pick here.

**Comment by samreid** [comment]
@zepumph and I confirmed this is working well locally, we applied the patch and confirmed there are no unused rules in ph-scale.  We will test ph-scale-basics next.  QA expertise will not be needed for this issue.

**Comment by zepumph** [comment]
I checked in ph-scale-basics and all is good there! Closing
