### ISSUE TITLE
StateObject validation is not exclusive of extra keys

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#279]
For cherry picking https://github.com/phetsims/tandem/issues/290

**Comment by samreid** [comment]
@zepumph and I cherry-picked this, and confirmed locally by disrupting the `NumberIO.step` rule in the built rules, and saw that it behaved as expected.  We also tried deleting one of the rules that compensates for this, and saw it correctly errored.  We will double check in the RC.2.  QA expertise not required here.

**Comment by zepumph** [comment]
This is working well in the version migration wrapper of ph-scale and ph-scale-basics 1.6.0-rc.2:

https://phet-dev.colorado.edu/html/ph-scale/1.6.0-rc.2/phet-io/wrappers/version-migration/?oldVersion=https://phet-io.colorado.edu/sims/ph-scale/1.5/wrappers/studio/
https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.2/phet-io/wrappers/version-migration/?oldVersion=https://phet-io.colorado.edu/sims/ph-scale-basics/1.5/wrappers/studio/

Closing
