### ISSUE TITLE
Loading Studio with some nonexistent locales results in assertion errors

### ISSUE THREAD

**Issue by zepumph** [phetsims/ph-scale#281]
Bug reported in https://github.com/phetsims/beers-law-lab/issues/320 and should block ph-scale as well, since it was noted that it occurs in the 1.6.0-rc.2 ph-scale version.

**Comment by zepumph** [comment]
To cherry pick: https://github.com/phetsims/joist/commit/4889cfb3ae2b4a5ab9cdfdfc948a4b3660140cc5

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3 for pH Scale and pH scale Basics. Closing.
