### ISSUE TITLE
When pHProperty is autoselected is different between screens

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ph-scale#282]
While testing the autoselect fixes in https://github.com/phetsims/qa/issues/910 with version 1.6.2-rc.1, I noticed that when `pHProperty` is autoselected differs on the Micro Screen and My Solution Screen. On the Micro Screen, it will autoselect when the mouse is in the gray area of the pH accordion panel. When on the My Solution Screen, it will autoselect when the mouse is over one of the arrows and not the gray area. This is also present in 1.6.1. 

After discussing with JG and SR, and based on the results of a vote held today in the PhET-iO meeting, we decided that this isn't worth spending time on at the moment. 

*****Reduce time to production
*****Avoiding micro-design nit-picky waste of time that yields disproportionate value
****Client-driven needs and feedback

**Comment by pixelzoom** [comment]
@samreid and I worked on this. The pH Meter in My Solution was missing a link to the pHProperty, added in the above commit. 

@samreid and I agreed that this does not warrent review or a maintenance release.  So closing.
