### ISSUE TITLE
Untranslated Azerbaijani Strings

### ISSUE THREAD

**Issue by solaolateju** [phetsims/ph-scale#283]
The list of substances in the Azerbaijani translation of the Ph Scale is not showing the translated strings. The translator have noticed this for a few days now but waiting to see if it was a caching issue or just some delay. 
It seems only the  Azerbaijani version is affected. Other locales show the translated strings. 

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/18397749/232232128-68c44eb1-e8e1-4b4b-8dc9-7ea5017269ef.png">

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/18397749/232232056-62a5ee71-d399-4fdb-b964-ae5e95434b56.png">

**Comment by pixelzoom** [comment]
I'm going to assign this to @jbphet and @liammulh (Rosetta subteam) to investigate.  First thing would be to determine what the locale code is for Azerbaijani. Then verify that the values for keys with the "choice." prefix are indeed being saved to the Azerbaijani.  Perhaps there's a problem with nested keys in Rosetta 2.0.

**Comment by pixelzoom** [comment]
Azerbaijani locale code is "az".

**Comment by pixelzoom** [comment]
babel/ph-scale/ph-scale-strings_az.json does contain entries for the solutes. For example:

```
"choice.batteryAcid": {
    "value": "Akkumulyator turşusu",
...
  "choice.blood": {
    "value": "Qan",
...
  "choice.chickenSoup": {
    "value": "Toyuq Supu",
```

I did not inspect the entries futher to see if they are somehow malformed.

**Comment by pixelzoom** [comment]
Running the sim from the PhET website via https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_az.html, I see the reported problem:

<img width="1003" alt="screenshot_2487" src="https://user-images.githubusercontent.com/3046552/232233439-e5be2e43-acf4-4e69-8c94-171da2bb43ef.png">

**Comment by liammulh** [comment]
I triggered a rebuild for ph-scale/az: https://phet.colorado.edu/sims/html/ph-scale/1.6.2/ph-scale_az.html, https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_az.html.

I believe the strings that were missing are now present.

**Comment by pixelzoom** [comment]
Thanks @liammulh.  The version on the PhET website at https://phet.colorado.edu/sims/html/ph-scale/latest/ph-scale_az.html now looks correct, screenshot below.

@solaolateju please confirm, and close this issue if it looks OK.

<img width="1228" alt="screenshot_2492" src="https://user-images.githubusercontent.com/3046552/233445715-a4dfdd27-8bf1-444a-aa97-8fd9e0cfffe7.png">

**Comment by solaolateju** [comment]
Thank you @liammulh @pixelzoom. Yes, it's ok. I will now close the issue.
