### ISSUE TITLE
Uninstrument Text and RichText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#287]
... the next time this sim is published.  This will  be an API change, and will require migration rules.

**Comment by zepumph** [comment]
https://github.com/phetsims/joist/issues/934

**Comment by pixelzoom** [comment]
`waterFaucetNode.waterText` should remaining instrumented, because `waterFaucetNode.waterText.visibleProperty` is featured.

In general, if a Text/Rich has any featured child elements, consult with @arouinfar before uninstrumenting.

**Comment by pixelzoom** [comment]
Done in the above commits. This should be reviewed before republishing.

**Comment by pixelzoom** [comment]
Uninstrumenting Text and RichText has been the general approach for some time now, and https://github.com/phetsims/phet-io-sim-specific/commit/ca0f101e76c52b708e6921f5d042e17fc0af2c1d added the appropriate migration rules.  So this issue can be closed.
