### ISSUE TITLE
Remove "Beer" from selection possibilities

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/ph-scale#54]
@ycarpenterphet and @pixelzoom --

Concord consortium reported to us that they had to remove "beer" as an option from this sim since many middle schools and high school will not use _anything_ with a mention of alcohol.

We should remove/replace this option.

**Comment by pixelzoom** [comment]
@kathy-phet @ariel-phet For the record... A friend of mine recently asked me why the pH Scale sim doesn’t include beer.  I told him about the reasons that prompted this issue (not mentioning alcohol, etc). He pointed out that the pH Scale was invented by Carlsberg Brewing while researching proteins, amino acids, and enzymes used in the brewing of _beer_.  So in the (imo misguided) attempt to shield students from the real world, the solution that has the most direct tie to pH has been omitted from this sim.
