### ISSUE TITLE
Once sim is redeployed, publish primer video to website

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/ph-scale#57]
The teacher primer video has been recorded using the updated dev version (http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.0-dev.1/ph-scale_en.html) with the new title for the last screen (My Solution).

Since we want the primer and sim to match, we will wait until the sim is redeployed to post the video to vimeo/the sim page.

@schasteen Will be doing the final production and upload of the video.

@pixelzoom I've assigned you for now since you'll know when the sim has been redeployed/published and can assign @schasteen when that happens.

**Comment by pixelzoom** [comment]
@ariel-phet and @phetsims/schasteen ph Scale 1.2.0 has been deployed, so the primer video can be republished.  Assigning to @schasteen.

**Comment by pixelzoom** [comment]
Guess I can't assign to @schasteen because she's not in the contributor list for this repo. Assigning to @ariel-phet.

**Comment by ariel-phet** [comment]
@amanda-phet it seems like the primer stuff is best assigned to you for the moment.

**Comment by amanda-phet** [comment]
Thanks. This is now uploaded.
