### ISSUE TITLE
Bug with H30+/OH- ratio showing when not checked

### ISSUE THREAD

**Issue by BryceAG** [phetsims/ph-scale#64]
Test device: Schrodinger

Operating System: Windows 8, recreated on windows 7 and OS X 10.9.5

Browser: Chrome, firefox, internet explorer, safari

Problem description:
The  H30+/OH- ratio can show when not checked

Steps to reproduce:
Go to the micro section, check and uncheck the ratio box. Empty the beaker of all fluid. Upon refilling it will show the colored dots. It will show the same pattern if you switch to another fluid after. Checking the ratio box again will give the correct pattern, and if unchecked again the pattern will go away.

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/11133527/87b1484c-8953-11e5-9062-4e8b77c2d5e5.png)
The initial error

![image](https://cloud.githubusercontent.com/assets/15327201/11133558/a6b39b28-8953-11e5-9f38-4d5e3c86141d.png)
Switching fluid

![image](https://cloud.githubusercontent.com/assets/15327201/11133567/b524a364-8953-11e5-9d55-c3875e2b7f65.png)
Correct pattern for new fluid

Troubleshooting information (do not edit):
Name: ‪pH Scale‬
URL: http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.0-rc.1/ph-scale_en.html
Version: 1.2.0-rc.1 2015-11-10 20:58:09 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Language: en-US
Window: 1920x971
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"5cacf7c5","branch":"master"},"babel":{"sha":"5736ecd2","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"1c01c622","branch":"master"},"dot":{"sha":"660f4241","branch":"master"},"joist":{"sha":"929223ee","branch":"master"},"kite":{"sha":"5ba9a6bb","branch":"master"},"nitroglycerin":{"sha":"fda44e12","branch":"master"},"ph-scale":{"sha":"afbc88a0","branch":"1.2"},"phet-core":{"sha":"35278ca5","branch":"master"},"phetcommon":{"sha":"8efc0a6e","branch":"master"},"scenery":{"sha":"6242f79b","branch":"master"},"scenery-phet":{"sha":"647eac9d","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"158de3d2","branch":"master"},"tandem":{"sha":"e5842f89","branch":"master"}}

**Comment by pixelzoom** [comment]
Reproduced in 1.2.0-rc.1.  This was not a problem in published on the PhET website (1.1.1, Nov 18, 2014).  This representation (the "colored dots") is implemented in `ph-scale.RatioNode`, and it uses `scenery.CanvasNode`.  Adding debug output to `RatioNode.setVisible` shows that `this.visible === false`, but it is for some reason visible. 

@jonathanolson This smells a lot like https://github.com/phetsims/beers-law-lab/issues/116, where scenery changes you made to `renderer:'canvas'` where resulting in invisible nodes being visible. Could you please have a look and see if this is related?

**Comment by jonathanolson** [comment]
Looking into it.

**Comment by jonathanolson** [comment]
Tracking Scenery changes in the above-marked Scenery issue. I've verified it's a Scenery bug in the same general system that caused https://github.com/phetsims/beers-law-lab/issues/116, but they are both independent.

**Comment by jonathanolson** [comment]
Fix applied in Scenery master, can you confirm?

**Comment by pixelzoom** [comment]
Fix confirmed.  Nice that it was a one-line fix in scenery. Unfortunate that we'll need to update to master and do another full RC test cycle. This is yet another example of how PhET's SCM process does not address our real needs. See https://github.com/phetsims/chipper/issues/395#issuecomment-156889888.

Closing.

**Comment by pixelzoom** [comment]
Related to RC test https://github.com/phetsims/tasks/issues/420.

**Comment by pixelzoom** [comment]
Fix was applied in https://github.com/phetsims/scenery/commit/c0c08ec5a6e97f467025d60a97274ffec57e2098.
