### ISSUE TITLE
Bug where ph sensor gives a value outside of liquid

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/ph-scale#65]
Test device: Personal, Chadwick, Schrodinger

Operating System: Win 7, recreated on Chromebook, Win 8

Browser: Chrome, Firefox, Internet Explorer

Problem description: In the Macro tab of the sim, when the probe is in the very top-left corner, it will display the pH as if it were inside the liquid. Also, if you start draining the liquid, the sensor will display a pH of 7 (no matter what pH the liquid actually is.) This seems to be recreated across all platforms.

Steps to reproduce: Go into the Macro tab, move the probe up to the very top-left corner, and notice that it displays a number. Adding water will change the number normally as if it were in the liquid. Draining liquid will change the value to 7. 

Severity: Minor

Screenshots:
![1](https://cloud.githubusercontent.com/assets/11947677/11135125/57486422-895f-11e5-98ce-6ac0547c645b.PNG)

And while draining liquid, it displays 7
![2](https://cloud.githubusercontent.com/assets/11947677/11135132/6b65f230-895f-11e5-895f-8cea93535b7d.png)

Troubleshooting information (do not edit):
Name: ‪pH Scale‬:‪pH Scale‬
URL: http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.0-rc.1/ph-scale_en.html?stringTest=double&dev
Version: 1.2.0-rc.1 2015-11-10 20:58:09 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 9 uniform: 254
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"5cacf7c5","branch":"master"},"babel":{"sha":"5736ecd2","branch":"master"},"brand":{"sha":"3b236d6f","branch":"master"},"chipper":{"sha":"1c01c622","branch":"master"},"dot":{"sha":"660f4241","branch":"master"},"joist":{"sha":"929223ee","branch":"master"},"kite":{"sha":"5ba9a6bb","branch":"master"},"nitroglycerin":{"sha":"fda44e12","branch":"master"},"ph-scale":{"sha":"afbc88a0","branch":"1.2"},"phet-core":{"sha":"35278ca5","branch":"master"},"phetcommon":{"sha":"8efc0a6e","branch":"master"},"scenery":{"sha":"6242f79b","branch":"master"},"scenery-phet":{"sha":"647eac9d","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"158de3d2","branch":"master"},"tandem":{"sha":"e5842f89","branch":"master"}}

**Comment by pixelzoom** [comment]
Reproduced in 1.2.0-rc.1 and in 1.1.1 on PhET website, so not a new problem.

**Comment by pixelzoom** [comment]
Problem is specific to when the probe's location is (0,0).  At this line in MacroPHMeterNode, `probeNode.isInDrainFluid()` is erroneously returning true:

`435 if ( probeNode.isInSolution() || probeNode.isInDrainFluid() ) {`

So at (0,0), the probe thinks it's in fluid coming out of the drain faucet.

**Comment by pixelzoom** [comment]
In MacroPHMeterNode.ProbeNode.isInDrainFluid`, the bounds of `drainFluidNode` are reported to be `[x:(-0.5,0.5),y:(-0.5,0.5)]`, which is clearly incorrect.  Looking at `FaucetFluidNode` (the type of `drainFluidNode`), it uses an empty rectangle positioned at (0,0) when there is no fluid:

`42 thisNode.setRect( 0, 0, 0, 0 ); // empty rectangle`

So the position of this rectangle is the problem. Changing to this should fix it:

`42 thisNode.setRect( -1, -1, 0, 0 ); // empty rectangle, at a location where we won't intersect with it`

**Comment by pixelzoom** [comment]
One-line fix (as shown above) in master and 1.2 branch. No need to do another RC for this specific issue.

Closing.

**Comment by pixelzoom** [comment]
Related to RC test https://github.com/phetsims/tasks/issues/420.
