### ISSUE TITLE
remove pH values from combo box

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/ph-scale#69]
> Doesn't putting the pH level of each solution in parentheses next to the solution's name kind of defeat the purpose of figuring out the pH of it? My students were really bummed because they couldn't make a hypothesis beforehand, and even using the pH meter, they already knew the answer. Even my "lowest" students knew that below 7 is an acid and above 7 is a base, so they flew through that portion of the lab.

**Comment by pixelzoom** [comment]
Gotta say that I agree with this one - I've always found it odd that we display the pH values in the combo box.   (The combo box is also ordered by descending pH value.)

On the first screen, all you have to do is put the pH probe in the solution, like this:

![screenshot_94](https://cloud.githubusercontent.com/assets/3046552/21114639/f59e3ece-c06a-11e6-9957-b788c3430799.png)

On the second screen, the probe is always in the solution.  And what's the point of having a 'collapse' button on the pH probe if the value is shown in the combo box? 

![screenshot_95](https://cloud.githubusercontent.com/assets/3046552/21114664/0fc7a524-c06b-11e6-96f5-494d6987a36a.png)

**Comment by ariel-phet** [comment]
My guess is this was done so that you could see how adding water or starting out with water and adding different known pH substances affected the solution. 

Definitely a question for @amyh-phet and @emily-phet (we could also reach out to YY since this was her sim). I imagine this is documented in the design doc, YY was pretty thorough.

**Comment by pixelzoom** [comment]
Whoops, accidentally deleted my comment.

**Comment by pixelzoom** [comment]
Attempt to reproduce my comment....

Gotta say that I agree with this one. I've always found it odd that we display the pH values in the combo boxes. (And the combo boxes are ordered by descending pH, another potential give away.)

On the first screen, you can put the pH probe in the solution to measure the pH.  Simply leave it there if you want to switch between solutions for comparison.

![screen1](https://cloud.githubusercontent.com/assets/3046552/21114855/d39af7bc-c06b-11e6-83be-a2ad58c76fca.jpg)

On the second screen, the pH display is sitting right next to the combo box, kind of redundant. And the expand/collapse button on the pH display let's you show/hide the pH.  But what's the point when the pH value is in the combo box? 

![screen2](https://cloud.githubusercontent.com/assets/3046552/21114888/f6aca48a-c06b-11e6-8969-63098528f0e6.jpg)

**Comment by pixelzoom** [comment]
@ariel-phet said:
> My guess is this was done so that you could see how adding water or starting out with water and adding different known pH substances affected the solution.

I guess that's a reasonable reason. But (as this teacher points out) it sabotages the more introductory task of experimenting with (and comparing) various known solutions.

**Comment by emily-phet** [comment]
@pixelzoom I would suggest reaching out to YY. I agree she will likely have something about this decision documented. Off the top of my head it seems needlessly redundant as you suggest, but I'd be surprised if there wasn't some reasoning behind it. We might disagree with the reasoning, but it would be nice to know what it was.

**Comment by amyh-phet** [comment]
@oliver-phet  @ariel-phet @pixelzoom   I agree that having the pH in the combo box does provide redundant information and gives away a lot of information to the user.  I can look at the design docs to see if we can figure out why this was done.  My impression is that YY likely had a good reason for doing this, so it would be helpful to know her thinking before making changes.

**Comment by ariel-phet** [comment]
@amyh-phet when you get a chance please peruse the design doc...if nothing is obvious, let me know and I will reach out to YY

**Comment by amyh-phet** [comment]
@ariel-phet   I looked through the HTML 5 design doc and did not find any reason for labeling the solutions in the combo box with their pH. It looks like this behavior was carried over from the Java version. The only mention of the label for the solutions in the combo box was a justification for labeling solutions as Spit (pH 7.4) instead of Spit (7.4).  Thinking we'll need to reach out to YY to figure this out.  I'm guessing it is related to what you mentioned above as one of the learning goals for both MS and HS is to explain how adding water or removing liquid from the beaker effects pH.

**Comment by pixelzoom** [comment]
I looked through the design doc for the Java version - it's checked in to Unfuddle at https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Fph-scale%2Fdoc%2Fph-scale-design.pdf&commit=74659. The mockups in that document don't show the pH value in the combo box.  So I'm not sure when or why it was introduced.

You might also consider asking Trish and Kathy.  Besides me, they are the only team members who were involved with the design process for the Java version.

**Comment by amyh-phet** [comment]
@pixelzoom   Thanks for checking the Java design doc.  I'll get in touch with Trish to see if she knows why this might have been included.

**Comment by amyh-phet** [comment]
@oliver-phet  @pixelzoom @ariel-phet   I checked with Trish and she does not recall why this was included in the design.  Let me know if you need me to reach out to YY.

**Comment by ariel-phet** [comment]
I will reach out to YY

**Comment by oliver-phet** [comment]
Yes, let's reach out to YY. If she doesn't have a reason, I think we should consider removing.

**Comment by ariel-phet** [comment]
YY says:

> I won't have a chance to dig into this today (final exam is due at the printer's at end of day), but should be able to reply by end of the week.

**Comment by pixelzoom** [comment]
Presumably, if we decide to remove it from ph-scale, then we'll also want to remove it from ph-scale-basics.

Note to self:  This will be relatively easy to patch into a maintenance release. The change is in SoluteComboBox, from this:

```js
68      var textNode = new Text(
69      StringUtils.format( pattern0Name1PHString, solute.name, Util.toFixed( solute.pH, PHScaleConstants.PH_COMBO_BOX_DECIMAL_PLACES ) ),
70       { font: new PhetFont( 22 ) } );,
```

to this:

```js
    var textNode = new Text( solute.name, { 
      font: new PhetFont( 22 ) 
    } )
```

**Comment by pixelzoom** [comment]
Hi @ycarpenterphet. Nice to see your smiling face on GitHub. And happy new year!

@amyh-phet @ariel-phet If you'd like me to proceed with this change, assign to me.

**Comment by ariel-phet** [comment]
@pixelzoom marking low priority - basically I would say make this change when you need a mental break from unit rates.

**Comment by pixelzoom** [comment]
Code changes are done (master & 1.2 branches) and tested in requirejs mode.  

I was unable to publish because the recent requirejs update (https://github.com/phetsims/chipper/issues/538) broke the sim deployment instructions. Discussing on Skype, there are now additional "npm update" instructions that are needed. Putting deployment on hold until instructions are fixed.

**Comment by pixelzoom** [comment]
Note to self:  After https://github.com/phetsims/phet-info/issues/39 is addressed, need to deploy ph-scale 1.2.8 and ph-scale-basics 1.2.8.

**Comment by pixelzoom** [comment]
@ariel-phet Do you want the screenshots updated for ph-scale and ph-scale-basics? The screenshots show the pH values in the combo box, but you'd really need to be looking for them to notice. Updating screenshots is not something that I'm equipped to do (no retina iPad).

**Comment by pixelzoom** [comment]
Current thumbnail and screenshot:

![screenshot_112](https://cloud.githubusercontent.com/assets/3046552/21817981/53bd61aa-d723-11e6-8c59-9dae3056af1e.png)

![screenshot_113](https://cloud.githubusercontent.com/assets/3046552/21817984/561d8222-d723-11e6-9296-e3df1eaab2b1.png)

**Comment by pixelzoom** [comment]
Actually, @ariel-phet never mind. I'll take the pH value out of the current screenshots in Photoshop.

**Comment by pixelzoom** [comment]
ph-scale 1.2.8 and ph-scale-basics 1.2.8 have been deployed to the PhET website.   English versions of both sims were tested, several translations were spot tested.

This took about twice as long as it should have, because I spent considerable time dealing with faulty "sim deployment" instructions (see https://github.com/phetsims/phet-info/issues/39). 

Closing.

**Comment by pixelzoom** [comment]
Reopening. @oliver-phet please notify the user who requested this change. Then you can close this issue.

**Comment by oliver-phet** [comment]
Email to user sent. Re-closing.

**Comment by oliver-phet** [comment]
From user:
> Ahhhhhhh! That looks SOOOOOO much better :)
> 
> Unfortunately, my class is done with pH now for the year, but it's definitely in my plans for next year, so I look forward to using PhET again.

**Comment by pixelzoom** [comment]
@oliver-phet Thanks for posting the user's reaction - nice to hear.
