### ISSUE TITLE
layout of panel is messed up

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#70]
Should look like this, as in published version 1.2.10:

![screenshot_341](https://user-images.githubusercontent.com/3046552/29146171-1be34c18-7d1d-11e7-812a-d96a4b9cf4ee.png)

Looks like this in master:

![screenshot_342](https://user-images.githubusercontent.com/3046552/29146179-283a7c70-7d1d-11e7-9a69-1a519f52a44e.png)

Zooming in on the messed up panel:

![screenshot_343](https://user-images.githubusercontent.com/3046552/29146203-3d7fe7d2-7d1d-11e7-8567-034a3ae7a901.png)

I don't see any recent changes to Panel, so perhaps recent changes to RichText? @jonathanolson?

**Comment by pixelzoom** [comment]
Relevant code in BeakerControls.js:

```js
    // 'H3O+/OH- ratio' check box, with color-coded label, spacing tweaked visually
    var textH3O = new RichText( PHScaleConstants.H3O_FORMULA, { font: FONT, fill: PHScaleColors.H3O_MOLECULES } );
    var textSlash = new Text( '/', { font: FONT, left: textH3O.right + 2 } );
    var textOH = new RichText( PHScaleConstants.OH_FORMULA, {
      font: FONT,
      fill: PHScaleColors.OH_MOLECULES,
      left: textSlash.right + 4,
      supXSpacing: 2
    } );
    var textRatio = new Text( ratioString, { font: FONT, left: textOH.right + 4 } );
    var ratioLabel = new Node( { children: [ textH3O, textSlash, textOH, textRatio ] } );
    var ratioCheckBox = new CheckBox( ratioLabel, ratioVisibleProperty );
```

**Comment by pixelzoom** [comment]
This was probably broken when SubSupText was replaced with RichText in https://github.com/phetsims/ph-scale/commit/00fc1f90462d0e859e3685bfd6f9405354eb7b8b.

**Comment by jonathanolson** [comment]
Investigating.

**Comment by pixelzoom** [comment]
I'm guessing there was something specific about where SubSupText had its origin.

**Comment by jonathanolson** [comment]
Likely broken when I added in multi-line support (VBox now holds lines, and that places the origin of the RichText in a different location).

I'll replace the VBox with custom layout in RichText, which should fix this.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit, can you verify?

**Comment by pixelzoom** [comment]
👍 Closing.
