### ISSUE TITLE
eliminate reentrant Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#72]
Related to https://github.com/phetsims/axon/issues/179.

Determine whether `pHValueProperty` (EDIT: renamed to `spinnerProperty`) in PHMeterNode really needs to be `reentrant: true`.  If so, document why.

**Comment by pixelzoom** [comment]
The reentry here occurs in the "My Solution" screen, when you change the pH value with the spinner.  It's almost certainly due to floating-point error.  E.g.:

`Assertion failed: reentry detected, value=7.03, oldValue=7.029999999999999`

**Comment by pixelzoom** [comment]
As I recall, the model in this sim attempts to constrain pH to 2 decimal places.  In Solution.js:

```js
68    pH = Util.toFixedNumber( pH, PHScaleConstants.PH_METER_DECIMAL_PLACES ); // constrain to the pH meter format, see issue #4
```

Whatever that was intended to fix, it's probably causing other problems.

**Comment by pixelzoom** [comment]
So... `pHValueProperty` may not need to be reentrant.  But we'd probably need to revisit the constraint of values in the model (#4), and that's going to be nontrivial.  So marking this as deferred until this sim gets instrumented for PhET-iO.  Then we can make a decision about whether it's worth the effort to remove intermediate values from the data stream.

**Comment by pixelzoom** [comment]
Un-deferring this as part of PhET-iO design.   

If we need to create a CustomSolute for iO, then this intermediate `pHValueProperty` will go away, and we'll be observing/manipulating CustomSolute's `pHValueProperty`.

**Comment by pixelzoom** [comment]
We will not be adding anything like CustomSolute.  So deferring this issue.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/ph-scale/issues/92#issuecomment-583156907, @arouinfar said:
> I do not see any issues opened prior to the PhET-iO work that would need to be addressed before publication.

@arouinfar I'm OK with continuing to defer this.  But I wanted to make sure that you realized that this issue does have implications for PhET-iO.  

See https://github.com/phetsims/ph-scale/issues/72#issuecomment-418192071 specifically -- there may still be intermediate states in the data stream.  I'm not sure whether that's still the case, or what the implications are -- perhaps someone from the PhET-iO team can comment (@samreid @zepumph @chrisklus).

**Comment by arouinfar** [comment]
@pixelzoom I could not find a `spinnerProperty` in the tree and searching studio yielded 0 results. The closest thing I could find was `pHProperty` which behaves as I would expect when changing the pH (NumberSpinner or graph controls). Looking at the data stream in the console, I'm also not seeing any errant messages about the `pHProperty`. I think we can probably continue to defer this issue.

I don't really understand what it means to be reentrant, so I would also be curious to hear from someone on the PhET-iO team about the implications.

**Comment by zepumph** [comment]
@arouinfar currently this isn't PhET-iO instrumented. That is why you don't see it.

>See #72 (comment) specifically. There may be intermediate states in the data stream. I'm not sure whether that's still the case, or what the implications are -- perhaps someone from the PhET-iO team can comment (@samreid @zepumph @chrisklus).

I don't know why we are assigned to this particular issue. To me the steps for this are as follows (note that I'm not involved in the design of this phet-io instrumentation process at all):

* Decide whether this should be instrumented (if not do not continue)
* Instrument the Property
* Have a design team look at the data stream as it pertains to the `spinnerProperty`.
* Determine if it is acceptable, as it pertains to intermediate values)
* If not, potentially tackle the non-trivial update in https://github.com/phetsims/ph-scale/issues/72#issuecomment-418192071.


How does that sound?

**Comment by pixelzoom** [comment]
@zepumph said:
> I don't know why we are assigned to this particular issue.

Sorry, let me clarify.  If this Property were to be instrumented and is reentrant, will there we intermediate states in the data stream?  I seem to recall mention of some work that was done to eliminate intermediate states from the data stream, but I don't recall details, or it could be a wishful hallucination.  I was hoping that someone from the PhET-iO team could clarify.

**Comment by zepumph** [comment]
Oh I see. Thanks. Yeah as far as I remember there will still be intermittent states. @samreid can you confirm?

**Comment by samreid** [comment]
> If this Property were to be instrumented and is reentrant, will there we intermediate states in the data stream?

Yes.

**Comment by pixelzoom** [comment]
I've confirmed that there is no need to instrument `spinnerProperty`.   And I confirmed that there are no intermediate message message in the data stream from `solution.pHProperty`.   I've added a comment in the code, noting that  `spinnerProperty` must not be instrumented, and referencing this issue. 

So there is nothing left to do here, closing.

**Comment by pixelzoom** [comment]
Notes about how I confirmed.... I added this line to PHMeterNode:

`solution.pHProperty.link( pH => console.log( `pH=${pH}` ) );`

Then followed these steps:

1. Start the sim
2. Got to _My Solution_ screen
3. Use the spinner on the pH meter to change pH value.
4. Note that there is exactly 1 console message for each press of the spinner value.
