### ISSUE TITLE
title case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#73]
For phetsims/tasks/issues/953
Should the "Molecule count" checkbox be in title case?  The "H3O/OH ratio" checkbox is less clear but bringing attention here.

**Comment by arouinfar** [comment]
Thanks @KatieWoe.  For consistency, I would capitalize both "count" and "ratio", but that can wait until this sim is worked on again.

**Comment by pixelzoom** [comment]
Changed to title case in master, see screenshot below.  Labeling as "fixed-awaiting-deploy".

![screenshot_822](https://user-images.githubusercontent.com/3046552/47887843-1d268080-de07-11e8-9fb7-9cd9b8bad515.png)

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom!

**Comment by KatieWoe** [comment]
Looks good in 1.3.0-rc.1
