### ISSUE TITLE
start with Water selected in combo box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#76]
In https://github.com/phetsims/ph-scale/issues/75, we added Water to the solutes combo box. At 3/21/19 status meeting, @emily-phet suggested that maybe Water should be the initial section when the sim starts up. (It's currently Chicken Soup in all screens.)

Assigning to @arouinfar to evaluate. Please get input from Argenta.

Please consider this for pH Scale and pH Scale: Basics, and whether it applies to all screens or specific screens.

**Comment by pixelzoom** [comment]
The [pH Scale HTML5](https://docs.google.com/document/d/1N2PZJvzs-zmyjJLS87L3O06M1XBXB-ZinmzCVvIfcpI/edit) design document contains information about why Chicken Soup was chosen as the initial solute:

| Feature | Reason | Detailed changes & Rationale |
| :--- | :--- | :--- |
| Startup Solution | L (Layout and Look/Feel) | With the new white background, milk is no longer a good choice of starting solution, since it blends into the background. Another solution near neutral is desirable - spit resembles water too much, and may mislead students who have just started the sim; blood has a significant squeamish-factor for some students. Added a new solution, chicken soup (pH 5.8 [REF](http://foodscience.caes.uga.edu/extension/documents/fdaapproximatephoffoodslacf-phs.pdf)), which has a specific pH in the desired range and an appealing color. |

**2013-12-06 Updates**
Starting solution changed to Chicken Soup
Tea - Wide range of possible pH values, and wide range of possible types of tea which could be at the extremes of the range

Soup - Needed a specific soup, since cream-based soups have a significantly different pH range than broths. Chicken soup seems relatively universal, and a good color. pH = 5.8
[reference = FDA via University of Georgia  http://www.foodscience.caes.uga.edu/extension/documents/fdaapproximatephoffoodslacf-phs.pdf]

**Comment by pixelzoom** [comment]
Reading through interview and meeting notes in the [pH Scale HTML5](https://docs.google.com/document/d/1N2PZJvzs-zmyjJLS87L3O06M1XBXB-ZinmzCVvIfcpI/edit) design document, it looks like there was some confusion when the initial solution color was too similar to water, and the goal was to pick an initial solute that resulted in a solution that is has a color that is very different from water.  Search for "initial" for relevant notes.

**Comment by pixelzoom** [comment]
The [pH Scale Java](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Fph-scale%2Fdoc%2Fph-scale-design.pdf&commit=74956) design documented doesn't provide any information about why Milk was chosen as the initial solute.

**Comment by kathy-phet** [comment]
@arouinfar - What do you think here? I am thinking starting with Water might be good for both sims - and not have the downfalls that starting with "Spit" had in that it is indeed water with a 7 pH.

**Comment by pixelzoom** [comment]
Raising the priority of this issue, since I've been instructed to being RC testing.  @arouinfar do you want this issue addressed before RC testing?

**Comment by arouinfar** [comment]
@pixelzoom thank you for reviewing the design doc and interview notes!

>  It looks like there was some confusion when the initial solution color was too similar to water

I think the confusion likely stemmed from the solution looking like water, but not being water. However, I do like the idea of having water as the initial solute for both sims, so I'd like to give it a try. 

@pixelzoom please go ahead and make water the default solute.

@kathy-phet I could add this sim to the end of the upcoming Diffraction screen interviews just to confirm there isn't any confusion/flow issues with water being the new default.

**Comment by pixelzoom** [comment]
Done, water is now the default solute.  

@arouinfar Here are dev versions for verification/interviews:

[ph-scale 1.3.0-dev.5](https://phet-dev.colorado.edu/html/ph-scale/1.3.0-dev.5/phet/ph-scale_en_phet.html)
[ph-scale-basics 1.3.0-dev.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.3.0-dev.1/phet/ph-scale-basics_en_phet.html)

**Comment by arouinfar** [comment]
Looks good @pixelzoom, thanks.

**Comment by KatieWoe** [comment]
Looks good in both rcs
