### ISSUE TITLE
bogus touchArea for eyedropper (ProbeNode bug)

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#77]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Red pointer area that can control the pointer node (may be connected to https://github.com/phetsims/scenery-phet/issues/488)

Screenshots:
![Image from iOS](https://user-images.githubusercontent.com/41024075/56069380-071ad580-5d40-11e9-84fd-7e790fdb3923.png)

**Comment by pixelzoom** [comment]
The bogus touchArea (red rectangle) shown in https://github.com/phetsims/ph-scale/issues/77#issue-433955384 was a sim-specific bug, fixed in the above commit. 

The incorrect mouseArea (blue shape) is still a problem.  At 4/25/19 dev meeting, @ariel-phet said that the root issue phetsims/scenery-phet#488 is not a priority so it (and this issue) is deferred.

**Comment by pixelzoom** [comment]
@KatieWoe since this issue is liable to be open for awhile, I took the liberty of changing the title to remind me specifically what the problem is.

**Comment by KatieWoe** [comment]
It seems to have been fixed in the rcs in progress now.  I'm not sure what issue it was recorded/committed in if not this one though.

**Comment by pixelzoom** [comment]
This will not be addressed for the PhET-iO release.

**Comment by pixelzoom** [comment]
I no longer see this problem with master on:

* MacBook Pro + macOS 11.2.3 + any browser
* iPhone 11 + iOS 14.4.2 + Safari
* iPad6 + iPadOS 14.4.2 + Safari
 
So perhaps it has self-healed. 

@KatieWoe can you confirm, when you have a moment (not high priority).  And if you can no longer reproduce, please close.

**Comment by KatieWoe** [comment]
I don't see this anymore either. Closing, and will reopen if this ever resurfaces.
