### ISSUE TITLE
LoL icons/descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ph-scale#80]
For https://github.com/phetsims/QA/issues/323

**Comment by pixelzoom** [comment]
I've added this issue to the list in phetsims/QA#323.

@arouinfar Does this also apply to ph-scale-basics, for phetsims/QA#326?

**Comment by pixelzoom** [comment]
Three other questions, I'm confused about the state of this issue.

(1) Why is this issue assigned to @arouinfar? 
(2) Should this issue be labeled “status:ready-for-qa”? 
(3) Does this also apply to ph-scale-basics, for phetsims/QA#326?

**Comment by arouinfar** [comment]
> (1) Why is this issue assigned to @arouinfar?

The responsible designer needs to create icons, descriptions, keywords, and a few other things to deliver to LoL when a sim is published (part of master checklist) or when an older sim redeploys adding LoL support. For this sim, that'd be me.

> (2) Should this issue be labeled “status:ready-for-qa”?

No. There is nothing for QA to test related to this issue. In the rc issue under "What to test" there is an item for checking whether or not a sim has already been delivered to LoL, and if not, to create an issue.  This is to ensure the responsible designer is aware that a sim is being redeployed with LoL support -- while the designer should be tagged in QA issues, they aren't always. This step is to ensure a sim doesn't slip through the cracks.

I tagged the rc issue so @KatieWoe would be aware that I already made the LoL issue.

> (3) Does this also apply to ph-scale-basics, for phetsims/QA#326?

On the LoL platform, each screen is its own "sim", and assets are created fo reach individual screen of a sim. Here's a screenshot from LoL showing the Build an Atom simulation, separated into three separate items.

![image](https://user-images.githubusercontent.com/8419308/58344750-c9679d00-7e13-11e9-900e-7270a3b809b4.png)

Generally speaking, we deliver all sims to LoL, with the exception of redundant screens. For suites of math sims, we may deliver only 9/12 screens to avoid redundant material. Since pH Scale: Basics is essentially just the first screen of pH Scale, it won't be delivered to LoL. The same would apply to Concentration, since it's just the first screen of Beer's Law Lab.

**Comment by arouinfar** [comment]
> I've added this issue to the list in phetsims/QA#323.

QA doesn't need to test anything, so it should be removed. I'll go ahead and do that.

**Comment by pixelzoom** [comment]
Thanks for clarification.

**Comment by arouinfar** [comment]
Assets are ready for delivery to LoL when the sim redeploys.
