### ISSUE TITLE
Hand cursor when faucet shooter is disabled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#84]
**Test device:**
Dell
**Operating System:**
Win 10 (or other)
**Browser:**
Chrome (or other)
**Problem description:**
For https://github.com/phetsims/QA/issues/323 and https://github.com/phetsims/QA/issues/326.
Likely very minor.  Appears in published version as well.  When clicking down on the plunger that empties the bucket when it is grayed out, the mouse becomes a hand.
**Steps to reproduce:**
1. Go to any page that has this plunger
2. Empty bucket if not already
3. Hover mouse over grey plunger, then click down

**Screenshots:**
![isitodd](https://user-images.githubusercontent.com/41024075/58646880-931e9780-82c3-11e9-9acd-d7225f0b04bf.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪pH Scale: Basics‬
URL: https://phet-dev.colorado.edu/html/ph-scale-basics/1.3.0-rc.1/phet/ph-scale-basics_all_phet.html
Version: 1.3.0-rc.1 2019-05-24 13:37:56 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
This part of the faucet is known as the "shooter".  The shooter's `enabledProperty` was not setting `pickable:false` when the shooter is disabled.   Fixed in the above commit.   @KatieWoe could you please verify in master?

**Comment by KatieWoe** [comment]
Looks good.

**Comment by pixelzoom** [comment]
Thank @KatieWoe.  

Note to self: I still need to create branch "ph-scale-1.3" for scenery-phet and apply this fix there.

**Comment by pixelzoom** [comment]
Branch patches completed.  Ready for testing in upcoming 1.3.0-rc.2.

**Comment by pixelzoom** [comment]
Talked with @jonathanolson. I should also create and patch "ph-scale-basics-1.3" branch for scenery-phet.

**Comment by pixelzoom** [comment]
Patched in "ph-scale-basics-1.3" branch of scenery-phet.

**Comment by pixelzoom** [comment]
Verified in https://github.com/phetsims/QA/issues/374 and https://github.com/phetsims/QA/issues/375, closing.
