### ISSUE TITLE
update credits for 1.3.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#87]
For phetsims/QA#323 and phetsims/QA#326.

@KatieWoe requested that I add the following to QA credits:

Liam Mulhall, Ethan Ward, and Kathryn Woessner 

Looks like I should also factor out `PHScaleConstants.CREDITS` and use in both ph-scale-main.js and ph-scale-basics-main.js.   Credits are currently duplicated, and that's certainly going to be the case going forward, since ph-scale-basics is derived from ph-scale.

**Comment by pixelzoom** [comment]
Done, to be reviewed in the next RC.

**Comment by pixelzoom** [comment]
@arouinfar I don't see you list in the credits, and you've had a hand in the design changes that will appear in this release (e.g. adding 'Water' to solutes).   Would you like me to add you? And if so, should I add you to "Lead Design" or "Team"?

**Comment by pixelzoom** [comment]
Note to self: These changes need to be pushed to the 1.3 branch.

**Comment by arouinfar** [comment]
@pixelzoom please add me to the Team.

**Comment by pixelzoom** [comment]
@arouinfar has been added to the Team credits.

**Comment by pixelzoom** [comment]
Changes have been cherry-picked to the 1.3 branches of ph-scale and ph-scale-basics.  Labeling as "fixed-awaiting-deploy", to be verified in 1.3.0-rc.2.

**Comment by KatieWoe** [comment]
Jaspe Arias should be added.

**Comment by pixelzoom** [comment]
Jaspe Arias has been added to QA credits in master and 1.3 branches.

**Comment by KatieWoe** [comment]
Looks good rc.3
