### ISSUE TITLE
verify patch for phet-ios-app#484 ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#90]
In https://github.com/phetsims/QA/issues/323#issuecomment-509418037 and https://github.com/phetsims/QA/issues/326#issuecomment-509417975, @chrisklus said:
> Patched issue phetsims/phet-ios-app#484 on this release branch.

Accordding to @KatieWoe, QA testing was done in https://github.com/phetsims/QA/issues/360, and that issue is closed.  But https://github.com/phetsims/phet-ios-app/issues/484 is still open.

I have been unable to determine if this patch involved and changes to sim or common code, so I can't evaluate the impact on this release branch.   And unpublished sims apparently can't be tested for this issue. 

@ariel-phet and @KatieWoe please discuss and decide whether this needs to be part of https://github.com/phetsims/QA/issues/374.

**Comment by KatieWoe** [comment]
I don't know if its in the sim or not, but I can't really test as part of https://github.com/phetsims/QA/issues/374 because it involves looking at how the sim behaves in the app.  Since there is currently no way to test a sim in the app before it is published.

**Comment by pixelzoom** [comment]
According to @chrisklus via Slack, the changes were in phetcommon and phet-ios-app.   I see ph-scale-1.3 and ph-scale-basics-1.3 branches for phetcommon, but not for phet-ios-app (which may have different branching rules?)

**Comment by chrisklus** [comment]
I think I was mistaken and changes were just in phetcommon, my apologies. @jonathanolson knows the answer to these questions.

**Comment by ariel-phet** [comment]
@KatieWoe @pixelzoom for now I think just go ahead and publish if everything looks good and we can check in the app after published. I know that is pretty unideal, however, since this patch has been verified, we just need to make sure the sim opens, and it should be pretty low risk.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> for now I think just go ahead and publish if everything looks good and we can check in the app after published. ...

@ariel-phet Please clarify -- check after the app is published, or after pH Scale 1.3.0 is published?

**Comment by ariel-phet** [comment]
@pixelzoom check ph Scale 1.3.0 in the Android app after pH Scale 1.3.0 is published.

**Comment by pixelzoom** [comment]
Self assigning.  After pH Scale 1.3.0 is published, I will assign to QA for verification.

**Comment by pixelzoom** [comment]
pH Scale and pH Scale: Basics 1.3.0 have been published, so this issue can now be verified.  Assigning to @KatieWoe to prioritize and assign.

**Comment by KatieWoe** [comment]
Patch on published version of the app looks good
