### ISSUE TITLE
Interrupting initial filling of bucket

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ph-scale#91]
For https://github.com/phetsims/QA/issues/374 (and basics).
If you click the dropper while the bucket is automatically filling up, it will stop at the .5 level, but the button will still look depressed.  Letting go and clicking again will stop the issue, and it is rather hard to pull off without slowing animation speed.
![veryedgecase](https://user-images.githubusercontent.com/41024075/61897821-2398e300-aed5-11e9-8d4b-2e16fa29334c.gif)

**Comment by pixelzoom** [comment]
@KatieWoe I don't see any Troubleshooting info for this issue. What platform? 

Also... Does this problem appear in the previous RC, 1.3.0-rc.1?   I'm wondering if the changes made for #86 might have introduced this problem.

**Comment by KatieWoe** [comment]
I got it to happen on Win 10 chrome, but that is probably because I move faster on this device.  Might also be easier to achieve without slowing on a touch screen like an iPad.  I'll have to go back and check.  This is such an edge case that it would be very easy to miss.

**Comment by KatieWoe** [comment]
Published Behavior: Liquid stops, but dropper does not look depressed
![publishedbehavior](https://user-images.githubusercontent.com/41024075/61899154-16312800-aed8-11e9-8d5d-4b31cb74c24d.gif)
First RC:  Same as current RC
![firstrcbehavior](https://user-images.githubusercontent.com/41024075/61899220-395bd780-aed8-11e9-95b8-980fe75b5be9.gif)

**Comment by pixelzoom** [comment]
So this problem was not in the published version (1.2 branch) and is in the 1.3 branch.  So it was probably present in master when 1.3 branch was created.  I don't see any obvious differences in EyeDropperNode, so I'm guessing this is due to a change in something related to input event handling for buttons.   @jonathanolson Any ideas?

**Comment by pixelzoom** [comment]
Forgot to mention... My recommendation is option (a).  Disabling interaction with the eyedropper seems unnecessary and potentially disconcerting to the user in some situations.

**Comment by arouinfar** [comment]
@pixelzoom I'm perfectly happy to do nothing, given that this takes quite a few steps to reproduce (including the use of non-public-facing query parameters) and doesn't create a pedagogically problematic situation.

**Comment by pixelzoom** [comment]
I found an easy way to address this that took 5 minutes and shouldn't present any problems for the user.  When auto-fill begins or ends, interaction with the eyedropper is cancelled.  That's implemented in the above commit.  @arouinfar @KatieWoe please verify in master.

**Comment by pixelzoom** [comment]
If the above change is acceptable, please assign back to me after reviewing, so that I can cherry-pick into the 1.3 release branch.

**Comment by KatieWoe** [comment]
Didn't see any problems in master.  For documentation, behavior is now as follows:
1. Quick press and let go while filling will interrupt and stop the flow (this always seems to have been the case.)
2. Pressing and holding down will cause the stream to continue until the .5 mark and then stop.  At that point the button is no longer depressed and you loose the ability to drag the dropper around.  When you let go everything behaves normally.

@pixelzoom @arouinfar if this is all as intended this is ready for another rc.
![suddenstopparttwo](https://user-images.githubusercontent.com/41024075/62067171-53572c00-b1f0-11e9-8bbe-313002caf406.gif)
![suddenstop](https://user-images.githubusercontent.com/41024075/62067176-56eab300-b1f0-11e9-8549-67bfb679b156.gif)

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.   If this is cool with @arouinfar, then it will appear in 1.3.0-rc.3.

**Comment by arouinfar** [comment]
The behavior described in https://github.com/phetsims/ph-scale/issues/91#issuecomment-516075560 is fine with me.

**Comment by pixelzoom** [comment]
Cherry-picked into the 1.3 branch via the above commit.

**Comment by KatieWoe** [comment]
Looks good rc.3
