### ISSUE TITLE
PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#92]
_pH Scale: Basics_ is on the desired list of sims for a client. That sim is a derivative (subset), so this will actually involve instrumenting _pH Scale_.   

The current status (according to @kathy-phet) is: not high on the client's list, so not high priority. Probably something we need to start thinking about in the beginning of 2020.

**Comment by pixelzoom** [comment]
This now has a milestone - "around end of March or mid April".

**Comment by pixelzoom** [comment]
I'm added phet-io to supportedBrands in package.json, and added top-level (Screen, ScreenView, Model) tandems.  So this is ready to start basic instrumentation.

**Comment by pixelzoom** [comment]
I did an instrumentation sprint to see what issues I'd run into.  Most of the basic instrumentation is done.   Look for "TODO #92" comments in the code to identify things that need to be be discussed, addressed, etc.

**Comment by pixelzoom** [comment]
@arouinfar @kathy-phet @ariel-phet:

Basic instrumentation is done, all required tandems are present, and the sim is passing validation. You can test drive in Studio at [1.4.0-dev.5](https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.5/phet-io/) (password protected).  

Some issues to discuss at design meeting:

- [ ]  This is an older sim, and predates some common-code components. Should parts of the sim be rewritten to use those common-code components, so we can take advantage of phet-io and a11y instrumentation? See #95, #96, #100.

- [ ] Which additional subcomponents of view elements need to be instrumented?

- [ ] There is a fixed set of solutes that are reused for all screens. You can find them in Studio at `phScale.global.model.solutes`.  Is this the best place for them?

- [ ] Do we need an API for solutes? What do you want to be able to find out about a solute?

- [ ] Does the color Property for the solution need to be instrumented?

- [ ] What is the best way to disable the "Neutral" indicator feature? (as requested by the client) Should this be done via a query parameter? Or should we add a PhET-iO-only Property?

- [ ] In the _My Solution_ screen, a new solute is created each time there is a pH change. This doesn't work well with PhET-iO.  What do we want to do here?  What do you want to see in the Studio tree?  Creating a "custom solute" class seems most correct, but will be a nontrivial change.

- [ ] There's a feature that autofills the beaker at startup and reset, or when a new solute is selected. It's used in ph-scale, but not in ph-scale-basics. Do we need to be able to disable this feature?

- [ ] ABSwitch has structural problems that make it have a nested OnOffSwitch, see https://github.com/phetsims/sun/issues/559.  Does this need to be addressed?

- [ ] Visibility of several Nodes are controlled by an associated Property. Should their `visibleProperty` be read-only so we can't get into trouble?  (LinearGraph, LogarithmicGraph, RatioNode, MoleculesNode, PHMeterNode)

- [ ] `beakerNode` and `solutionNode` are currently siblings. Should `solutionNode` be a child of `beakerNode`, so that the solution is "in" the beaker? 

- [ ] In _My Solutions_ screen, there is just a solution, whose pH we can change.  But it uses the same model as the other screens, so there are Properties that we probably don't want to see here: `soluteVolumeProperty` and `waterVolumeProperty`.  Should we hide these for this screen?

**Comment by pixelzoom** [comment]
The design doc, including client requirements, can be found at [pH Scale: PhET-iO Design](https://docs.google.com/document/d/1RrILoln3Jdo1hSA1eOtTJN-j8015Q9clqP1caORVYCE/edit?ts=5e39ad31#heading=h.6y75prk97rmc)

**Comment by arouinfar** [comment]
> Review all open GitHub issues. Are there any that need to be addressed before this sim can be published out of master?

I do not see any issues opened prior to the PhET-iO work that would need to be addressed before publication.

> After browsing the Studio tree... Which additional subcomponents of view elements should be instrumented?

It would be best if the TODOs in https://github.com/phetsims/ph-scale/issues/92#issuecomment-581709192 could be addressed before @kathy-phet and I review the sim in studio. @pixelzoom can you re-assign us when it's ready for review?

**Comment by pixelzoom** [comment]
Feedback on initial instrumentation has been requested in #117.

**Comment by pixelzoom** [comment]
Feedback on initial PhET-iO instrumentation was completed in #117, and all resulting GitHub issues have been either addressed or deferred.  The sim is now ready to identify featured elements using Studio, tracking in #146.

**Comment by pixelzoom** [comment]
"Featured" design #146 was complete on 4/16/20.   

When blocking issues have been addressed, dev versions will be published and provided to the client in #164.

**Comment by pixelzoom** [comment]
Dev version was provided to the client awhile ago.  Feedback was received, no change requests.   So closing this issue.
