### ISSUE TITLE
setting maxWidth for listboxParent causes scale/position problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#93]
See phetsims/sun#542.

**Comment by pixelzoom** [comment]
Fixed in the above commit.

**Comment by pixelzoom** [comment]
Looks like this problem (https://github.com/phetsims/sun/issues/542) is reoccurring.  @arouinfar reported on Slack:

> I was looking at some examples of how ComboBox handles i18n, and I noticed that the latest published version of pH Scale is not handling `stringTest=long`  very gracefully. The problem started appearing in 1.3.0, but is not present in master. With the PhET-iO work going on, I doubt this would be the time to fix it up in a maintenance release, but I wanted to make you aware (if you weren’t already). It isn’t something sim-breaking, just not very pretty.

![image](https://user-images.githubusercontent.com/3046552/75376158-c7dc7100-588c-11ea-8771-6d404c5c20d7.png)

**Comment by pixelzoom** [comment]
@arouinfarI I could not reproduce this in master, so I re-read your description above.  You said " the latest published version".  And that's a fact -- it's broken in the latest published version, which is on the 1.3 branch.   This issue was marked "status:fixed-awaiting-deploy" because it had been fixed in master, and needs to be tested the next time we create a release branch.  There is no plan to patch it in the 1.3 branch.

**Comment by pixelzoom** [comment]
@arouinfar If for some reason you can re-produce this in master, please let me know.

**Comment by arouinfar** [comment]
I never saw the problem on master, only in versions 1.3.0-1.3.4.

**Comment by pixelzoom** [comment]
To regression test:

Run the sim normally, and confirm that the listbox is the same width as the combo box button, and aligned with the button, like in this screenshot:

<img width="317" alt="screenshot_242" src="https://user-images.githubusercontent.com/3046552/78610888-0b7ab100-7823-11ea-8cf8-1eafc2d4de62.png">

Run the sim with `?stringTest=long`, and confirm that the listbox is still the same width as the combo box button, and aligned with the button, like in this screenshot:

<img width="408" alt="screenshot_243" src="https://user-images.githubusercontent.com/3046552/78610903-103f6500-7823-11ea-968c-a573e782db5f.png">

**Comment by KatieWoe** [comment]
Looks good in https://github.com/phetsims/QA/issues/514
