### ISSUE TITLE
use SUN/NumberSpinner

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ph-scale#95]
The pH meter in MySolutions (`PHMeterNode`) should be using `NumberSpinner`.  It predates `NumberSpinner`, so is currently rolling its own value display and `ArrowButton` instances.  This is important for phet-io and a11y.

**Comment by pixelzoom** [comment]
The pH meter in _My Solutions_ screen is now using NumberSpinner.  Again, it is not (and cannot be) pixel identical to the previous implementation.   

@arouinfar please compare master to the published version.  If this looks reasonable, you can close.

**Comment by arouinfar** [comment]
Looks good in master @pixelzoom.
